Repository elastic/stack-docs, pull requests merged in 2018-07, with the labels that each got.

#74 [DOCS] Updates the introduction in the machine learning tutorial
  docs/en/stack/getting-started/get-started-trial.asciidoc
  docs/en/stack/getting-started/images/management-license.png
  docs/en/stack/ml/getting-started.asciidoc
Labels: :ml, v6.3.2, v6.4.0, v7.0.0

#63 Use .\metricbeat.exe when executing from the CWD
  docs/en/stack/getting-started/get-started-stack.asciidoc
Labels: needs_backport

#75 [DOCS] Update ML tutorial for when security is not enabled
  docs/en/stack/ml/getting-started-data.asciidoc
  docs/en/stack/ml/getting-started-multi.asciidoc
  docs/en/stack/ml/getting-started-single.asciidoc
  docs/en/stack/ml/getting-started-wizards.asciidoc
Labels: :ml, v6.3.2, v6.4.0, v7.0.0

#85 [DOCS] Moves monitor troubleshooting content kibana repo
  docs/en/stack/monitoring/troubleshooting.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: v6.3.2, v6.4.0, v7.0.0

#84 [DOCS] Adds overview for machine learning rules and filters
  docs/en/stack/ml/overview.asciidoc
  docs/en/stack/ml/rules.asciidoc
Labels: :ml, v6.4.0, v7.0.0

#90 [DOCS] Updates version information
  docs/en/stack/index.asciidoc
Labels: v6.5.0

#89 Document that field-level security should not be set on field aliases.
  docs/en/stack/security/authorization/field-level-security.asciidoc
Labels: :Security

#96 [DOCS] Removes X-Pack from monitoring images
  docs/en/stack/monitoring/images/architecture1.jpg
  docs/en/stack/monitoring/images/architecture2.jpg
  docs/en/stack/monitoring/images/architecture3.jpg
Labels: :Monitoring, v6.3.3, v6.4.0, v6.5.0, v7.0.0

#94 [DOCS] Adds security note to upgrade instructions
  docs/upgrading-stack.asciidoc
Labels: v6.3.3

#95 [DOCS] Link custom rule pages
  docs/en/stack/ml/rules.asciidoc
Labels: :ml, v6.4.0, v6.5.0, v7.0.0
