Repository elastic/stack-docs, pull requests merged in 2018-06, with the labels that each got.

#51 [DOCS] Removes or renames X-Pack-specific pages
  docs/en/stack/InstallationFlow.jpg
  docs/en/stack/gs-index.asciidoc
  docs/en/stack/index.asciidoc
  docs/en/stack/introduction.asciidoc
  docs/en/stack/license.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/monitoring/how-monitoring-works.asciidoc
  docs/en/stack/monitoring/intro.asciidoc
  docs/en/stack/release-notes/7.0.0-alpha1.asciidoc
  docs/en/stack/troubleshooting.asciidoc
  docs/en/stack/xpack-apis.asciidoc
  docs/en/stack/xpack-breaking-changes.asciidoc
  docs/en/stack/xpack-enabling.asciidoc
  docs/en/stack/xpack-features.asciidoc
  docs/en/stack/xpack-introduction.asciidoc
  docs/en/stack/xpack-release-notes.asciidoc
  docs/en/stack/xpack-settings.asciidoc
  docs/en/stack/xpack-setup.asciidoc
  docs/en/stack/xpack-uninstalling.asciidoc
  docs/en/stack/xpack-upgrading.asciidoc
Labels: v7.0.0

#52 [DOCS] Moves the machine learning overview source files
  docs/en/stack/index.asciidoc
  docs/en/stack/ml/analyzing.asciidoc
  docs/en/stack/ml/architecture.asciidoc
  docs/en/stack/ml/buckets.asciidoc
  docs/en/stack/ml/calendars.asciidoc
  docs/en/stack/ml/datafeeds.asciidoc
  docs/en/stack/ml/forecasting.asciidoc
  docs/en/stack/ml/images/ml-gs-job-analysis.jpg
  docs/en/stack/ml/images/ml-gs-job-forecast.jpg
  docs/en/stack/ml/index.asciidoc
  docs/en/stack/ml/jobs.asciidoc
  docs/en/stack/ml/overview.asciidoc
Labels: v6.3.0, v6.4.0, v7.0.0

#53 [DOCS] Moves authentication overview to stack-docs
  docs/en/stack/index.asciidoc
  docs/en/stack/security/authentication/active-directory-realm.asciidoc
  docs/en/stack/security/authentication/built-in-users.asciidoc
  docs/en/stack/security/authentication/custom-realm.asciidoc
  docs/en/stack/security/authentication/file-realm.asciidoc
  docs/en/stack/security/authentication/internal-users.asciidoc
  docs/en/stack/security/authentication/ldap-realm.asciidoc
  docs/en/stack/security/authentication/native-realm.asciidoc
  docs/en/stack/security/authentication/overview.asciidoc
  docs/en/stack/security/authentication/pki-realm.asciidoc
  docs/en/stack/security/authentication/realms.asciidoc
  docs/en/stack/security/authentication/saml-realm.asciidoc
  docs/en/stack/security/getting-started.asciidoc
  docs/en/stack/security/how-security-works.asciidoc
  docs/en/stack/security/index.asciidoc
Labels: :Security, v6.3.0, v6.4.0, v7.0.0

#56 [DOCS] Removes X-Pack feature pages
  docs/en/stack/index.asciidoc
  docs/en/stack/xpack-features.asciidoc
Labels: v6.3.0, v6.4.0, v7.0.0

#57 [DOCS] Move ML getting started to stack-docs
  docs/en/stack/limitations.asciidoc
  docs/en/stack/ml/getting-started-data.asciidoc
  docs/en/stack/ml/getting-started-forecast.asciidoc
  docs/en/stack/ml/getting-started-multi.asciidoc
  docs/en/stack/ml/getting-started-next.asciidoc
  docs/en/stack/ml/getting-started-single.asciidoc
  docs/en/stack/ml/getting-started-wizards.asciidoc
  docs/en/stack/ml/getting-started.asciidoc
  docs/en/stack/ml/images/ml-gs-aggregations.jpg
  docs/en/stack/ml/images/ml-gs-duration.jpg
  docs/en/stack/ml/images/ml-gs-forecast-actual.jpg
  docs/en/stack/ml/images/ml-gs-forecast-open.jpg
  docs/en/stack/ml/images/ml-gs-forecast-results.jpg
  docs/en/stack/ml/images/ml-gs-forecast.jpg
  docs/en/stack/ml/images/ml-gs-job1-analysis.jpg
  docs/en/stack/ml/images/ml-gs-job1-anomalies.jpg
  docs/en/stack/ml/images/ml-gs-job1-datafeed.jpg
  docs/en/stack/ml/images/ml-gs-job1-explorer-anomaly.jpg
  docs/en/stack/ml/images/ml-gs-job1-explorer.jpg
  docs/en/stack/ml/images/ml-gs-job1-manage1.jpg
  docs/en/stack/ml/images/ml-gs-job1-results.jpg
  docs/en/stack/ml/images/ml-gs-job1-time.jpg
  docs/en/stack/ml/images/ml-gs-job1.jpg
  docs/en/stack/ml/images/ml-gs-job2-explorer-anomaly.jpg
  docs/en/stack/ml/images/ml-gs-job2-explorer-host.jpg
  docs/en/stack/ml/images/ml-gs-job2-explorer-table.jpg
  docs/en/stack/ml/images/ml-gs-job2-explorer.jpg
  docs/en/stack/ml/images/ml-gs-job2-split.jpg
  docs/en/stack/ml/images/ml-gs-multi-job.jpg
  docs/en/stack/ml/images/ml-gs-single-job.jpg
  docs/en/stack/ml/limitations.asciidoc
  docs/en/stack/ml/troubleshooting.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: v6.3.0, v6.4.0, v7.0.0

#54 [DOCS] Clarifies authorization overview
  docs/en/stack/security/authorization/images/authorization.png
  docs/en/stack/security/authorization/overview.asciidoc
  docs/en/stack/security/how-security-works.asciidoc
Labels: :Security, v6.3.0, v6.4.0, v7.0.0

#46 Move getting started content and make it more generic
  docs/en/stack/getting-started/get-started-stack.asciidoc
  docs/en/stack/images/metricbeat-system-host-details.png
  docs/en/stack/images/metricbeat-system-overview.png
  docs/en/stack/index.asciidoc
  docs/en/stack/introduction.asciidoc
Labels: review

#64 Alphabetize list of beats
  docs/en/stack/getting-started/get-started-stack.asciidoc
Labels: needs_backport

#65 Fix broken link
  docs/installing-stack.asciidoc
Labels: needs_backport

#67 [DOCS] Clarifies Logstash gotchas
  docs/en/stack/getting-started/get-started-stack.asciidoc
Labels: v6.3.1, v6.4.0, v7.0.0

#55 [DOCS] Creates field and document level security overview
  docs/en/stack/security/authorization/document-level-security.asciidoc
  docs/en/stack/security/authorization/field-level-security.asciidoc
  docs/en/stack/security/authorization/index.asciidoc
Labels: :Security, v6.3.0, v6.4.0, v7.0.0

#73 [DOCS] Clarified license management
  docs/en/stack/license.asciidoc
Labels: v6.3.1, v6.4.0, v7.0.0
