Repository elastic/stack-docs, pull requests merged in 2018-08, with the labels that each got.

#101 [DOCS] Refer to rules as custom rules
  docs/en/stack/ml/rules.asciidoc
Labels: :ml, review, v6.4.0, v6.5.0, v7.0.0

#99 [DOCS] Adds link for ML getting started scripts
  docs/en/stack/ml/getting-started-multi.asciidoc
  docs/en/stack/ml/getting-started-single.asciidoc
Labels: :ml, v6.3.3, v6.4.0, v6.5.0, v7.0.0

#102 [DOCS] Refer to rules feature as custom rules
  docs/en/stack/ml/rules.asciidoc
Labels: :ml, v6.4.0, v6.5.0, v7.0.0

#88 Adding RBAC Phase 1 Docs
  docs/en/stack/security/authorization/built-in-roles.asciidoc
Labels: v6.4.0, v6.5.0, v7.0.0

#106 [DOCS] Updates link to role mapping API
  docs/en/stack/security/authentication/ldap-realm.asciidoc
Labels: v6.3.3, v6.4.1, v6.5.0, v7.0.0

#104 [DOCS] Adds overview of application privileges
  docs/en/stack/security/authorization/privileges.asciidoc
Labels: v6.4.1, v6.5.0, v7.0.0

#100 Add documentation for authorization_realms
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authentication/realm-chains.asciidoc
  docs/en/stack/security/authentication/realms.asciidoc
Labels: :Security, v6.5.0, v7.0.0

#110 [DOCS] Creates Getting Started book
  docs/en/getting-started/get-started-stack.asciidoc
  docs/en/getting-started/images/metricbeat-system-host-details.png
  docs/en/getting-started/images/metricbeat-system-overview.png
  docs/en/getting-started/index.asciidoc
  docs/en/stack/get-started-trial.asciidoc
  docs/en/stack/images/management-license.png
  docs/en/stack/index.asciidoc
  docs/en/stack/introduction.asciidoc
  docs/en/stack/ml/getting-started.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
Labels: v6.3.3, v6.4.1, v6.5.0, v7.0.0

#107 [DOCS] Updates location of ML pages
  docs/en/stack/index.asciidoc
  docs/en/stack/ml/api-quickref.asciidoc
  docs/en/stack/ml/index.asciidoc
Labels: v6.3.3, v6.4.1, v6.5.0, v7.0.0
