Repository elastic/stack-docs, pull requests merged in 2018-11, with the labels that each got.

#141 [DOCS] Adds machine learning limitation related to rollups
  docs/en/stack/ml/limitations.asciidoc
Labels: v6.3.3, v6.4.3, v6.5.0, v6.6.0, v7.0.0

#143 [DOCS] Adds remote_monitoring_user to security tutorial
  docs/en/stack/security/get-started-builtin-users.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
Labels: :Security, v6.5.0, v6.6.0, v7.0.0

#138 [DOCS] Minimizes the duplicated information in the production monitoring page
  docs/en/stack/monitoring/production.asciidoc
Labels: :Monitoring, review, v6.5.0, v6.6.0, v7.0.0

#142 Initialize docs for the infrastructure monitoring
  docs/en/infraops/add-data.png
  docs/en/infraops/index.asciidoc
  docs/en/infraops/infra-ui-intro.asciidoc
  docs/en/infraops/installation.asciidoc
  docs/en/infraops/logs-ui-intro.asciidoc
  docs/en/infraops/monitoring-architecture.png
  docs/en/infraops/overview.asciidoc
  docs/en/infraops/screenshot-logs-ui.jpg
  docs/en/infraops/screenshot-metrics-infrastructure-monitoring.jpg
  docs/en/infraops/screenshot-systems-monitoring.jpg
Labels: WIP

#145 Backport to 6.x: PR #142
  docs/en/infraops/add-data.png
  docs/en/infraops/index.asciidoc
  docs/en/infraops/infra-ui-intro.asciidoc
  docs/en/infraops/installation.asciidoc
  docs/en/infraops/logs-ui-intro.asciidoc
  docs/en/infraops/monitoring-architecture.png
  docs/en/infraops/overview.asciidoc
  docs/en/infraops/screenshot-logs-ui.jpg
  docs/en/infraops/screenshot-metrics-infrastructure-monitoring.jpg
  docs/en/infraops/screenshot-systems-monitoring.jpg
Labels: backport

#146 Backport to 6.x: PR #142
  docs/en/infraops/add-data.png
  docs/en/infraops/index.asciidoc
  docs/en/infraops/infra-ui-intro.asciidoc
  docs/en/infraops/installation.asciidoc
  docs/en/infraops/logs-ui-intro.asciidoc
  docs/en/infraops/monitoring-architecture.png
  docs/en/infraops/overview.asciidoc
  docs/en/infraops/screenshot-logs-ui.jpg
  docs/en/infraops/screenshot-metrics-infrastructure-monitoring.jpg
  docs/en/infraops/screenshot-systems-monitoring.jpg
Labels: backport

#148 [DOCS] Adds machine learning limitations related to Kibana spaces
  docs/en/stack/ml/limitations.asciidoc
Labels: :ml, v6.5.0, v6.6.0, v7.0.0

#150 Add changes from review
  docs/en/infraops/installation.asciidoc
  docs/en/infraops/overview.asciidoc
Labels: needs_backport, review

#149 [DOCS] Adds read_ccr and manage_ccr privileges
  docs/en/stack/security/authorization/privileges.asciidoc
Labels: :Security, v6.5.0, v6.6.0, v7.0.0

#135 Troubleshooting SAML doc
  docs/en/stack/security/troubleshooting.asciidoc
Labels: :Security

#154 [DOCS] Stack Overview cleanup
  docs/en/stack/license.asciidoc
  docs/en/stack/ml/analyzing.asciidoc
  docs/en/stack/ml/architecture.asciidoc
  docs/en/stack/ml/buckets.asciidoc
  docs/en/stack/ml/forecasting.asciidoc
  docs/en/stack/ml/getting-started-data.asciidoc
  docs/en/stack/ml/getting-started-forecast.asciidoc
  docs/en/stack/ml/getting-started-multi.asciidoc
  docs/en/stack/ml/getting-started-single.asciidoc
  docs/en/stack/ml/getting-started-wizards.asciidoc
  docs/en/stack/ml/getting-started.asciidoc
  docs/en/stack/ml/limitations.asciidoc
  docs/en/stack/ml/troubleshooting.asciidoc
  docs/en/stack/monitoring/troubleshooting.asciidoc
  docs/en/stack/security/authorization/built-in-roles.asciidoc
  docs/en/stack/security/limitations.asciidoc
  docs/en/stack/security/troubleshooting.asciidoc
  docs/en/stack/troubleshooting.asciidoc
  docs/en/stack/watcher/limitations.asciidoc
  docs/en/stack/watcher/troubleshooting.asciidoc
  docs/en/stack/xpack-enabling.asciidoc
  docs/index.asciidoc
Labels: v6.6.0, v7.0.0
