Repository elastic/stack-docs, pull requests merged in 2019-12, with the labels that each got.

#658 [DOCS] [FOR 7.5] Remove temporary "future docs" banner from 7.5 release docs
  docs/en/logs/page_header.html
  docs/en/metrics/page_header.html
Labels: Infrastructure monitoring, v7.5.0

#654 [DOCS] [FOR 7.5] Add superseded banner to older versions of Infrastructure Monitoring Guide
  docs/en/infraops/page_header.html
Labels: Infrastructure monitoring, v6.5.0, v6.6.0, v6.7.0, v6.8.0, v7.0.0, v7.1.0, v7.2.0, v7.3.0, v7.4.0

#711 [7.x] Removes temporary "future docs" page headers (#658)
  docs/en/logs/page_header.html
  docs/en/metrics/page_header.html
Labels: backport

#712 [7.5] Removes temporary "future docs" page headers (#658)
  docs/en/logs/page_header.html
  docs/en/metrics/page_header.html
Labels: backport

#720 [6.5] [DOCS] [FOR 7.5] Add superseded banner to older versions of Infrastructure Monitoring Guide (#654)
  docs/en/infraops/page_header.html
Labels: backport

#719 [6.6] [DOCS] [FOR 7.5] Add superseded banner to older versions of Infrastructure Monitoring Guide (#654)
  docs/en/infraops/page_header.html
Labels: backport

#718 [6.7] [DOCS] [FOR 7.5] Add superseded banner to older versions of Infrastructure Monitoring Guide (#654)
  docs/en/infraops/page_header.html
Labels: backport

#717 [6.8] [DOCS] [FOR 7.5] Add superseded banner to older versions of Infrastructure Monitoring Guide (#654)
  docs/en/infraops/page_header.html
Labels: backport

#716 [7.0] [DOCS] [FOR 7.5] Add superseded banner to older versions of Infrastructure Monitoring Guide (#654)
  docs/en/infraops/page_header.html
Labels: backport

#715 [7.1] [DOCS] [FOR 7.5] Add superseded banner to older versions of Infrastructure Monitoring Guide (#654)
  docs/en/infraops/page_header.html
Labels: backport

#714 [7.2] [DOCS] [FOR 7.5] Add superseded banner to older versions of Infrastructure Monitoring Guide (#654)
  docs/en/infraops/page_header.html
Labels: backport

#713 [7.3] [DOCS] [FOR 7.5] Add superseded banner to older versions of Infrastructure Monitoring Guide (#654)
  docs/en/infraops/page_header.html
Labels: backport

#700 Remove deleted pages from Stack Overview
  docs/en/getting-started/get-started-stack.asciidoc
  docs/en/stack/introduction.asciidoc
  docs/en/stack/license.asciidoc
  docs/en/stack/ml/anomaly-detection/stopping-ml.asciidoc
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/redirects.asciidoc
Labels: v8.0.0

#694 Adds OOM banners in stack books
  docs/en/getting-started/page_header.html
  docs/en/install-upgrade/page_header.html
  docs/en/stack/page_header.html
Labels: v6.3.4, v6.4.4, v6.5.5, v6.6.3, v6.7.3, v7.0.2, v7.1.2, v7.2.2, v7.3.2, v7.4.3

#723 [DOCS] Puts regression model info into a separated section
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
Labels: :ml, v7.4.3, v7.5.1, v7.6.0, v8.0.0

#729 [SIEM] [Docs] Fixes ecs field name in map connection lines note
  docs/en/siem/siem-ui.asciidoc
Labels: v7.4.0, v7.5.0

#730 [SIEM] [Docs][Backport]Fixes ECS field name in map connection lines note
  docs/en/siem/siem-ui.asciidoc
Labels: backport

#731 [SIEM] [Docs][Backport]Fixes ECS field name in map connection lines note
  docs/en/siem/siem-ui.asciidoc
Labels: v7.5.0

#722 [Docs] [SIEM] ML threshold tuning procedure
  docs/en/siem/images/ml-rule-threshold.png
  docs/en/siem/images/rule-scope.png
  docs/en/siem/machine-learning.asciidoc
  docs/en/siem/tune-anomaly-results.asciidoc
Labels: :ml, Team:SIEM, v7.5.0, v7.6.0

#733 [SIEM][Docs][Backport]ML threshold tuning procedure 7.5
  docs/en/siem/images/ml-rule-threshold.png
  docs/en/siem/images/rule-scope.png
  docs/en/siem/machine-learning.asciidoc
  docs/en/siem/tune-anomaly-results.asciidoc
Labels: v7.5.0

#704 [DOCS] Expands DFA limitations section with runtime paragraph
  docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
Labels: :ml, v7.3.2, v7.4.3, v7.5.1, v7.6.0, v8.0.0

#727 [DOCS] Changes section title in classification conceptual docs
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
Labels: v7.5.1, v7.6.0, v8.0.0

#737 [DOCS] Fine-tunes regression docs section titles
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
Labels: :ml, v7.4.3, v7.5.1, v7.6.0, v8.0.0

#736 [7.2][DOCS] Remove CCR docs from Stack Overview (#464)
  docs/en/stack/index.asciidoc
  docs/en/stack/redirects.asciidoc
Labels: backport

#742 [7.1][DOCS] Remove CCR docs from Stack Overview (#464)
  docs/en/stack/index.asciidoc
  docs/en/stack/redirects.asciidoc
Labels: backport

#743 [7.0][DOCS] Remove CCR docs from Stack Overview (#464)
  docs/en/stack/index.asciidoc
  docs/en/stack/redirects.asciidoc
Labels: backport

#744 [6.8][DOCS] Remove CCR docs from Stack Overview (#464)
  docs/en/stack/index.asciidoc
  docs/en/stack/redirects.asciidoc
Labels: backport

#745 [6.7][DOCS] Remove CCR docs from Stack Overview (#464)
  docs/en/stack/index.asciidoc
  docs/en/stack/redirects.asciidoc
Labels: backport

#740 [DOCS] Added older release notice.
  docs/en/getting-started/page_header.html
  docs/en/install-upgrade/page_header.html
  docs/en/stack/page_header.html
Labels: v6.8.5

#741 [DOCS] Remove custom page_header.html
  docs/en/stack/page_header.html
Labels: v6.4.4, v6.5.5, v6.6.3, v6.7.3, v7.0.2, v7.1.2, v7.2.2, v7.3.2, v7.4.3

#746 [6.5][DOCS] Remove CCR docs from Stack Overview (#464)
  docs/en/stack/index.asciidoc
  docs/en/stack/redirects.asciidoc
Labels: backport

#747 [6.6][DOCS] Remove CCR docs from Stack Overview (#464)
  docs/en/stack/index.asciidoc
  docs/en/stack/redirects.asciidoc
Labels: backport

#739 [SIEM][Docs]Clarifies SIEM index and Kibana index pattern requirements
  docs/en/siem/installation.asciidoc
  docs/en/siem/siem-ui.asciidoc
Labels: Team:SIEM, v7.5.0

#749 [SIEM][Docs][Backport]Clarifies SIEM index and Kibana index pattern requirements
  docs/en/siem/installation.asciidoc
  docs/en/siem/siem-ui.asciidoc
Labels: v7.5.0

#750 [DOCS] Removes link refering to hyperparameter optimization in Limitations
  docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
Labels: :ml, v7.6.0, v8.0.0

#751 [DOCS] Adds link refering to hyperparameter optimization to Limitations
  docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
Labels: :ml, v7.6.0, v8.0.0

#760 [DOCS] Adds Jupyter noetbook link to the classification example
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
Labels: :ml, v7.5.1, v7.6.0, v8.0.0

#762 [DOCS] Adds a Jupyter notebook link to the outlier detection example
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
Labels: :ml, v7.5.1, v7.6.0, v8.0.0

#766 [7.1] Moves ML content to anomaly-detection folder (#430)
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/ml/anomaly-detection/analyzing.asciidoc
  docs/en/stack/ml/anomaly-detection/api-quickref.asciidoc
  docs/en/stack/ml/anomaly-detection/architecture.asciidoc
  docs/en/stack/ml/anomaly-detection/buckets.asciidoc
  docs/en/stack/ml/anomaly-detection/calendars.asciidoc
  docs/en/stack/ml/anomaly-detection/create-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/datafeeds.asciidoc
  docs/en/stack/ml/anomaly-detection/forecasting.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-data.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-forecast.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-multi.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-next.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-single.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-wizards.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started.asciidoc
  docs/en/stack/ml/anomaly-detection/images/ml-create-job.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-data-recognizer-auditbeat.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-data-recognizer-filebeat.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-aggregations.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-create-job.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-dates.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-keywords.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-metrics.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-topmetrics.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-visualizer.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-duration.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast-actual.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast-open.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast-results.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job-analysis.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job-forecast.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-analysis.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-anomalies.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-datafeed.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-explorer-anomaly.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-explorer.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-manage1.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-results.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-time.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer-anomaly.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer-host.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer-table.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-split.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-multi-job.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-single-job.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-start-feed.jpg
  docs/en/stack/ml/anomaly-detection/images/multibucketanalysis.jpg
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/job-tips.asciidoc
  docs/en/stack/ml/anomaly-detection/jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/limitations.asciidoc
  docs/en/stack/ml/anomaly-detection/overview.asciidoc
  docs/en/stack/ml/anomaly-detection/rules.asciidoc
  docs/en/stack/ml/anomaly-detection/troubleshooting.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#767 [7.0] Moves ML content to anomaly-detection folder (#430)
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/ml/anomaly-detection/analyzing.asciidoc
  docs/en/stack/ml/anomaly-detection/api-quickref.asciidoc
  docs/en/stack/ml/anomaly-detection/architecture.asciidoc
  docs/en/stack/ml/anomaly-detection/buckets.asciidoc
  docs/en/stack/ml/anomaly-detection/calendars.asciidoc
  docs/en/stack/ml/anomaly-detection/create-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/datafeeds.asciidoc
  docs/en/stack/ml/anomaly-detection/forecasting.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-data.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-forecast.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-multi.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-next.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-single.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-wizards.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started.asciidoc
  docs/en/stack/ml/anomaly-detection/images/ml-create-job.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-data-recognizer-auditbeat.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-data-recognizer-filebeat.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-aggregations.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-create-job.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-dates.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-keywords.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-metrics.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-topmetrics.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-visualizer.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-duration.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast-actual.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast-open.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast-results.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job-analysis.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job-forecast.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-analysis.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-anomalies.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-datafeed.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-explorer-anomaly.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-explorer.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-manage1.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-results.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-time.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer-anomaly.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer-host.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer-table.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-split.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-multi-job.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-single-job.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-start-feed.jpg
  docs/en/stack/ml/anomaly-detection/images/multibucketanalysis.jpg
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/job-tips.asciidoc
  docs/en/stack/ml/anomaly-detection/jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/limitations.asciidoc
  docs/en/stack/ml/anomaly-detection/overview.asciidoc
  docs/en/stack/ml/anomaly-detection/rules.asciidoc
  docs/en/stack/ml/anomaly-detection/troubleshooting.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#755 Add conceptual overview of model snapshots
  docs/en/stack/ml/anomaly-detection/ml-concepts.asciidoc
  docs/en/stack/ml/anomaly-detection/model-snapshots.asciidoc
Labels: :ml, v7.5.2, v7.6.0, v8.0.0

#768 [6.8] Moves ML content to anomaly-detection folder (#430)
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/ml/anomaly-detection/analyzing.asciidoc
  docs/en/stack/ml/anomaly-detection/api-quickref.asciidoc
  docs/en/stack/ml/anomaly-detection/architecture.asciidoc
  docs/en/stack/ml/anomaly-detection/buckets.asciidoc
  docs/en/stack/ml/anomaly-detection/calendars.asciidoc
  docs/en/stack/ml/anomaly-detection/create-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/datafeeds.asciidoc
  docs/en/stack/ml/anomaly-detection/forecasting.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-data.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-forecast.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-multi.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-next.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-single.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-wizards.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started.asciidoc
  docs/en/stack/ml/anomaly-detection/images/ml-create-job.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-data-recognizer-auditbeat.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-data-recognizer-filebeat.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-aggregations.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-create-job.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-dates.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-keywords.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-metrics.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-topmetrics.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-visualizer.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-duration.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast-actual.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast-open.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast-results.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job-analysis.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job-forecast.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-analysis.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-anomalies.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-datafeed.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-explorer-anomaly.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-explorer.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-manage1.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-results.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-time.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer-anomaly.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer-host.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer-table.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-split.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-multi-job.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-single-job.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-start-feed.jpg
  docs/en/stack/ml/anomaly-detection/images/multibucketanalysis.jpg
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/job-tips.asciidoc
  docs/en/stack/ml/anomaly-detection/jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/limitations.asciidoc
  docs/en/stack/ml/anomaly-detection/overview.asciidoc
  docs/en/stack/ml/anomaly-detection/rules.asciidoc
  docs/en/stack/ml/anomaly-detection/troubleshooting.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#764 [DOCS] Adds bucket results section and detail
  docs/en/stack/ml/anomaly-detection/buckets.asciidoc
  docs/en/stack/ml/anomaly-detection/create-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
  docs/en/stack/ml/anomaly-detection/stopping-ml.asciidoc
Labels: :ml, v7.5.2, v7.6.0, v8.0.0

#769 [7.1] Drafts index.asciidoc for ML Guide
  docs/en/stack/license.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-next.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started.asciidoc
  docs/en/stack/ml/anomaly-detection/troubleshooting.asciidoc
  docs/en/stack/ml/get-started-trial.asciidoc
  docs/en/stack/ml/images/management-license.png
  docs/en/stack/ml/index.asciidoc
Labels: backport

#770 [7.0] Drafts index.asciidoc for ML Guide
  docs/en/stack/license.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-next.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started.asciidoc
  docs/en/stack/ml/anomaly-detection/troubleshooting.asciidoc
  docs/en/stack/ml/get-started-trial.asciidoc
  docs/en/stack/ml/images/management-license.png
  docs/en/stack/ml/index.asciidoc
Labels: backport

#771 [6.8] Drafts index.asciidoc for ML Guide
  docs/en/stack/license.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-next.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started.asciidoc
  docs/en/stack/ml/anomaly-detection/troubleshooting.asciidoc
  docs/en/stack/ml/get-started-trial.asciidoc
  docs/en/stack/ml/images/management-license.png
  docs/en/stack/ml/index.asciidoc
Labels: backport

#772 [6.7] Drafts index.asciidoc for ML Guide
  docs/en/install-upgrade/upgrading-stack.asciidoc
  docs/en/stack/index.asciidoc
  docs/en/stack/license.asciidoc
  docs/en/stack/ml/analyzing.asciidoc
  docs/en/stack/ml/buckets.asciidoc
  docs/en/stack/ml/forecasting.asciidoc
  docs/en/stack/ml/get-started-trial.asciidoc
  docs/en/stack/ml/getting-started-forecast.asciidoc
  docs/en/stack/ml/getting-started-multi.asciidoc
  docs/en/stack/ml/getting-started-next.asciidoc
  docs/en/stack/ml/getting-started-single.asciidoc
  docs/en/stack/ml/getting-started-wizards.asciidoc
  docs/en/stack/ml/getting-started.asciidoc
  docs/en/stack/ml/images/management-license.png
  docs/en/stack/ml/index.asciidoc
  docs/en/stack/ml/ml-index.asciidoc
  docs/en/stack/ml/troubleshooting.asciidoc
Labels: backport

#773 [6.6] Drafts index.asciidoc for ML Guide
  docs/en/install-upgrade/upgrading-stack.asciidoc
  docs/en/stack/index.asciidoc
  docs/en/stack/license.asciidoc
  docs/en/stack/ml/analyzing.asciidoc
  docs/en/stack/ml/buckets.asciidoc
  docs/en/stack/ml/forecasting.asciidoc
  docs/en/stack/ml/get-started-trial.asciidoc
  docs/en/stack/ml/getting-started-forecast.asciidoc
  docs/en/stack/ml/getting-started-multi.asciidoc
  docs/en/stack/ml/getting-started-next.asciidoc
  docs/en/stack/ml/getting-started-single.asciidoc
  docs/en/stack/ml/getting-started-wizards.asciidoc
  docs/en/stack/ml/getting-started.asciidoc
  docs/en/stack/ml/images/management-license.png
  docs/en/stack/ml/index.asciidoc
  docs/en/stack/ml/ml-index.asciidoc
  docs/en/stack/ml/troubleshooting.asciidoc
Labels: backport

#774 [6.5] Drafts index.asciidoc for ML Guide (#773)
  docs/en/install-upgrade/upgrading-stack.asciidoc
  docs/en/stack/index.asciidoc
  docs/en/stack/license.asciidoc
  docs/en/stack/ml/analyzing.asciidoc
  docs/en/stack/ml/buckets.asciidoc
  docs/en/stack/ml/forecasting.asciidoc
  docs/en/stack/ml/get-started-trial.asciidoc
  docs/en/stack/ml/getting-started-forecast.asciidoc
  docs/en/stack/ml/getting-started-multi.asciidoc
  docs/en/stack/ml/getting-started-next.asciidoc
  docs/en/stack/ml/getting-started-single.asciidoc
  docs/en/stack/ml/getting-started-wizards.asciidoc
  docs/en/stack/ml/getting-started.asciidoc
  docs/en/stack/ml/images/management-license.png
  docs/en/stack/ml/index.asciidoc
  docs/en/stack/ml/ml-index.asciidoc
  docs/en/stack/ml/troubleshooting.asciidoc
Labels: backport

#775 [6.4] Drafts index.asciidoc for ML Guide
  docs/en/install-upgrade/upgrading-stack.asciidoc
  docs/en/stack/index.asciidoc
  docs/en/stack/license.asciidoc
  docs/en/stack/ml/analyzing.asciidoc
  docs/en/stack/ml/forecasting.asciidoc
  docs/en/stack/ml/get-started-trial.asciidoc
  docs/en/stack/ml/getting-started-forecast.asciidoc
  docs/en/stack/ml/getting-started-multi.asciidoc
  docs/en/stack/ml/getting-started-next.asciidoc
  docs/en/stack/ml/getting-started-single.asciidoc
  docs/en/stack/ml/getting-started-wizards.asciidoc
  docs/en/stack/ml/getting-started.asciidoc
  docs/en/stack/ml/images/management-license.png
  docs/en/stack/ml/index.asciidoc
  docs/en/stack/ml/ml-index.asciidoc
  docs/en/stack/ml/troubleshooting.asciidoc
Labels: backport

#776 [6.3] Drafts index.asciidoc for ML Guide
  docs/en/install-upgrade/upgrading-stack.asciidoc
  docs/en/stack/index.asciidoc
  docs/en/stack/ml/analyzing.asciidoc
  docs/en/stack/ml/forecasting.asciidoc
  docs/en/stack/ml/get-started-trial.asciidoc
  docs/en/stack/ml/getting-started-forecast.asciidoc
  docs/en/stack/ml/getting-started-multi.asciidoc
  docs/en/stack/ml/getting-started-next.asciidoc
  docs/en/stack/ml/getting-started-single.asciidoc
  docs/en/stack/ml/getting-started-wizards.asciidoc
  docs/en/stack/ml/getting-started.asciidoc
  docs/en/stack/ml/images/management-license.png
  docs/en/stack/ml/index.asciidoc
  docs/en/stack/ml/ml-index.asciidoc
  docs/en/stack/ml/troubleshooting.asciidoc
  docs/en/stack/xpack-license.asciidoc
Labels: backport

#765 [DOCS] Adds Jupyter notebook links to the example page
  docs/en/stack/ml/df-analytics/examples.asciidoc
Labels: :ml, v7.5.2, v7.6.0, v8.0.0

#756 [DOCS] Adds conceptual overview for influencers
  docs/en/stack/ml/anomaly-detection/images/influencers.jpg
  docs/en/stack/ml/anomaly-detection/influencers.asciidoc
  docs/en/stack/ml/anomaly-detection/job-tips.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-concepts.asciidoc
Labels: :ml, v7.5.2, v7.6.0, v8.0.0

#777 [DOCS] Removes ML content from Stack Overview
  docs/en/stack/index.asciidoc
  docs/en/stack/redirects.asciidoc
Labels: :ml, v8.0.0

#778 [DOCS] Fixes machine learning links
  docs/60_upgrade_guide.html
  docs/en/siem/machine-learning.asciidoc
  docs/en/siem/tune-anomaly-results.asciidoc
  docs/en/stack/ml/anomaly-detection/create-jobs.asciidoc
Labels: :ml, v8.0.0

#757 [DOCS] Fixes incorrect version and filename in Docker GS examples.
  docs/en/getting-started/docker/.env
  docs/en/getting-started/docker/create-certs.yml
  docs/en/getting-started/docker/elastic-docker-tls.yml
  docs/en/getting-started/get-started-docker.asciidoc
Labels: v7.5.2

#779 [7.2][DOCS] Removes ML content from Stack Overview
  docs/60_upgrade_guide.html
  docs/en/getting-started/get-started-stack.asciidoc
  docs/en/stack/index.asciidoc
  docs/en/stack/license.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/ml/anomaly-detection/create-jobs.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#781 [7.0][DOCS] Removes ML content from Stack Overview (#777)
  docs/60_upgrade_guide.html
  docs/en/getting-started/get-started-stack.asciidoc
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#780 [7.1][DOCS] Removes ML content from Stack Overview
  docs/60_upgrade_guide.html
  docs/en/getting-started/get-started-stack.asciidoc
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/ml/anomaly-detection/job-tips.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#754 [DOCS] Adds how DFA jobs work section
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-phases.asciidoc
Labels: :ml, v7.5.1, v7.6.0, v8.0.0

#782 [6.8][DOCS] Removes ML content from Stack Overview (#777)
  docs/60_upgrade_guide.html
  docs/en/getting-started/get-started-stack.asciidoc
  docs/en/install-upgrade/upgrading-stack.asciidoc
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#783 [6.7][DOCS] Removes ML content from Stack Overview
  docs/60_upgrade_guide.html
  docs/en/getting-started/get-started-stack.asciidoc
  docs/en/install-upgrade/upgrading-stack.asciidoc
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#784 [6.6][DOCS] Removes ML content from Stack Overview
  docs/60_upgrade_guide.html
  docs/en/getting-started/get-started-stack.asciidoc
  docs/en/install-upgrade/upgrading-stack.asciidoc
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#785 [6.5][DOCS] Removes ML content from Stack Overview
  docs/60_upgrade_guide.html
  docs/en/getting-started/get-started-stack.asciidoc
  docs/en/install-upgrade/upgrading-stack.asciidoc
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#786 [6.4][DOCS] Removes ML content from Stack Overview
  docs/60_upgrade_guide.html
  docs/en/getting-started/get-started-stack.asciidoc
  docs/en/install-upgrade/upgrading-stack.asciidoc
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#787 [6.3][DOCS] Removes ML content from Stack Overview
  docs/60_upgrade_guide.html
  docs/en/getting-started/get-started-stack.asciidoc
  docs/en/install-upgrade/upgrading-stack.asciidoc
  docs/en/stack/index.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/xpack-limitations.asciidoc
  docs/en/stack/xpack-troubleshooting.asciidoc
Labels: backport

#738 Adds ecs fields for ml jobs
  docs/en/siem/machine-learning.asciidoc
Labels: Team:SIEM, v7.5.0
