Repository elastic/stack-docs, pull requests merged in 2019-02, with the labels that each got.

#194 [DOCS] Add OS/architecture classifier to distributions
  docs/en/getting-started/get-started-stack.asciidoc
Labels: v7.0.0

#191 [DOCS] Replace use of custom-roles-provider.asciidoc
  docs/en/stack/security/authorization/index.asciidoc
Labels: v7.0.0

#198 Add linux examples to the stack getting started
  docs/en/getting-started/get-started-stack.asciidoc
Labels: needs_backport

#201 [DOCS] Update shared versions file
  docs/en/getting-started/index.asciidoc
  docs/en/infraops/index.asciidoc
  docs/en/secops/index.asciidoc
  docs/en/stack/index.asciidoc
Labels: 7.1.0

#202 Update shared versions file
  docs/en/getting-started/index.asciidoc
  docs/en/infraops/index.asciidoc
  docs/en/secops/index.asciidoc
  docs/en/stack/index.asciidoc
Labels: v7.0.0

#197 [DOCS] Adds breaking changes page with content re-use
  docs/en/install-upgrade/breaking.asciidoc
  docs/index.asciidoc
  docs/upgrading-stack.asciidoc
Labels: v7.0.0, v7.1.0, v8.0.0

#207 Add trb information for InvalidNameIDPolicy
  docs/en/stack/security/troubleshooting.asciidoc
Labels: :Security, v6.7.0, v7.0.0, v7.1.0, v8.0.0

#209 [DOCS] Removes glossary from 7.x
  docs/en/glossary/glossary.asciidoc
  docs/en/glossary/index.asciidoc
  docs/en/glossary/intro.asciidoc
Labels: v7.1.0

#210 Update Infrastructure UI documentation with metric definitions
  docs/en/infraops/installation.asciidoc
Labels: Infrastructure monitoring, review, v6.5.0, v6.6.0, v6.7.0, v7.0.0

#216 [7.x] Update Infrastructure UI documentation with metric definitions
  docs/en/infraops/installation.asciidoc
Labels: backport

#215 [7.0] Update Infrastructure UI documentation with metric definitions
  docs/en/infraops/installation.asciidoc
Labels: backport

#214 [6.7] Update Infrastructure UI documentation with metric definitions
  docs/en/infraops/installation.asciidoc
Labels: backport

#213 [6.6] Update Infrastructure UI documentation with metric definitions
  docs/en/infraops/installation.asciidoc
Labels: backport

#217 [6.6] Add links to Kibana docs (#181)
  docs/en/infraops/infra-ui-intro.asciidoc
  docs/en/infraops/installation.asciidoc
  docs/en/infraops/logs-ui-intro.asciidoc
Labels: backport

#218 [6.7] Add links to Kibana docs (#181)
  docs/en/infraops/infra-ui-intro.asciidoc
  docs/en/infraops/installation.asciidoc
  docs/en/infraops/logs-ui-intro.asciidoc
Labels: backport

#196 [DOCS] Create install-upgrade folder
  docs/en/install-upgrade/index.asciidoc
  docs/en/install-upgrade/installing-stack.asciidoc
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: v5.0.3, v5.1.3, v5.2.3, v5.3.4, v5.4.4, v5.5.4, v5.6.15, v6.0.2, v6.1.5, v6.2.5, v6.3.4, v6.4.4, v6.5.5, v6.6.0, v6.7.0, v7.0.0

#212 DOC Add snapshot_user built-in role
  docs/en/stack/security/authorization/built-in-roles.asciidoc
  docs/en/stack/security/authorization/privileges.asciidoc
Labels: :Security, enhancement, v6.7.0, v7.0.0, v7.1.0, v8.0.0

#219 [DOCS] Remove upgrade step that stops machine learning
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: :ml, v6.7.0, v7.0.0, v7.1.0, v8.0.0

#223 [6.7] [DOCS] Adds missing anchor in Installation Upgrade Guide
  docs/en/install-upgrade/index.asciidoc
Labels: backport, v6.7.0

#220 [DOCS] Update version detail in upgrade instructions
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: v8.0.0

#221 [7.x] [DOCS] Update version detail in upgrade instructions
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: v7.0.0, v7.1.0

#227 [DOCS] Fixes anchor for asciidoctor
  docs/en/getting-started/get-started-stack.asciidoc
Labels: v6.3.3, v6.4.4, v6.5.5, v6.6.2, v6.7.0, v7.0.0, v7.1.0, v8.0.0

#228 [DOCS] Fixes undefined anchor
  docs/en/getting-started/get-started-stack.asciidoc
Labels: v6.3.4, v6.4.4, v6.5.5, v6.6.2, v6.7.0, v7.0.0, v7.1.0, v8.0.0

#230 [DOCS] Fixes inline callout in TLS tutorial
  docs/en/stack/security/securing-communications/tutorial-tls-certificates.asciidoc
Labels: v6.5.5, v6.6.2, v6.7.0, v7.0.0, v7.1.0, v8.0.0
