Repository elastic/stack-docs, pull requests merged in 2019-08, with the labels that each got.

#447 [DOCS] Adds data frame analytics limitations
  docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
  docs/en/stack/ml/df-analytics/index.asciidoc
Labels: :ml/Data Frame, v7.3.0, v7.4.0, v8.0.0

#452 [7.3] [SIEM] Adding section to overview for Machine Learning (#448)
  docs/en/siem/images/ml-ui.png
  docs/en/siem/index.asciidoc
  docs/en/siem/machine-learning.asciidoc
Labels: backport

#451 [7.x] [SIEM] Adding section to overview for Machine Learning (#448)
  docs/en/siem/images/ml-ui.png
  docs/en/siem/index.asciidoc
  docs/en/siem/machine-learning.asciidoc
Labels: backport

#454 [DOCS] Add Kerberos configration redirect
  docs/en/stack/redirects.asciidoc
Labels: :Security, v7.2.1

#450 [DOCS] Adds Beats 7.3 release highlights
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.3.1

#457 Updates monitoring architecture diagram
  docs/en/stack/monitoring/how-monitoring-works.asciidoc
  docs/en/stack/monitoring/images/architecture10.png
  docs/en/stack/monitoring/images/architecture20.png
  docs/en/stack/monitoring/images/architecture30.png
Labels: :Monitoring, v7.3.1, v7.4.0, v8.0.0

#456 Adds instructions for sending Beats monitoring data to ESMS
  docs/en/stack/index.asciidoc
  docs/en/stack/monitoring/esms.asciidoc
  docs/en/stack/monitoring/intro.asciidoc
Labels: :Monitoring, v7.3.1, v7.4.0, v8.0.0

#461 [Backport] Changed wording of packetbeat description for 7.x
  docs/en/siem/installation.asciidoc
Labels: backport

#462 [Backport] Changed wording of packetbeat description for 7.3
  docs/en/siem/installation.asciidoc
Labels: backport

#466 [DOCS] Fixes incorrect substitution in Jobs section
  docs/en/stack/ml/anomaly-detection/jobs.asciidoc
Labels: :ml, v7.2.1, v7.3.1, v7.4.0, v8.0.0

#467 [docs] Update Hadoop to use version attribute
  docs/en/install-upgrade/breaking.asciidoc
Labels: bug

#332 add additional SSLHandshakeException
  docs/en/stack/security/troubleshooting.asciidoc
Labels: :Security, enhancement, v7.3.1, v7.4.0, v8.0.0

#468 [Backport 7.x] add additional SSLHandshakeException
  docs/en/stack/security/troubleshooting.asciidoc
Labels: backport

#469 [Backport 7.3] add additional SSLHandshakeException
  docs/en/stack/security/troubleshooting.asciidoc
Labels: backport

#471 Updates version attributes filename
  docs/en/getting-started/index.asciidoc
  docs/en/infraops/index.asciidoc
  docs/en/stack/index.asciidoc
Labels: v7.5.0
