Repository elastic/stack-docs, pull requests merged in 2019-09, with the labels that each got.

#485 PKI authn in Kibana
  docs/en/stack/security/authentication/pki-realm.asciidoc
Labels: :Security, v7.4.0, v7.5.0, v8.0.0

#476 [DOCS] Spell check and minor tidying up of Infrastructure Monitoring Guide
  .gitignore
  docs/en/infraops/images/add-data.png
  docs/en/infraops/images/infra-sysmon.png
  docs/en/infraops/images/logs-console.png
  docs/en/infraops/images/monitoring-architecture.png
  docs/en/infraops/index.asciidoc
  docs/en/infraops/infra-ui-intro.asciidoc
  docs/en/infraops/infrastructure-metrics.asciidoc
  docs/en/infraops/installation.asciidoc
  docs/en/infraops/logs-ui-intro.asciidoc
  docs/en/infraops/overview.asciidoc
  docs/en/infraops/screenshot-logs-ui.jpg
  docs/en/infraops/screenshot-metrics-infrastructure-monitoring.jpg
  docs/en/infraops/screenshot-systems-monitoring.jpg
Labels: Infrastructure monitoring, review

#487 [7.4] [DOCS] Spell check and minor tidying up of Infrastructure Monitoring Guide (#476)
  .gitignore
  docs/en/infraops/images/add-data.png
  docs/en/infraops/images/infra-sysmon.png
  docs/en/infraops/images/logs-console.png
  docs/en/infraops/images/monitoring-architecture.png
  docs/en/infraops/index.asciidoc
  docs/en/infraops/infra-ui-intro.asciidoc
  docs/en/infraops/infrastructure-metrics.asciidoc
  docs/en/infraops/installation.asciidoc
  docs/en/infraops/logs-ui-intro.asciidoc
  docs/en/infraops/overview.asciidoc
  docs/en/infraops/screenshot-logs-ui.jpg
  docs/en/infraops/screenshot-metrics-infrastructure-monitoring.jpg
  docs/en/infraops/screenshot-systems-monitoring.jpg
Labels: backport

#488 [7.3] [DOCS] Spell check and minor tidying up of Infrastructure Monitoring Guide (#476)
  .gitignore
  docs/en/infraops/images/add-data.png
  docs/en/infraops/images/infra-sysmon.png
  docs/en/infraops/images/logs-console.png
  docs/en/infraops/images/monitoring-architecture.png
  docs/en/infraops/index.asciidoc
  docs/en/infraops/infra-ui-intro.asciidoc
  docs/en/infraops/infrastructure-metrics.asciidoc
  docs/en/infraops/installation.asciidoc
  docs/en/infraops/logs-ui-intro.asciidoc
  docs/en/infraops/overview.asciidoc
  docs/en/infraops/screenshot-logs-ui.jpg
  docs/en/infraops/screenshot-metrics-infrastructure-monitoring.jpg
  docs/en/infraops/screenshot-systems-monitoring.jpg
Labels: backport

#489 [7.x] [DOCS] Spell check and minor tidying up of Infrastructure Monitoring Guide (#476)
  .gitignore
  docs/en/infraops/images/add-data.png
  docs/en/infraops/images/infra-sysmon.png
  docs/en/infraops/images/logs-console.png
  docs/en/infraops/images/monitoring-architecture.png
  docs/en/infraops/index.asciidoc
  docs/en/infraops/infra-ui-intro.asciidoc
  docs/en/infraops/infrastructure-metrics.asciidoc
  docs/en/infraops/installation.asciidoc
  docs/en/infraops/logs-ui-intro.asciidoc
  docs/en/infraops/overview.asciidoc
  docs/en/infraops/screenshot-logs-ui.jpg
  docs/en/infraops/screenshot-metrics-infrastructure-monitoring.jpg
  docs/en/infraops/screenshot-systems-monitoring.jpg
Labels: backport

#490 [Backport] [Docs] 7.x Updated screenshots for Hosts and Network pages
  docs/en/siem/images/hosts-ui.png
  docs/en/siem/images/network-ui.png
Labels: backport

#491 [Backport] [Docs] 7.4 Updated screenshots for Hosts and Network pages
  docs/en/siem/images/hosts-ui.png
  docs/en/siem/images/network-ui.png
Labels: backport

#493 Updates location of version attributes for Stack Overview
  docs/en/stack/index.asciidoc
Labels: v8.0.0

#496 Updates location of version attributes for Getting started with Stack
  docs/en/getting-started/index.asciidoc
Labels: v8.0.0

#497 Updates location of version attribute for multiple books
  docs/en/gke-on-prem/index.asciidoc
  docs/en/glossary/index.asciidoc
  docs/en/infraops/index.asciidoc
  docs/en/siem/index.asciidoc
Labels: v8.0.0

#498 [DOCS] Deletes Cannot update data frame transform limitation
  docs/en/stack/data-frames/limitations.asciidoc
Labels: :ml, :ml/Data Frame, v7.4.1, v7.5.0, v8.0.0

#504 [DOCS] Update source for transforms in Stack Overview
  docs/en/stack/data-frames/api-quickref.asciidoc
  docs/en/stack/data-frames/checkpoints.asciidoc
  docs/en/stack/data-frames/dataframe-examples.asciidoc
  docs/en/stack/data-frames/ecommerce-example.asciidoc
  docs/en/stack/data-frames/images/dataframe-transforms.jpg
  docs/en/stack/data-frames/images/ecommerce-batch.jpg
  docs/en/stack/data-frames/images/ecommerce-continuous.jpg
  docs/en/stack/data-frames/images/ecommerce-pivot1.jpg
  docs/en/stack/data-frames/images/ecommerce-pivot2.jpg
  docs/en/stack/data-frames/images/ecommerce-results.jpg
  docs/en/stack/data-frames/images/ml-dataframepivot.jpg
  docs/en/stack/data-frames/index.asciidoc
  docs/en/stack/data-frames/limitations.asciidoc
  docs/en/stack/data-frames/overview.asciidoc
  docs/en/stack/data-frames/troubleshooting.asciidoc
  docs/en/stack/index.asciidoc
Labels: :ml/Data Frame, v7.2.2, v7.3.2, v7.4.1, v7.5.0, v8.0.0

#506 [7.4][DOCS] Update source for transforms in Stack Overview (#504)
  docs/en/stack/data-frames/api-quickref.asciidoc
  docs/en/stack/data-frames/checkpoints.asciidoc
  docs/en/stack/data-frames/dataframe-examples.asciidoc
  docs/en/stack/data-frames/ecommerce-example.asciidoc
  docs/en/stack/data-frames/images/dataframe-transforms.jpg
  docs/en/stack/data-frames/images/ecommerce-batch.jpg
  docs/en/stack/data-frames/images/ecommerce-continuous.jpg
  docs/en/stack/data-frames/images/ecommerce-pivot1.jpg
  docs/en/stack/data-frames/images/ecommerce-pivot2.jpg
  docs/en/stack/data-frames/images/ecommerce-results.jpg
  docs/en/stack/data-frames/images/ml-dataframepivot.jpg
  docs/en/stack/data-frames/index.asciidoc
  docs/en/stack/data-frames/limitations.asciidoc
  docs/en/stack/data-frames/overview.asciidoc
  docs/en/stack/data-frames/troubleshooting.asciidoc
  docs/en/stack/index.asciidoc
Labels: backport

#507 [7.3][DOCS] Update source for transforms in Stack Overview (#504)
  docs/en/stack/data-frames/api-quickref.asciidoc
  docs/en/stack/data-frames/checkpoints.asciidoc
  docs/en/stack/data-frames/dataframe-examples.asciidoc
  docs/en/stack/data-frames/ecommerce-example.asciidoc
  docs/en/stack/data-frames/images/dataframe-transforms.jpg
  docs/en/stack/data-frames/images/ecommerce-batch.jpg
  docs/en/stack/data-frames/images/ecommerce-continuous.jpg
  docs/en/stack/data-frames/images/ecommerce-pivot1.jpg
  docs/en/stack/data-frames/images/ecommerce-pivot2.jpg
  docs/en/stack/data-frames/images/ecommerce-results.jpg
  docs/en/stack/data-frames/images/ml-dataframepivot.jpg
  docs/en/stack/data-frames/index.asciidoc
  docs/en/stack/data-frames/limitations.asciidoc
  docs/en/stack/data-frames/overview.asciidoc
  docs/en/stack/data-frames/troubleshooting.asciidoc
  docs/en/stack/index.asciidoc
Labels: backport

#508 [7.2][DOCS] Update source for transforms in Stack Overview (#504)
  docs/en/stack/data-frames/api-quickref.asciidoc
  docs/en/stack/data-frames/dataframe-examples.asciidoc
  docs/en/stack/data-frames/ecommerce-example.asciidoc
  docs/en/stack/data-frames/images/ml-dataframepivot.jpg
  docs/en/stack/data-frames/index.asciidoc
  docs/en/stack/data-frames/limitations.asciidoc
  docs/en/stack/data-frames/overview.asciidoc
  docs/en/stack/data-frames/troubleshooting.asciidoc
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
Labels: backport

#510 Updates path in Stack Overview to Kibana monitoring
  docs/en/stack/monitoring/esms.asciidoc
Labels: :Monitoring, v8.0.0

#512 Use shared versions file from elastic/docs for install-upgrade guide
  docs/en/install-upgrade/index.asciidoc
Labels: v6.3.0, v6.4.0, v6.5.0, v6.6.0, v6.7.0, v6.8.0, v7.0.0, v7.1.0, v7.2.0, v7.3.0, v7.4.0, v7.5.0, v8.0.0

#515 Wording correction
  docs/en/stack/security/how-security-works.asciidoc
Labels: :Security, v7.3.2, v7.4.1, v7.5.0, v8.0.0

#514 [DOCS] Adds Kibana job creation pages
  docs/en/stack/ml/anomaly-detection/create-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/images/ml-create-job.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-data-recognizer-auditbeat.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-data-recognizer-filebeat.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-data-recognizer-metricbeat.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-data-recognizer-sample.jpg
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/job-tips.asciidoc
Labels: :ml, v7.4.1, v7.5.0, v8.0.0

#464 [DOCS] Remove CCR docs from Stack Overview
  docs/en/stack/index.asciidoc
  docs/en/stack/redirects.asciidoc
Labels: v7.3.0, v7.4.0, v7.5.0, v8.0.0

#517 [DOCS] Updates data frame transform terminology
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/security/authorization/built-in-roles.asciidoc
  docs/en/stack/security/authorization/privileges.asciidoc
Labels: :ml/Data Frame, v7.2.2, v7.3.2, v7.4.1, v7.5.0, v8.0.0

#501 [DOCS] Adds data frame analytics field type and document limitation
  docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
Labels: :ml, :ml/Data Frame, v7.4.1, v7.5.0, v8.0.0

#479 [DOCS] Adds conceptual documentation of regression and the related evaluation type
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/evaluatedf-api.asciidoc
  docs/en/stack/ml/df-analytics/index.asciidoc
Labels: :ml, :ml/Data Frame, v7.4.0, v7.5.0, v8.0.0

#520 [DOCS] Fixes wrong section level in data frame analytics limitations
  docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
Labels: v7.4.1, v7.5.0, v8.0.0

#523 Update Kibana release highlights in Install Upgrade Guide
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.4.1, v7.5.0, v8.0.0

#525 [DOCS] Fixes link to transform APIs
  docs/en/stack/ml/df-analytics/index.asciidoc
Labels: :ml/Data Frame, v7.2.2, v7.3.2, v7.4.1, v7.5.0, v8.0.0

#526 [7.x][DOCS] Fixes link to transform APIs (#525)
  docs/en/stack/ml/df-analytics/index.asciidoc
Labels: backport

#527 [7.4][DOCS] Fixes link to transform APIs (#525)
  docs/en/stack/ml/df-analytics/index.asciidoc
Labels: backport

#528 [7.3][DOCS] Fixes link to transform APIs (#525)
  docs/en/stack/ml/df-analytics/index.asciidoc
Labels: backport

#516 [DOCS] Reuse glossary items from ES glossary
  docs/en/glossary/glossary.asciidoc
Labels: enhancement, v8.0.0

#524 [DOCS] Adds outlier detection example
  docs/en/stack/get-started-trial.asciidoc
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/examples.asciidoc
  docs/en/stack/ml/df-analytics/images/ecommerce-outlier-job.jpg
  docs/en/stack/ml/df-analytics/images/ecommerce-transform-preview.jpg
  docs/en/stack/ml/df-analytics/images/outliers.jpg
  docs/en/stack/ml/df-analytics/index.asciidoc
Labels: :ml/Data Frame, v7.4.1, v7.5.0, v8.0.0

#513 [Docs] SIEM 7.4 network map
  docs/en/siem/images/field-ui.png
  docs/en/siem/images/network-ui.png
  docs/en/siem/siem-ui.asciidoc
Labels: Team:SIEM

#519 [DOCS] Removes transform content from Stack Overview
  docs/en/stack/index.asciidoc
  docs/en/stack/redirects.asciidoc
Labels: :ml/Data Frame, backport, v7.2.2, v7.3.2, v7.4.1, v7.5.0, v8.0.0

#521 [DOCS][7.3] Adds data frame analytics field type and document limitation
  docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
Labels: :ml, :ml/Data Frame, v7.3.2

#534 [DOCS] Changes wording to move away from data frame terminology in Stack Docs
  docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
  docs/en/stack/ml/df-analytics/evaluatedf-api.asciidoc
Labels: :ml, :ml/Data Frame, v7.2.2, v7.3.2, v7.4.1, v7.5.0, v8.0.0

#509 [Docs] 7.4 Updated ML Job Descriptions
  docs/en/siem/images/ml-ui.png
  docs/en/siem/machine-learning.asciidoc
Labels: Team:SIEM

#544 Removes deleted pages for transforms
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/redirects.asciidoc
Labels: :ml/Data Frame, v8.0.0

#552 Fixes transform links
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/index.asciidoc
Labels: :ml/Data Frame, v7.2.2, v7.3.2, v7.4.1, v7.5.0

#554 Removes redundant monitoring pages
  docs/en/stack/monitoring/how-monitoring-works.asciidoc
  docs/en/stack/monitoring/index.asciidoc
  docs/en/stack/monitoring/intro.asciidoc
  docs/en/stack/monitoring/production.asciidoc
  docs/en/stack/redirects.asciidoc
Labels: :Monitoring, v7.3.2, v7.4.1, v7.5.0, v8.0.0

#546 Removes Watcher from Stack Overview
  docs/en/stack/index.asciidoc
  docs/en/stack/introduction.asciidoc
  docs/en/stack/redirects.asciidoc
Labels: v6.8.4, v7.0.2, v7.1.2, v7.2.2, v7.3.2, v7.4.1, v7.5.0, v8.0.0

#557 [7.x] Removes Watcher from Stack Overview (#546)
  docs/en/stack/index.asciidoc
  docs/en/stack/introduction.asciidoc
  docs/en/stack/redirects.asciidoc
Labels: backport

#558 [7.4] Removes Watcher from Stack Overview (#546)
  docs/en/stack/index.asciidoc
  docs/en/stack/introduction.asciidoc
  docs/en/stack/redirects.asciidoc
Labels: backport

#559 [7.3] Removes Watcher from Stack Overview (#546)
  docs/en/stack/index.asciidoc
  docs/en/stack/introduction.asciidoc
  docs/en/stack/redirects.asciidoc
Labels: backport
