Repository elastic/stack-docs, pull requests merged in 2019-10, with the labels that each got.

#562 [7.2]Removes Watcher from Stack Overview (#546)
  docs/en/stack/images/watcher-ui-edit-watch.png
  docs/en/stack/index.asciidoc
  docs/en/stack/introduction.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/troubleshooting.asciidoc
  docs/en/stack/watcher/limitations.asciidoc
  docs/en/stack/watcher/troubleshooting.asciidoc
Labels: backport

#563 [7.1]Removes Watcher from Stack Overview (#546)
  docs/en/stack/images/watcher-ui-edit-watch.png
  docs/en/stack/index.asciidoc
  docs/en/stack/introduction.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/troubleshooting.asciidoc
  docs/en/stack/watcher/limitations.asciidoc
  docs/en/stack/watcher/troubleshooting.asciidoc
Labels: backport

#564 [7.0] Removes Watcher from Stack Overview (#546)
  docs/en/stack/images/watcher-ui-edit-watch.png
  docs/en/stack/index.asciidoc
  docs/en/stack/introduction.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/troubleshooting.asciidoc
  docs/en/stack/watcher/limitations.asciidoc
  docs/en/stack/watcher/troubleshooting.asciidoc
Labels: backport

#565 [6.8] Removes Watcher from Stack Overview (#546)
  docs/en/stack/images/watcher-ui-edit-watch.png
  docs/en/stack/images/watcher-ui-edit-watch0.png
  docs/en/stack/index.asciidoc
  docs/en/stack/introduction.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/troubleshooting.asciidoc
  docs/en/stack/watcher/limitations.asciidoc
  docs/en/stack/watcher/troubleshooting.asciidoc
Labels: backport

#567 [6.7] Removes Watcher from Stack Overview
  docs/en/stack/images/watcher-ui-edit-watch.png
  docs/en/stack/images/watcher-ui-edit-watch0.png
  docs/en/stack/index.asciidoc
  docs/en/stack/introduction.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/troubleshooting.asciidoc
  docs/en/stack/watcher/limitations.asciidoc
  docs/en/stack/watcher/troubleshooting.asciidoc
Labels: backport

#568 [6.6]Removes Watcher from Stack Overview (#546)
  docs/en/stack/images/watcher-ui-edit-watch.png
  docs/en/stack/images/watcher-ui-edit-watch0.png
  docs/en/stack/index.asciidoc
  docs/en/stack/introduction.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/troubleshooting.asciidoc
  docs/en/stack/watcher/limitations.asciidoc
  docs/en/stack/watcher/troubleshooting.asciidoc
Labels: backport

#570 [DOCS] Remove comments around ES 7.4 release highlights include
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.4.0

#571 [6.5]Removes Watcher from Stack Overview
  docs/en/stack/images/watcher-ui-edit-watch.png
  docs/en/stack/images/watcher-ui-edit-watch0.png
  docs/en/stack/index.asciidoc
  docs/en/stack/introduction.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/troubleshooting.asciidoc
  docs/en/stack/watcher/limitations.asciidoc
  docs/en/stack/watcher/troubleshooting.asciidoc
Labels: backport

#572 [6.4] Removes Watcher from Stack Overview
  docs/en/stack/images/watcher-ui-edit-watch.png
  docs/en/stack/index.asciidoc
  docs/en/stack/introduction.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/troubleshooting.asciidoc
  docs/en/stack/watcher/limitations.asciidoc
  docs/en/stack/watcher/troubleshooting.asciidoc
Labels: backport

#573 [6.3] Removes Watcher from Stack Overview
  docs/en/stack/images/watcher-ui-edit-watch.png
  docs/en/stack/index.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/watcher/limitations.asciidoc
  docs/en/stack/watcher/troubleshooting.asciidoc
  docs/en/stack/xpack-introduction.asciidoc
  docs/en/stack/xpack-limitations.asciidoc
  docs/en/stack/xpack-troubleshooting.asciidoc
Labels: backport

#574 Stages removal of security content
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/index.asciidoc
Labels: :Security, needs_backport, v7.3.2, v7.4.1, v7.5.0, v8.0.0

#575 Removes security from Stack Overview
  docs/en/stack/index.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/authentication/active-directory-realm.asciidoc
  docs/en/stack/security/authentication/built-in-users.asciidoc
  docs/en/stack/security/authentication/file-realm.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authentication/internal-users.asciidoc
  docs/en/stack/security/authentication/kerberos-realm.asciidoc
  docs/en/stack/security/authentication/ldap-realm.asciidoc
  docs/en/stack/security/authentication/native-realm.asciidoc
  docs/en/stack/security/authentication/overview.asciidoc
  docs/en/stack/security/authentication/pki-realm.asciidoc
  docs/en/stack/security/authentication/realm-chains.asciidoc
  docs/en/stack/security/authentication/realms.asciidoc
  docs/en/stack/security/authentication/saml-realm.asciidoc
  docs/en/stack/security/authentication/token-authentication-services.asciidoc
  docs/en/stack/security/authorization/built-in-roles.asciidoc
  docs/en/stack/security/authorization/configuring-authorization-delegation.asciidoc
  docs/en/stack/security/authorization/document-level-security.asciidoc
  docs/en/stack/security/authorization/field-level-security.asciidoc
  docs/en/stack/security/authorization/images/authorization.png
  docs/en/stack/security/authorization/index.asciidoc
  docs/en/stack/security/authorization/overview.asciidoc
  docs/en/stack/security/authorization/privileges.asciidoc
  docs/en/stack/security/get-started-builtin-users.asciidoc
  docs/en/stack/security/get-started-enable-security.asciidoc
  docs/en/stack/security/get-started-kibana-users.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
  docs/en/stack/security/how-security-works.asciidoc
  docs/en/stack/security/images/assign-role.jpg
  docs/en/stack/security/images/create-logstash-user.jpg
  docs/en/stack/security/images/create-reader-role.jpg
  docs/en/stack/security/images/create-user.jpg
  docs/en/stack/security/images/create-writer-role.jpg
  docs/en/stack/security/images/management-builtin-users.jpg
  docs/en/stack/security/images/management-roles.jpg
  docs/en/stack/security/images/management-users.jpg
  docs/en/stack/security/index.asciidoc
  docs/en/stack/security/limitations.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-addnodes.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-certificates.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-internode.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-intro.asciidoc
  docs/en/stack/security/troubleshooting.asciidoc
Labels: needs_backport, v7.3.2, v7.4.1, v7.5.0, v8.0.0

#576 Security anchor fixes
  docs/en/stack/redirects.asciidoc
Labels: needs_backport, v7.3.2, v7.4.1, v7.5.0, v8.0.0

#577 [7.x] Stages removal of security content (#574)
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
  docs/en/stack/security/index.asciidoc
Labels: backport

#578 [7.x] Removes security from Stack Overview
  docs/en/stack/index.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/authentication/active-directory-realm.asciidoc
  docs/en/stack/security/authentication/built-in-users.asciidoc
  docs/en/stack/security/authentication/file-realm.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authentication/internal-users.asciidoc
  docs/en/stack/security/authentication/kerberos-realm.asciidoc
  docs/en/stack/security/authentication/ldap-realm.asciidoc
  docs/en/stack/security/authentication/native-realm.asciidoc
  docs/en/stack/security/authentication/overview.asciidoc
  docs/en/stack/security/authentication/pki-realm.asciidoc
  docs/en/stack/security/authentication/realm-chains.asciidoc
  docs/en/stack/security/authentication/realms.asciidoc
  docs/en/stack/security/authentication/saml-realm.asciidoc
  docs/en/stack/security/authorization/built-in-roles.asciidoc
  docs/en/stack/security/authorization/configuring-authorization-delegation.asciidoc
  docs/en/stack/security/authorization/document-level-security.asciidoc
  docs/en/stack/security/authorization/field-level-security.asciidoc
  docs/en/stack/security/authorization/images/authorization.png
  docs/en/stack/security/authorization/index.asciidoc
  docs/en/stack/security/authorization/overview.asciidoc
  docs/en/stack/security/authorization/privileges.asciidoc
  docs/en/stack/security/get-started-builtin-users.asciidoc
  docs/en/stack/security/get-started-enable-security.asciidoc
  docs/en/stack/security/get-started-kibana-users.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
  docs/en/stack/security/how-security-works.asciidoc
  docs/en/stack/security/images/assign-role.jpg
  docs/en/stack/security/images/create-logstash-user.jpg
  docs/en/stack/security/images/create-reader-role.jpg
  docs/en/stack/security/images/create-user.jpg
  docs/en/stack/security/images/create-writer-role.jpg
  docs/en/stack/security/images/management-builtin-users.jpg
  docs/en/stack/security/images/management-roles.jpg
  docs/en/stack/security/images/management-users.jpg
  docs/en/stack/security/index.asciidoc
  docs/en/stack/security/limitations.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-addnodes.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-certificates.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-internode.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-intro.asciidoc
  docs/en/stack/security/troubleshooting.asciidoc
Labels: backport

#579 [7.4] Stages removal of security content
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
  docs/en/stack/security/index.asciidoc
Labels: backport

#580 [7.3] Stages removal of security content
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
  docs/en/stack/security/index.asciidoc
Labels: backport

#582 [7.4]Removes security from Stack Overview
  docs/en/stack/index.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/authentication/active-directory-realm.asciidoc
  docs/en/stack/security/authentication/built-in-users.asciidoc
  docs/en/stack/security/authentication/file-realm.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authentication/internal-users.asciidoc
  docs/en/stack/security/authentication/kerberos-realm.asciidoc
  docs/en/stack/security/authentication/ldap-realm.asciidoc
  docs/en/stack/security/authentication/native-realm.asciidoc
  docs/en/stack/security/authentication/overview.asciidoc
  docs/en/stack/security/authentication/pki-realm.asciidoc
  docs/en/stack/security/authentication/realm-chains.asciidoc
  docs/en/stack/security/authentication/realms.asciidoc
  docs/en/stack/security/authentication/saml-realm.asciidoc
  docs/en/stack/security/authorization/built-in-roles.asciidoc
  docs/en/stack/security/authorization/configuring-authorization-delegation.asciidoc
  docs/en/stack/security/authorization/document-level-security.asciidoc
  docs/en/stack/security/authorization/field-level-security.asciidoc
  docs/en/stack/security/authorization/images/authorization.png
  docs/en/stack/security/authorization/index.asciidoc
  docs/en/stack/security/authorization/overview.asciidoc
  docs/en/stack/security/authorization/privileges.asciidoc
  docs/en/stack/security/get-started-builtin-users.asciidoc
  docs/en/stack/security/get-started-enable-security.asciidoc
  docs/en/stack/security/get-started-kibana-users.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
  docs/en/stack/security/how-security-works.asciidoc
  docs/en/stack/security/images/assign-role.jpg
  docs/en/stack/security/images/create-logstash-user.jpg
  docs/en/stack/security/images/create-reader-role.jpg
  docs/en/stack/security/images/create-user.jpg
  docs/en/stack/security/images/create-writer-role.jpg
  docs/en/stack/security/images/management-builtin-users.jpg
  docs/en/stack/security/images/management-roles.jpg
  docs/en/stack/security/images/management-users.jpg
  docs/en/stack/security/index.asciidoc
  docs/en/stack/security/limitations.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-addnodes.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-certificates.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-internode.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-intro.asciidoc
  docs/en/stack/security/troubleshooting.asciidoc
Labels: backport

#583 [7.3] Removes security from Stack Overview
  docs/en/stack/index.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/authentication/active-directory-realm.asciidoc
  docs/en/stack/security/authentication/built-in-users.asciidoc
  docs/en/stack/security/authentication/file-realm.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authentication/internal-users.asciidoc
  docs/en/stack/security/authentication/kerberos-realm.asciidoc
  docs/en/stack/security/authentication/ldap-realm.asciidoc
  docs/en/stack/security/authentication/native-realm.asciidoc
  docs/en/stack/security/authentication/overview.asciidoc
  docs/en/stack/security/authentication/pki-realm.asciidoc
  docs/en/stack/security/authentication/realm-chains.asciidoc
  docs/en/stack/security/authentication/realms.asciidoc
  docs/en/stack/security/authentication/saml-realm.asciidoc
  docs/en/stack/security/authorization/built-in-roles.asciidoc
  docs/en/stack/security/authorization/document-level-security.asciidoc
  docs/en/stack/security/authorization/field-level-security.asciidoc
  docs/en/stack/security/authorization/images/authorization.png
  docs/en/stack/security/authorization/index.asciidoc
  docs/en/stack/security/authorization/overview.asciidoc
  docs/en/stack/security/authorization/privileges.asciidoc
  docs/en/stack/security/get-started-builtin-users.asciidoc
  docs/en/stack/security/get-started-enable-security.asciidoc
  docs/en/stack/security/get-started-kibana-users.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
  docs/en/stack/security/how-security-works.asciidoc
  docs/en/stack/security/images/assign-role.jpg
  docs/en/stack/security/images/create-logstash-user.jpg
  docs/en/stack/security/images/create-reader-role.jpg
  docs/en/stack/security/images/create-user.jpg
  docs/en/stack/security/images/create-writer-role.jpg
  docs/en/stack/security/images/management-builtin-users.jpg
  docs/en/stack/security/images/management-roles.jpg
  docs/en/stack/security/images/management-users.jpg
  docs/en/stack/security/index.asciidoc
  docs/en/stack/security/limitations.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-addnodes.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-certificates.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-internode.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-intro.asciidoc
  docs/en/stack/security/troubleshooting.asciidoc
Labels: backport

#548 [DOCS] Revamps the Anomaly Detection section
  docs/en/stack/ml/anomaly-detection/create-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/examples.asciidoc
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/job-tips.asciidoc
  docs/en/stack/ml/anomaly-detection/jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-concepts.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
  docs/en/stack/ml/anomaly-detection/overview.asciidoc
  docs/en/stack/ml/anomaly-detection/stopping-ml.asciidoc
  docs/en/stack/redirects.asciidoc
Labels: :ml, v7.2.2, v7.3.2, v7.4.1, v7.5.0, v8.0.0

#584 [7.2]Stages removal of security content
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
  docs/en/stack/security/index.asciidoc
Labels: backport

#585 [7.1] Stages removal of security content
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
  docs/en/stack/security/index.asciidoc
Labels: backport

#592 [7.x] [DOCS] Revamps Anomaly Detection section
  docs/en/stack/ml/anomaly-detection/create-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/examples.asciidoc
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/job-tips.asciidoc
  docs/en/stack/ml/anomaly-detection/jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-concepts.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
  docs/en/stack/ml/anomaly-detection/overview.asciidoc
  docs/en/stack/ml/anomaly-detection/stopping-ml.asciidoc
  docs/en/stack/redirects.asciidoc
Labels: :ml, backport, v7.3.2, v7.4.1, v7.5.0

#596 [7.2] Removes redundant monitoring pages
  docs/en/stack/monitoring/how-monitoring-works.asciidoc
  docs/en/stack/monitoring/index.asciidoc
  docs/en/stack/monitoring/intro.asciidoc
  docs/en/stack/monitoring/production.asciidoc
  docs/en/stack/monitoring/troubleshooting.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#597 [7.1] Removes redundant monitoring pages
  docs/en/stack/monitoring/how-monitoring-works.asciidoc
  docs/en/stack/monitoring/index.asciidoc
  docs/en/stack/monitoring/intro.asciidoc
  docs/en/stack/monitoring/production.asciidoc
  docs/en/stack/monitoring/troubleshooting.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#598 [7.0] Removes redundant monitoring pages
  docs/en/stack/monitoring/how-monitoring-works.asciidoc
  docs/en/stack/monitoring/index.asciidoc
  docs/en/stack/monitoring/intro.asciidoc
  docs/en/stack/monitoring/production.asciidoc
  docs/en/stack/monitoring/troubleshooting.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#599 [6.8] Removes redundant monitoring pages
  docs/en/stack/monitoring/how-monitoring-works.asciidoc
  docs/en/stack/monitoring/index.asciidoc
  docs/en/stack/monitoring/intro.asciidoc
  docs/en/stack/monitoring/production.asciidoc
  docs/en/stack/monitoring/troubleshooting.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#600 [6.7] Removes redundant monitoring pages
  docs/en/stack/index.asciidoc
  docs/en/stack/introduction.asciidoc
  docs/en/stack/monitoring/how-monitoring-works.asciidoc
  docs/en/stack/monitoring/images/architecture10.png
  docs/en/stack/monitoring/images/architecture20.png
  docs/en/stack/monitoring/images/architecture30.png
  docs/en/stack/monitoring/index.asciidoc
  docs/en/stack/monitoring/intro.asciidoc
  docs/en/stack/monitoring/production.asciidoc
  docs/en/stack/monitoring/troubleshooting.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#601 [6.6] Removes redundant monitoring pages
  docs/en/stack/index.asciidoc
  docs/en/stack/introduction.asciidoc
  docs/en/stack/monitoring/how-monitoring-works.asciidoc
  docs/en/stack/monitoring/images/architecture10.png
  docs/en/stack/monitoring/images/architecture20.png
  docs/en/stack/monitoring/images/architecture30.png
  docs/en/stack/monitoring/index.asciidoc
  docs/en/stack/monitoring/intro.asciidoc
  docs/en/stack/monitoring/production.asciidoc
  docs/en/stack/monitoring/troubleshooting.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#602 [6.5] Removes redundant monitoring pages
  docs/en/stack/index.asciidoc
  docs/en/stack/monitoring/how-monitoring-works.asciidoc
  docs/en/stack/monitoring/images/architecture10.png
  docs/en/stack/monitoring/images/architecture20.png
  docs/en/stack/monitoring/images/architecture30.png
  docs/en/stack/monitoring/index.asciidoc
  docs/en/stack/monitoring/intro.asciidoc
  docs/en/stack/monitoring/production.asciidoc
  docs/en/stack/monitoring/troubleshooting.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#603 [6.4] Removes redundant monitoring pages
  docs/en/stack/index.asciidoc
  docs/en/stack/introduction.asciidoc
  docs/en/stack/monitoring/how-monitoring-works.asciidoc
  docs/en/stack/monitoring/images/architecture1.jpg
  docs/en/stack/monitoring/images/architecture2.jpg
  docs/en/stack/monitoring/images/architecture3.jpg
  docs/en/stack/monitoring/images/architecture4.png
  docs/en/stack/monitoring/index.asciidoc
  docs/en/stack/monitoring/intro.asciidoc
  docs/en/stack/monitoring/production.asciidoc
  docs/en/stack/monitoring/troubleshooting.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#604 [6.3] Removes redundant monitoring pages
  docs/en/stack/index.asciidoc
  docs/en/stack/monitoring/how-monitoring-works.asciidoc
  docs/en/stack/monitoring/images/architecture1.jpg
  docs/en/stack/monitoring/images/architecture2.jpg
  docs/en/stack/monitoring/images/architecture3.jpg
  docs/en/stack/monitoring/index.asciidoc
  docs/en/stack/monitoring/intro.asciidoc
  docs/en/stack/monitoring/production.asciidoc
  docs/en/stack/monitoring/troubleshooting.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/xpack-introduction.asciidoc
  docs/en/stack/xpack-troubleshooting.asciidoc
Labels: backport

#606 [7.x] [DOCS] Fixes TOC in the anomaly detection index
  docs/en/stack/ml/anomaly-detection/index.asciidoc
Labels: v7.4.1, v7.5.0

#609 [7.2] Removes security from Stack Overview
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/authentication/active-directory-realm.asciidoc
  docs/en/stack/security/authentication/built-in-users.asciidoc
  docs/en/stack/security/authentication/file-realm.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authentication/internal-users.asciidoc
  docs/en/stack/security/authentication/kerberos-realm.asciidoc
  docs/en/stack/security/authentication/ldap-realm.asciidoc
  docs/en/stack/security/authentication/native-realm.asciidoc
  docs/en/stack/security/authentication/overview.asciidoc
  docs/en/stack/security/authentication/pki-realm.asciidoc
  docs/en/stack/security/authentication/realm-chains.asciidoc
  docs/en/stack/security/authentication/realms.asciidoc
  docs/en/stack/security/authentication/saml-realm.asciidoc
  docs/en/stack/security/authorization/built-in-roles.asciidoc
  docs/en/stack/security/authorization/document-level-security.asciidoc
  docs/en/stack/security/authorization/field-level-security.asciidoc
  docs/en/stack/security/authorization/images/authorization.png
  docs/en/stack/security/authorization/index.asciidoc
  docs/en/stack/security/authorization/overview.asciidoc
  docs/en/stack/security/authorization/privileges.asciidoc
  docs/en/stack/security/get-started-builtin-users.asciidoc
  docs/en/stack/security/get-started-enable-security.asciidoc
  docs/en/stack/security/get-started-kibana-users.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
  docs/en/stack/security/how-security-works.asciidoc
  docs/en/stack/security/images/assign-role.jpg
  docs/en/stack/security/images/create-logstash-user.jpg
  docs/en/stack/security/images/create-reader-role.jpg
  docs/en/stack/security/images/create-user.jpg
  docs/en/stack/security/images/create-writer-role.jpg
  docs/en/stack/security/images/management-builtin-users.jpg
  docs/en/stack/security/images/management-roles.jpg
  docs/en/stack/security/images/management-users.jpg
  docs/en/stack/security/index.asciidoc
  docs/en/stack/security/limitations.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-addnodes.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-certificates.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-internode.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-intro.asciidoc
  docs/en/stack/security/troubleshooting.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#611 [7.0] Stages removal of security content (#574) (#580)
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
  docs/en/stack/security/index.asciidoc
Labels: backport

#610 [7.1] Removes security from Stack Overview
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/authentication/active-directory-realm.asciidoc
  docs/en/stack/security/authentication/built-in-users.asciidoc
  docs/en/stack/security/authentication/file-realm.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authentication/internal-users.asciidoc
  docs/en/stack/security/authentication/kerberos-realm.asciidoc
  docs/en/stack/security/authentication/ldap-realm.asciidoc
  docs/en/stack/security/authentication/native-realm.asciidoc
  docs/en/stack/security/authentication/overview.asciidoc
  docs/en/stack/security/authentication/pki-realm.asciidoc
  docs/en/stack/security/authentication/realm-chains.asciidoc
  docs/en/stack/security/authentication/realms.asciidoc
  docs/en/stack/security/authentication/saml-realm.asciidoc
  docs/en/stack/security/authentication/token-authentication-services.asciidoc
  docs/en/stack/security/authorization/built-in-roles.asciidoc
  docs/en/stack/security/authorization/document-level-security.asciidoc
  docs/en/stack/security/authorization/field-level-security.asciidoc
  docs/en/stack/security/authorization/images/authorization.png
  docs/en/stack/security/authorization/index.asciidoc
  docs/en/stack/security/authorization/overview.asciidoc
  docs/en/stack/security/authorization/privileges.asciidoc
  docs/en/stack/security/get-started-builtin-users.asciidoc
  docs/en/stack/security/get-started-enable-security.asciidoc
  docs/en/stack/security/get-started-kibana-users.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
  docs/en/stack/security/how-security-works.asciidoc
  docs/en/stack/security/images/assign-role.jpg
  docs/en/stack/security/images/create-logstash-user.jpg
  docs/en/stack/security/images/create-reader-role.jpg
  docs/en/stack/security/images/create-user.jpg
  docs/en/stack/security/images/create-writer-role.jpg
  docs/en/stack/security/images/management-builtin-users.jpg
  docs/en/stack/security/images/management-roles.jpg
  docs/en/stack/security/images/management-users.jpg
  docs/en/stack/security/index.asciidoc
  docs/en/stack/security/limitations.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-addnodes.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-certificates.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-internode.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-intro.asciidoc
  docs/en/stack/security/troubleshooting.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#605 [6.8]Stages removal of security content (#574)
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
  docs/en/stack/security/index.asciidoc
Labels: backport

#615 [7.0] Removes security from Stack Overview
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/authentication/active-directory-realm.asciidoc
  docs/en/stack/security/authentication/built-in-users.asciidoc
  docs/en/stack/security/authentication/file-realm.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authentication/internal-users.asciidoc
  docs/en/stack/security/authentication/kerberos-realm.asciidoc
  docs/en/stack/security/authentication/ldap-realm.asciidoc
  docs/en/stack/security/authentication/native-realm.asciidoc
  docs/en/stack/security/authentication/overview.asciidoc
  docs/en/stack/security/authentication/pki-realm.asciidoc
  docs/en/stack/security/authentication/realm-chains.asciidoc
  docs/en/stack/security/authentication/realms.asciidoc
  docs/en/stack/security/authentication/saml-realm.asciidoc
  docs/en/stack/security/authentication/token-authentication-services.asciidoc
  docs/en/stack/security/authorization/built-in-roles.asciidoc
  docs/en/stack/security/authorization/document-level-security.asciidoc
  docs/en/stack/security/authorization/field-level-security.asciidoc
  docs/en/stack/security/authorization/images/authorization.png
  docs/en/stack/security/authorization/index.asciidoc
  docs/en/stack/security/authorization/overview.asciidoc
  docs/en/stack/security/authorization/privileges.asciidoc
  docs/en/stack/security/get-started-builtin-users.asciidoc
  docs/en/stack/security/get-started-enable-security.asciidoc
  docs/en/stack/security/get-started-kibana-users.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
  docs/en/stack/security/how-security-works.asciidoc
  docs/en/stack/security/images/assign-role.jpg
  docs/en/stack/security/images/create-logstash-user.jpg
  docs/en/stack/security/images/create-reader-role.jpg
  docs/en/stack/security/images/create-user.jpg
  docs/en/stack/security/images/create-writer-role.jpg
  docs/en/stack/security/images/management-builtin-users.jpg
  docs/en/stack/security/images/management-roles.jpg
  docs/en/stack/security/images/management-users.jpg
  docs/en/stack/security/index.asciidoc
  docs/en/stack/security/limitations.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-addnodes.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-certificates.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-internode.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-intro.asciidoc
  docs/en/stack/security/troubleshooting.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#617 [6.8] Removes security from Stack Overview
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/authentication/active-directory-realm.asciidoc
  docs/en/stack/security/authentication/built-in-users.asciidoc
  docs/en/stack/security/authentication/file-realm.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authentication/internal-users.asciidoc
  docs/en/stack/security/authentication/kerberos-realm.asciidoc
  docs/en/stack/security/authentication/ldap-realm.asciidoc
  docs/en/stack/security/authentication/native-realm.asciidoc
  docs/en/stack/security/authentication/overview.asciidoc
  docs/en/stack/security/authentication/pki-realm.asciidoc
  docs/en/stack/security/authentication/realm-chains.asciidoc
  docs/en/stack/security/authentication/realms.asciidoc
  docs/en/stack/security/authentication/saml-realm.asciidoc
  docs/en/stack/security/authentication/token-authentication-services.asciidoc
  docs/en/stack/security/authorization/built-in-roles.asciidoc
  docs/en/stack/security/authorization/document-level-security.asciidoc
  docs/en/stack/security/authorization/field-level-security.asciidoc
  docs/en/stack/security/authorization/images/authorization.png
  docs/en/stack/security/authorization/index.asciidoc
  docs/en/stack/security/authorization/overview.asciidoc
  docs/en/stack/security/authorization/privileges.asciidoc
  docs/en/stack/security/get-started-builtin-users.asciidoc
  docs/en/stack/security/get-started-enable-security.asciidoc
  docs/en/stack/security/get-started-kibana-users.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
  docs/en/stack/security/how-security-works.asciidoc
  docs/en/stack/security/images/assign-role.jpg
  docs/en/stack/security/images/create-logstash-user.jpg
  docs/en/stack/security/images/create-reader-role.jpg
  docs/en/stack/security/images/create-user.jpg
  docs/en/stack/security/images/create-writer-role.jpg
  docs/en/stack/security/images/management-builtin-users.jpg
  docs/en/stack/security/images/management-roles.jpg
  docs/en/stack/security/images/management-users.jpg
  docs/en/stack/security/index.asciidoc
  docs/en/stack/security/limitations.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-addnodes.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-certificates.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-internode.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-intro.asciidoc
  docs/en/stack/security/troubleshooting.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#618 [DOCS] Fix broken link in redirects
  docs/en/stack/redirects.asciidoc
Labels: bug

#614 [6.7] Stages removal of security content
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/authentication/active-directory-realm.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authentication/ldap-realm.asciidoc
  docs/en/stack/security/authorization/index.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
  docs/en/stack/security/index.asciidoc
Labels: backport

#623 [6.7] Removes security from Stack Overview
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/authentication/active-directory-realm.asciidoc
  docs/en/stack/security/authentication/built-in-users.asciidoc
  docs/en/stack/security/authentication/file-realm.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authentication/internal-users.asciidoc
  docs/en/stack/security/authentication/kerberos-realm.asciidoc
  docs/en/stack/security/authentication/ldap-realm.asciidoc
  docs/en/stack/security/authentication/native-realm.asciidoc
  docs/en/stack/security/authentication/overview.asciidoc
  docs/en/stack/security/authentication/pki-realm.asciidoc
  docs/en/stack/security/authentication/realm-chains.asciidoc
  docs/en/stack/security/authentication/realms.asciidoc
  docs/en/stack/security/authentication/saml-realm.asciidoc
  docs/en/stack/security/authentication/token-authentication-services.asciidoc
  docs/en/stack/security/authorization/built-in-roles.asciidoc
  docs/en/stack/security/authorization/document-level-security.asciidoc
  docs/en/stack/security/authorization/field-level-security.asciidoc
  docs/en/stack/security/authorization/images/authorization.png
  docs/en/stack/security/authorization/index.asciidoc
  docs/en/stack/security/authorization/overview.asciidoc
  docs/en/stack/security/authorization/privileges.asciidoc
  docs/en/stack/security/get-started-builtin-users.asciidoc
  docs/en/stack/security/get-started-enable-security.asciidoc
  docs/en/stack/security/get-started-kibana-users.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
  docs/en/stack/security/how-security-works.asciidoc
  docs/en/stack/security/images/assign-role.jpg
  docs/en/stack/security/images/create-logstash-user.jpg
  docs/en/stack/security/images/create-reader-role.jpg
  docs/en/stack/security/images/create-user.jpg
  docs/en/stack/security/images/create-writer-role.jpg
  docs/en/stack/security/images/management-builtin-users.jpg
  docs/en/stack/security/images/management-roles.jpg
  docs/en/stack/security/images/management-users.jpg
  docs/en/stack/security/index.asciidoc
  docs/en/stack/security/limitations.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-addnodes.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-certificates.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-internode.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-intro.asciidoc
  docs/en/stack/security/troubleshooting.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#619 [DOCS] Marks DFA and the related analytics types as experimental feataures
  docs/en/stack/ml/df-analytics/dfa-outlierdetection.asciidoc
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/evaluatedf-api.asciidoc
  docs/en/stack/ml/df-analytics/index.asciidoc
Labels: enhancement, v7.3.2, v7.4.1, v7.5.0, v8.0.0

#628 [7.3] [DOCS] Marks DFA and the related analytics types as experimental features
  docs/en/stack/ml/df-analytics/dfa-outlierdetection.asciidoc
  docs/en/stack/ml/df-analytics/evaluatedf-api.asciidoc
  docs/en/stack/ml/df-analytics/index.asciidoc
Labels: backport, enhancement, v7.3.2

#607 [DOCS] Adds ML feature template to the repository
  docs/en/stack/ml/doc-template/ml-feature-template.asciidoc
Labels: :ml

#616 [6.6] Stages removal of security content (#574)
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/authentication/active-directory-realm.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authentication/ldap-realm.asciidoc
  docs/en/stack/security/authorization/index.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
  docs/en/stack/security/index.asciidoc
Labels: backport

#630 [6.6] Removes security from Stack Overview (#623)
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/authentication/active-directory-realm.asciidoc
  docs/en/stack/security/authentication/built-in-users.asciidoc
  docs/en/stack/security/authentication/file-realm.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authentication/internal-users.asciidoc
  docs/en/stack/security/authentication/kerberos-realm.asciidoc
  docs/en/stack/security/authentication/ldap-realm.asciidoc
  docs/en/stack/security/authentication/native-realm.asciidoc
  docs/en/stack/security/authentication/overview.asciidoc
  docs/en/stack/security/authentication/pki-realm.asciidoc
  docs/en/stack/security/authentication/realm-chains.asciidoc
  docs/en/stack/security/authentication/realms.asciidoc
  docs/en/stack/security/authentication/saml-realm.asciidoc
  docs/en/stack/security/authorization/built-in-roles.asciidoc
  docs/en/stack/security/authorization/document-level-security.asciidoc
  docs/en/stack/security/authorization/field-level-security.asciidoc
  docs/en/stack/security/authorization/images/authorization.png
  docs/en/stack/security/authorization/index.asciidoc
  docs/en/stack/security/authorization/overview.asciidoc
  docs/en/stack/security/authorization/privileges.asciidoc
  docs/en/stack/security/get-started-builtin-users.asciidoc
  docs/en/stack/security/get-started-enable-security.asciidoc
  docs/en/stack/security/get-started-kibana-users.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
  docs/en/stack/security/how-security-works.asciidoc
  docs/en/stack/security/images/assign-role.jpg
  docs/en/stack/security/images/create-logstash-user.jpg
  docs/en/stack/security/images/create-reader-role.jpg
  docs/en/stack/security/images/create-user.jpg
  docs/en/stack/security/images/create-writer-role.jpg
  docs/en/stack/security/images/management-builtin-users.jpg
  docs/en/stack/security/images/management-roles.jpg
  docs/en/stack/security/images/management-users.jpg
  docs/en/stack/security/index.asciidoc
  docs/en/stack/security/limitations.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-addnodes.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-certificates.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-internode.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-intro.asciidoc
  docs/en/stack/security/troubleshooting.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#624 [6.5][DOCS] Stages removal of security content
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/authentication/active-directory-realm.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authentication/ldap-realm.asciidoc
  docs/en/stack/security/authorization/index.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
  docs/en/stack/security/index.asciidoc
Labels: backport

#631 [6.5] Removes security from Stack Overview
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/authentication/active-directory-realm.asciidoc
  docs/en/stack/security/authentication/built-in-users.asciidoc
  docs/en/stack/security/authentication/file-realm.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authentication/internal-users.asciidoc
  docs/en/stack/security/authentication/kerberos-realm.asciidoc
  docs/en/stack/security/authentication/ldap-realm.asciidoc
  docs/en/stack/security/authentication/native-realm.asciidoc
  docs/en/stack/security/authentication/overview.asciidoc
  docs/en/stack/security/authentication/pki-realm.asciidoc
  docs/en/stack/security/authentication/realm-chains.asciidoc
  docs/en/stack/security/authentication/realms.asciidoc
  docs/en/stack/security/authentication/saml-realm.asciidoc
  docs/en/stack/security/authorization/built-in-roles.asciidoc
  docs/en/stack/security/authorization/document-level-security.asciidoc
  docs/en/stack/security/authorization/field-level-security.asciidoc
  docs/en/stack/security/authorization/images/authorization.png
  docs/en/stack/security/authorization/index.asciidoc
  docs/en/stack/security/authorization/overview.asciidoc
  docs/en/stack/security/authorization/privileges.asciidoc
  docs/en/stack/security/get-started-builtin-users.asciidoc
  docs/en/stack/security/get-started-enable-security.asciidoc
  docs/en/stack/security/get-started-kibana-users.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
  docs/en/stack/security/how-security-works.asciidoc
  docs/en/stack/security/images/assign-role.jpg
  docs/en/stack/security/images/create-logstash-user.jpg
  docs/en/stack/security/images/create-reader-role.jpg
  docs/en/stack/security/images/create-user.jpg
  docs/en/stack/security/images/create-writer-role.jpg
  docs/en/stack/security/images/management-builtin-users.jpg
  docs/en/stack/security/images/management-roles.jpg
  docs/en/stack/security/images/management-users.jpg
  docs/en/stack/security/index.asciidoc
  docs/en/stack/security/limitations.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-addnodes.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-certificates.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-internode.asciidoc
  docs/en/stack/security/securing-communications/tutorial-tls-intro.asciidoc
  docs/en/stack/security/troubleshooting.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#625 [6.4] Stages removal of security content
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/authentication/active-directory-realm.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authentication/ldap-realm.asciidoc
  docs/en/stack/security/authorization/index.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
  docs/en/stack/security/index.asciidoc
  docs/en/stack/security/troubleshooting.asciidoc
Labels: backport

#626 [6.3] Stages removal of security content
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/authentication/active-directory-realm.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authentication/ldap-realm.asciidoc
  docs/en/stack/security/authorization/index.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
  docs/en/stack/security/index.asciidoc
Labels: backport

#632 [6.4] Removes security from Stack Overview
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/authentication/active-directory-realm.asciidoc
  docs/en/stack/security/authentication/built-in-users.asciidoc
  docs/en/stack/security/authentication/file-realm.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authentication/internal-users.asciidoc
  docs/en/stack/security/authentication/kerberos-realm.asciidoc
  docs/en/stack/security/authentication/ldap-realm.asciidoc
  docs/en/stack/security/authentication/native-realm.asciidoc
  docs/en/stack/security/authentication/overview.asciidoc
  docs/en/stack/security/authentication/pki-realm.asciidoc
  docs/en/stack/security/authentication/realms.asciidoc
  docs/en/stack/security/authentication/saml-realm.asciidoc
  docs/en/stack/security/authorization/built-in-roles.asciidoc
  docs/en/stack/security/authorization/document-level-security.asciidoc
  docs/en/stack/security/authorization/field-level-security.asciidoc
  docs/en/stack/security/authorization/images/authorization.png
  docs/en/stack/security/authorization/index.asciidoc
  docs/en/stack/security/authorization/overview.asciidoc
  docs/en/stack/security/authorization/privileges.asciidoc
  docs/en/stack/security/get-started-builtin-users.asciidoc
  docs/en/stack/security/get-started-enable-security.asciidoc
  docs/en/stack/security/get-started-kibana-users.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
  docs/en/stack/security/how-security-works.asciidoc
  docs/en/stack/security/images/assign-role.jpg
  docs/en/stack/security/images/create-logstash-user.jpg
  docs/en/stack/security/images/create-reader-role.jpg
  docs/en/stack/security/images/create-user.jpg
  docs/en/stack/security/images/create-writer-role.jpg
  docs/en/stack/security/images/management-builtin-users.jpg
  docs/en/stack/security/images/management-roles.jpg
  docs/en/stack/security/images/management-users.jpg
  docs/en/stack/security/index.asciidoc
  docs/en/stack/security/limitations.asciidoc
  docs/en/stack/security/troubleshooting.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport

#633 [6.3] Removes security from Stack Overview
  docs/en/stack/index.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/authentication/active-directory-realm.asciidoc
  docs/en/stack/security/authentication/built-in-users.asciidoc
  docs/en/stack/security/authentication/file-realm.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authentication/internal-users.asciidoc
  docs/en/stack/security/authentication/ldap-realm.asciidoc
  docs/en/stack/security/authentication/native-realm.asciidoc
  docs/en/stack/security/authentication/overview.asciidoc
  docs/en/stack/security/authentication/pki-realm.asciidoc
  docs/en/stack/security/authentication/realms.asciidoc
  docs/en/stack/security/authentication/saml-realm.asciidoc
  docs/en/stack/security/authorization/built-in-roles.asciidoc
  docs/en/stack/security/authorization/document-level-security.asciidoc
  docs/en/stack/security/authorization/field-level-security.asciidoc
  docs/en/stack/security/authorization/images/authorization.png
  docs/en/stack/security/authorization/index.asciidoc
  docs/en/stack/security/authorization/overview.asciidoc
  docs/en/stack/security/authorization/privileges.asciidoc
  docs/en/stack/security/get-started-builtin-users.asciidoc
  docs/en/stack/security/get-started-enable-security.asciidoc
  docs/en/stack/security/get-started-kibana-users.asciidoc
  docs/en/stack/security/get-started-security.asciidoc
  docs/en/stack/security/how-security-works.asciidoc
  docs/en/stack/security/images/assign-role.jpg
  docs/en/stack/security/images/create-logstash-user.jpg
  docs/en/stack/security/images/create-reader-role.jpg
  docs/en/stack/security/images/create-user.jpg
  docs/en/stack/security/images/create-writer-role.jpg
  docs/en/stack/security/images/management-builtin-users.jpg
  docs/en/stack/security/images/management-roles.jpg
  docs/en/stack/security/images/management-users.jpg
  docs/en/stack/security/index.asciidoc
  docs/en/stack/security/limitations.asciidoc
  docs/en/stack/security/troubleshooting.asciidoc
  docs/en/stack/xpack-limitations.asciidoc
  docs/en/stack/xpack-troubleshooting.asciidoc
Labels: backport

#613 [DOCS] Revamps Data Fame Analytics section
  docs/en/stack/ml/df-analytics/dfa-outlierdetection.asciidoc
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/evaluatedf-api.asciidoc
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-concepts.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
Labels: :ml, :ml/Data Frame, v7.3.2, v7.4.1, v7.5.0, v8.0.0

#635 [7.3] [DOCS] Revamps Data Frame Analytics section
  docs/en/stack/ml/df-analytics/dfa-outlierdetection.asciidoc
  docs/en/stack/ml/df-analytics/evaluatedf-api.asciidoc
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-concepts.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
Labels: :ml, :ml/Data Frame, backport, v7.3.2

#648 [SIEM] [Docs] Adds note about map connection lines
  docs/en/siem/siem-ui.asciidoc
Labels: v7.4.0

#581 [DOCS] Preliminary work to split Infrastructure and Logs monitoring into two books
  docs/en/getting-started/get-started-stack.asciidoc
  docs/en/infraops/infra-ui-intro.asciidoc
  docs/en/infraops/logs-ui-intro.asciidoc
  docs/en/infraops/overview.asciidoc
  docs/en/logs/images/add-data.png
  docs/en/logs/images/logs-console.png
  docs/en/logs/images/logs-monitoring-architecture.png
  docs/en/logs/index.asciidoc
  docs/en/logs/logs-installation.asciidoc
  docs/en/logs/logs-overview.asciidoc
  docs/en/logs/logs-ui-intro.asciidoc
  docs/en/metrics/images/add-data.png
  docs/en/metrics/images/infra-sysmon.png
  docs/en/metrics/images/metrics-monitoring-architecture.png
  docs/en/metrics/index.asciidoc
  docs/en/metrics/infra-ui-intro.asciidoc
  docs/en/metrics/infrastructure-metrics.asciidoc
  docs/en/metrics/installation.asciidoc
  docs/en/metrics/metrics-overview.asciidoc
Labels: Infrastructure monitoring, review, v7.5.0

#638 [DOCS] Renames limitation items in DFA limitations
  docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
Labels: :ml, v7.3.2, v7.4.1, v7.5.0, v7.6.0, v8.0.0

#655 [DOCS] Adding temporary banner to mark Logs and Metrics docs as "future"
  docs/en/logs/page_header.html
  docs/en/metrics/page_header.html
Labels: Infrastructure monitoring, v7.5.0

#656 [7.3][DOCS] Renames limitation items in DFA limitations
  docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
Labels: :ml, backport, v7.3.2

#586 [DOCS] Added instructions for 3 nodes + kibana
  docs/en/getting-started/docker/.env
  docs/en/getting-started/docker/create-certs.yml
  docs/en/getting-started/docker/docker-compose.yml
  docs/en/getting-started/docker/elastic-docker-tls.yml
  docs/en/getting-started/docker/instances.yml
  docs/en/getting-started/get-started-docker.asciidoc
Labels: enhancement, v7.4.0, v7.5.0, v7.6.0, v8.0.0

#664 [DOCS] Added instructions for 3 nodes + kibana (#586)
  docs/en/getting-started/docker/.env
  docs/en/getting-started/docker/create-certs.yml
  docs/en/getting-started/docker/docker-compose.yml
  docs/en/getting-started/docker/elastic-docker-tls.yml
  docs/en/getting-started/docker/instances.yml
  docs/en/getting-started/get-started-docker.asciidoc
Labels: backport

#649 [SIEM] [Docs] Basic 7.5 updates
  docs/en/siem/images/add-data.png
  docs/en/siem/images/hosts-ui.png
  docs/en/siem/images/network-ui.png
  docs/en/siem/images/overview-ui.png
  docs/en/siem/images/siem-architecture.png
  docs/en/siem/machine-learning.asciidoc
  docs/en/siem/overview.asciidoc
  docs/en/siem/siem-ui.asciidoc
Labels: v7.5.0

#669 [DOCS] Correcting release conditionals for sample files
  docs/en/getting-started/get-started-docker.asciidoc
Labels: bug, v7.4.0, v7.5.0, v7.6.0, v8.0.0

#640 [DOCS] Extends DFA overview with outlier detection and regression reference
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
Labels: :ml, v7.4.1, v7.5.0, v7.6.0, v8.0.0
