Repository elastic/stack-docs, pull requests merged in 2019-07, with the labels that each got.

#392 [DOCS] Removes the term: tutorial from the Getting started with the Elastic Stack page
  docs/en/getting-started/get-started-stack.asciidoc
Labels: v6.3.0, v6.4.0, v6.5.0, v6.6.0, v6.7.0, v6.8.0, v7.0.0, v7.1.0, v7.2.0, v7.3.0, v8.0.0

#389 [DOCS] Creates a data frame examples page
  docs/en/stack/data-frames/dataframe-examples.asciidoc
  docs/en/stack/data-frames/index.asciidoc
Labels: :ml, v7.2.0, v7.3.0, v8.0.0

#396 Updates version attributes
  docs/en/getting-started/index.asciidoc
  docs/en/infraops/index.asciidoc
  docs/en/stack/index.asciidoc
Labels: v7.4.0

#395 Document "manage_api_key" cluster privilege
  docs/en/stack/security/authorization/privileges.asciidoc
Labels: :Security, v7.3.0, v8.0.0

#401 Updates ML job terminology
  docs/en/glossary/glossary.asciidoc
  docs/en/stack/ml/api-quickref.asciidoc
Labels: :ml, v7.3.0, v7.4.0, v8.0.0

#400 [Backport 7.x] Document "manage_api_key" cluster privilege
  docs/en/stack/security/authorization/privileges.asciidoc
Labels: backport

#403 Moves limitation pages within Stack Overview
  docs/en/stack/data-frames/index.asciidoc
  docs/en/stack/data-frames/limitations.asciidoc
  docs/en/stack/images/watcher-ui-edit-watch.png
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/ml/index.asciidoc
  docs/en/stack/ml/limitations.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/index.asciidoc
  docs/en/stack/security/limitations.asciidoc
  docs/en/stack/watcher/limitations.asciidoc
Labels: v7.3.0, v7.4.0, v8.0.0

#408 Adds Kibana highlights and breaking changes
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.3.0

#405 Moves troubleshooting pages within Stack Overview
  docs/en/stack/help.asciidoc
  docs/en/stack/index.asciidoc
  docs/en/stack/ml/getting-started-next.asciidoc
  docs/en/stack/ml/index.asciidoc
  docs/en/stack/ml/troubleshooting.asciidoc
  docs/en/stack/monitoring/index.asciidoc
  docs/en/stack/monitoring/troubleshooting.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/security/index.asciidoc
  docs/en/stack/security/troubleshooting.asciidoc
  docs/en/stack/troubleshooting.asciidoc
  docs/en/stack/watcher/troubleshooting.asciidoc
Labels: v7.3.0, v7.4.0, v8.0.0

#409 Removes the machine learning tutorial
  docs/en/stack/ml/analyzing.asciidoc
  docs/en/stack/ml/index.asciidoc
  docs/en/stack/ml/jobs.asciidoc
Labels: v7.2.1, v7.3.0, v7.4.0, v8.0.0

#410 [DOCS] Updates screenshots in data frame example
  docs/en/stack/data-frames/ecommerce-example.asciidoc
  docs/en/stack/data-frames/images/dataframe-transforms.jpg
  docs/en/stack/data-frames/images/ecommerce-batch.jpg
  docs/en/stack/data-frames/images/ecommerce-continuous.jpg
  docs/en/stack/data-frames/images/ecommerce-pivot1.jpg
  docs/en/stack/data-frames/images/ecommerce-pivot2.jpg
  docs/en/stack/data-frames/images/ecommerce-results.jpg
  docs/en/stack/images/dataframe-jobs.jpg
  docs/en/stack/images/ecommerce-pivot1.jpg
  docs/en/stack/images/ecommerce-pivot2.jpg
  docs/en/stack/images/ecommerce-results.jpg
Labels: :ml, v7.3.0, v7.4.0, v8.0.0

#414 Removes edit_url attributes
  docs/en/stack/ml/getting-started.asciidoc
  docs/en/stack/ml/overview.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authorization/index.asciidoc
Labels: v8.0.0

#415 Adds data frame analytics placeholder to Stack Overview
  docs/en/stack/data-frames/dataframes.asciidoc
  docs/en/stack/index.asciidoc
  docs/en/stack/ml/df-analytics/api-quickref.asciidoc
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/index.asciidoc
Labels: :ml, v7.3.0, v7.4.0, v8.0.0

#416 [7.x] Removes edit_url attributes (#414)
  docs/en/stack/ml/getting-started.asciidoc
  docs/en/stack/ml/overview.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authorization/index.asciidoc
Labels: backport, v7.4.0

#417 [7.3] Removes edit_url attributes (#414)
  docs/en/stack/ml/getting-started.asciidoc
  docs/en/stack/ml/overview.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authorization/index.asciidoc
Labels: v7.3.0

#418 [7.2] Removes edit_url attributes (#414)
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/ml/getting-started.asciidoc
  docs/en/stack/ml/index.asciidoc
  docs/en/stack/ml/overview.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authorization/index.asciidoc
  docs/en/stack/security/index.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport, v7.2.1

#419 [7.1] Removes edit_url attributes (#414)
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/ml/getting-started.asciidoc
  docs/en/stack/ml/index.asciidoc
  docs/en/stack/ml/overview.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authorization/index.asciidoc
  docs/en/stack/security/index.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport, v7.1.1

#407 [DOCS] Updates data frame limitations for 7.3.
  docs/en/stack/data-frames/limitations.asciidoc
Labels: :ml, v7.3.0, v7.4.0, v8.0.0

#412 [DOCS] Updates conceptual overview with checkpointing and continuous data frames
  docs/en/stack/data-frames/dataframes.asciidoc
Labels: :ml, v7.3.0, v7.4.0, v8.0.0

#383 [DOCS] Adds data frame analytics overview
  docs/en/stack/ml/df-analytics/dfa-outlierdetection.asciidoc
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/images/ml-densitybm.jpg
  docs/en/stack/ml/overview.asciidoc
Labels: :ml, v7.3.0

#420 [7.0] Removes edit_url attributes (#414)
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/ml/getting-started.asciidoc
  docs/en/stack/ml/index.asciidoc
  docs/en/stack/ml/overview.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authorization/index.asciidoc
  docs/en/stack/security/index.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport, v7.0.1

#426 [6.6] Removes edit_url attributes (#414)
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/ml/getting-started.asciidoc
  docs/en/stack/ml/index.asciidoc
  docs/en/stack/ml/overview.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authorization/index.asciidoc
  docs/en/stack/security/index.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: v6.6.3

#427 [6.4] Removes edit_url attributes (#414)
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/ml/getting-started.asciidoc
  docs/en/stack/ml/index.asciidoc
  docs/en/stack/ml/overview.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authorization/index.asciidoc
  docs/en/stack/security/index.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: v6.4.4

#424 [6.8] Removes edit_url attributes (#414)
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/ml/getting-started.asciidoc
  docs/en/stack/ml/index.asciidoc
  docs/en/stack/ml/overview.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authorization/index.asciidoc
  docs/en/stack/security/index.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: v6.8.2

#429 [DOCS] Reorganizes data frame examples
  docs/en/stack/data-frames/dataframe-examples.asciidoc
  docs/en/stack/data-frames/ecommerce-example.asciidoc
  docs/en/stack/data-frames/index.asciidoc
Labels: :ml, v7.2.1, v7.3.0, v7.4.0, v8.0.0

#428 [6.3] Removes edit_url attributes (#414)
  docs/en/stack/index.asciidoc
  docs/en/stack/ml/getting-started.asciidoc
  docs/en/stack/ml/index.asciidoc
  docs/en/stack/ml/overview.asciidoc
  docs/en/stack/security/authentication/index.asciidoc
  docs/en/stack/security/authorization/index.asciidoc
  docs/en/stack/security/index.asciidoc
  docs/en/stack/xpack-limitations.asciidoc
  docs/en/stack/xpack-troubleshooting.asciidoc
Labels: v6.3.3

#430 Moves ML content to anomaly-detection folder
  docs/en/stack/data-frames/dataframes.asciidoc
  docs/en/stack/data-frames/images/ml-dataframepivot.jpg
  docs/en/stack/index.asciidoc
  docs/en/stack/ml/anomaly-detection/analyzing.asciidoc
  docs/en/stack/ml/anomaly-detection/api-quickref.asciidoc
  docs/en/stack/ml/anomaly-detection/architecture.asciidoc
  docs/en/stack/ml/anomaly-detection/buckets.asciidoc
  docs/en/stack/ml/anomaly-detection/calendars.asciidoc
  docs/en/stack/ml/anomaly-detection/datafeeds.asciidoc
  docs/en/stack/ml/anomaly-detection/forecasting.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-data.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-forecast.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-multi.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-next.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-single.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-wizards.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started.asciidoc
  docs/en/stack/ml/anomaly-detection/images/ml-gs-aggregations.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-create-job.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-dates.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-keywords.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-metrics.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-topmetrics.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-visualizer.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-duration.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast-actual.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast-open.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast-results.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job-analysis.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job-forecast.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-analysis.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-anomalies.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-datafeed.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-explorer-anomaly.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-explorer.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-manage1.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-results.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-time.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer-anomaly.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer-host.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer-table.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-split.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-multi-job.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-single-job.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-start-feed.jpg
  docs/en/stack/ml/anomaly-detection/images/multibucketanalysis.jpg
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/limitations.asciidoc
  docs/en/stack/ml/anomaly-detection/overview.asciidoc
  docs/en/stack/ml/anomaly-detection/rules.asciidoc
  docs/en/stack/ml/anomaly-detection/troubleshooting.asciidoc
  docs/en/stack/ml/df-analytics/images/ml-densitybm.jpg
Labels: :ml, v7.3.0, v7.4.0, v8.0.0

#431 Adds data frame transform troubleshooting info
  docs/en/stack/data-frames/index.asciidoc
  docs/en/stack/data-frames/troubleshooting.asciidoc
Labels: :ml/Data Frame, v7.2.1, v7.3.0, v7.4.0, v8.0.0

#433 [7.x] Moves ML content to anomaly-detection folder (#430)
  docs/en/stack/data-frames/dataframes.asciidoc
  docs/en/stack/data-frames/images/ml-dataframepivot.jpg
  docs/en/stack/index.asciidoc
  docs/en/stack/ml/anomaly-detection/analyzing.asciidoc
  docs/en/stack/ml/anomaly-detection/api-quickref.asciidoc
  docs/en/stack/ml/anomaly-detection/architecture.asciidoc
  docs/en/stack/ml/anomaly-detection/buckets.asciidoc
  docs/en/stack/ml/anomaly-detection/calendars.asciidoc
  docs/en/stack/ml/anomaly-detection/datafeeds.asciidoc
  docs/en/stack/ml/anomaly-detection/forecasting.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-data.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-forecast.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-multi.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-next.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-single.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-wizards.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started.asciidoc
  docs/en/stack/ml/anomaly-detection/images/ml-gs-aggregations.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-create-job.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-dates.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-keywords.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-metrics.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-topmetrics.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-visualizer.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-duration.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast-actual.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast-open.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast-results.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job-analysis.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job-forecast.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-analysis.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-anomalies.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-datafeed.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-explorer-anomaly.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-explorer.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-manage1.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-results.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-time.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer-anomaly.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer-host.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer-table.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-split.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-multi-job.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-single-job.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-start-feed.jpg
  docs/en/stack/ml/anomaly-detection/images/multibucketanalysis.jpg
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/limitations.asciidoc
  docs/en/stack/ml/anomaly-detection/overview.asciidoc
  docs/en/stack/ml/anomaly-detection/rules.asciidoc
  docs/en/stack/ml/anomaly-detection/troubleshooting.asciidoc
  docs/en/stack/ml/df-analytics/images/ml-densitybm.jpg
Labels: backport

#434 [7.3] Moves ML content to anomaly-detection folder (#430)
  docs/en/stack/data-frames/dataframes.asciidoc
  docs/en/stack/data-frames/images/ml-dataframepivot.jpg
  docs/en/stack/index.asciidoc
  docs/en/stack/ml/anomaly-detection/analyzing.asciidoc
  docs/en/stack/ml/anomaly-detection/api-quickref.asciidoc
  docs/en/stack/ml/anomaly-detection/architecture.asciidoc
  docs/en/stack/ml/anomaly-detection/buckets.asciidoc
  docs/en/stack/ml/anomaly-detection/calendars.asciidoc
  docs/en/stack/ml/anomaly-detection/datafeeds.asciidoc
  docs/en/stack/ml/anomaly-detection/forecasting.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-data.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-forecast.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-multi.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-next.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-single.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-wizards.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started.asciidoc
  docs/en/stack/ml/anomaly-detection/images/ml-gs-aggregations.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-create-job.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-dates.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-keywords.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-metrics.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-topmetrics.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-visualizer.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-duration.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast-actual.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast-open.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast-results.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job-analysis.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job-forecast.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-analysis.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-anomalies.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-datafeed.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-explorer-anomaly.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-explorer.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-manage1.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-results.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-time.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer-anomaly.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer-host.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer-table.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-split.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-multi-job.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-single-job.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-start-feed.jpg
  docs/en/stack/ml/anomaly-detection/images/multibucketanalysis.jpg
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/limitations.asciidoc
  docs/en/stack/ml/anomaly-detection/overview.asciidoc
  docs/en/stack/ml/anomaly-detection/rules.asciidoc
  docs/en/stack/ml/anomaly-detection/troubleshooting.asciidoc
  docs/en/stack/ml/df-analytics/images/ml-densitybm.jpg
Labels: v7.3.0

#423 [DOCS] Update anchors and links for Elasticserach API relocation.
  docs/en/stack/data-frames/ecommerce-example.asciidoc
Labels: enhancement, v7.3.0, v7.4.0, v8.0.0

#437 Adjust troubleshooting guide for SAML
  docs/en/stack/security/troubleshooting.asciidoc
Labels: :Security, v7.3.0, v7.4.0, v8.0.0

#435 Adds info about when to use data frames
  docs/en/stack/data-frames/checkpoints.asciidoc
  docs/en/stack/data-frames/index.asciidoc
  docs/en/stack/data-frames/limitations.asciidoc
  docs/en/stack/data-frames/overview.asciidoc
Labels: :ml/Data Frame, v7.3.0, v7.4.0, v8.0.0

#439 [DOCS] Adds the evaluate API endpoint base to the quick reference page
  docs/en/stack/ml/df-analytics/api-quickref.asciidoc
Labels: :ml, v7.3.0, v7.4.0, v8.0.0

#442 [7.2] Moves ML content to anomaly-detection folder
  docs/en/stack/data-frames/images/ml-dataframepivot.jpg
  docs/en/stack/data-frames/overview.asciidoc
  docs/en/stack/index.asciidoc
  docs/en/stack/limitations.asciidoc
  docs/en/stack/ml/anomaly-detection/analyzing.asciidoc
  docs/en/stack/ml/anomaly-detection/api-quickref.asciidoc
  docs/en/stack/ml/anomaly-detection/architecture.asciidoc
  docs/en/stack/ml/anomaly-detection/buckets.asciidoc
  docs/en/stack/ml/anomaly-detection/calendars.asciidoc
  docs/en/stack/ml/anomaly-detection/datafeeds.asciidoc
  docs/en/stack/ml/anomaly-detection/forecasting.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-data.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-forecast.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-multi.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-next.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-single.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-wizards.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started.asciidoc
  docs/en/stack/ml/anomaly-detection/images/ml-gs-aggregations.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-create-job.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-dates.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-keywords.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-metrics.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-topmetrics.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-data-visualizer.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-duration.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast-actual.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast-open.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast-results.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-forecast.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job-analysis.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job-forecast.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-analysis.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-anomalies.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-datafeed.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-explorer-anomaly.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-explorer.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-manage1.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-results.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1-time.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job1.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer-anomaly.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer-host.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer-table.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-explorer.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-job2-split.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-multi-job.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-single-job.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-gs-start-feed.jpg
  docs/en/stack/ml/anomaly-detection/images/multibucketanalysis.jpg
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/limitations.asciidoc
  docs/en/stack/ml/anomaly-detection/overview.asciidoc
  docs/en/stack/ml/anomaly-detection/rules.asciidoc
  docs/en/stack/ml/anomaly-detection/troubleshooting.asciidoc
  docs/en/stack/troubleshooting.asciidoc
Labels: backport, v7.2.1

#443 Update "audience condition" SAML troubleshooting
  docs/en/stack/security/troubleshooting.asciidoc
Labels: :Security, v7.4.0, v8.0.0

#444 Updates anomaly detection job terminology in Stack Overview
  docs/en/stack/ml/anomaly-detection/api-quickref.asciidoc
  docs/en/stack/ml/anomaly-detection/buckets.asciidoc
  docs/en/stack/ml/anomaly-detection/calendars.asciidoc
  docs/en/stack/ml/anomaly-detection/datafeeds.asciidoc
  docs/en/stack/ml/anomaly-detection/forecasting.asciidoc
  docs/en/stack/ml/anomaly-detection/jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/limitations.asciidoc
  docs/en/stack/ml/anomaly-detection/rules.asciidoc
  docs/en/stack/ml/anomaly-detection/troubleshooting.asciidoc
Labels: :ml, v7.2.1, v7.3.0, v7.4.0, v8.0.0

#446 [DOCS] Fixes the headings in the data frame transform limitations
  docs/en/stack/data-frames/limitations.asciidoc
Labels: :ml/Data Frame, v7.3.0, v7.4.0, v8.0.0

#404 Monitoring Logstash and Beats with Metricbeat
  docs/en/stack/monitoring/esms.asciidoc
  docs/en/stack/monitoring/how-monitoring-works.asciidoc
  docs/en/stack/monitoring/images/architecture30.png
  docs/en/stack/monitoring/intro.asciidoc
  docs/en/stack/monitoring/production.asciidoc
Labels: :Monitoring, v7.3.0, v7.4.0, v8.0.0

#449 Updates 7.3.0 release highlights and breaking changes
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.3.0
