Repository elastic/stack-docs, pull requests merged in 2019-03, with the labels that each got.

#187 [DOCS] Replaces X-Pack security terminology
  docs/en/install-upgrade/upgrading-stack.asciidoc
  docs/en/stack/security/authentication/built-in-users.asciidoc
  docs/en/stack/security/authentication/internal-users.asciidoc
  docs/en/stack/security/authentication/overview.asciidoc
  docs/en/stack/security/authorization/built-in-roles.asciidoc
  docs/en/stack/security/authorization/overview.asciidoc
  docs/en/stack/security/how-security-works.asciidoc
  docs/en/stack/security/index.asciidoc
  docs/en/stack/security/limitations.asciidoc
Labels: :Security, v6.5.4, v6.5.5, v6.6.0, v6.7.0, v7.0.0

#232 [DOCS] Adds notable breaking changes from Kibana
  docs/en/install-upgrade/breaking.asciidoc
Labels: v8.0.0

#231 [DOCS] Drafts data frame privileges
  docs/en/stack/security/authorization/built-in-roles.asciidoc
  docs/en/stack/security/authorization/privileges.asciidoc
Labels: :ml, v7.1.0, v8.0.0

#233 Adds notable breaking changes from Elasticsearch
  docs/en/install-upgrade/breaking.asciidoc
Labels: v7.0.0, v7.1.0, v8.0.0

#244 Fixes link to Cloud documentation
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: v6.0.2, v6.1.5, v6.2.5, v6.3.4, v6.4.4, v6.5.5, v6.6.0, v6.7.0, v7.0.0, v7.1.0, v8.0.0

#246 Fix ML built in role docs
  docs/en/stack/security/authorization/built-in-roles.asciidoc
Labels: :ml, v6.6.3, v6.7.0, v7.0.0, v7.1.0, v8.0.0

#247 [DOCS] Deprecates migration assistance and upgrade APIs
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: v6.7.0, v7.0.0, v7.1.0, v8.0.0

#252 [DOCS] Adds highlights to the Installation and Upgrade Guide
  docs/en/install-upgrade/highlights.asciidoc
  docs/en/install-upgrade/index.asciidoc
Labels: WIP, v7.0.0, v7.1.0, v8.0.0

#229 Link to infrastructure monitoring docs from the stack getting started
  docs/en/getting-started/get-started-stack.asciidoc
Labels: needs_backport

#242 7.0 upgrade
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: v7.0.0

#253 [Infra UI] Add documentation for known workarounds
  docs/en/infraops/installation.asciidoc
Labels: review, v6.7.0, v7.0.0, v7.1.0, v8.0.0

#257 Adds 7.0 Elasticsearch breaking changes
  docs/en/install-upgrade/breaking.asciidoc
Labels: v7.0.0

#262 [DOCS] Work around for titleabbrev errors
  docs/en/stack/watcher/troubleshooting.asciidoc
Labels: v6.3.4, v6.4.4, v6.5.5, v6.6.3, v6.7.0, v7.0.0, v7.1.0, v8.0.0
