Repository elastic/stack-docs, pull requests merged in 2019-04, with the labels that each got.

#263 [DOCS] Clarify version compability in monitoring docs
  docs/en/stack/monitoring/how-monitoring-works.asciidoc
Labels: :Monitoring, v6.7.0, v7.0.0, v7.1.0, v8.0.0

#264 [DOCS] Adds notable Beats breaking changes
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/index.asciidoc
Labels: v8.0.0

#256 [DOCS] Adds notable Beats breaking changes
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/index.asciidoc
Labels: backport, v7.0.0

#265 Splits highlights and breaking changes into multiple pages
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.0.0, v7.1.0, v8.0.0

#267 Adds APM breaking changes to Install Upgrade Guide
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/index.asciidoc
Labels: v7.0.0, v7.1.0, v8.0.0

#269 Adds APM breaking changes to Install Upgrade Guide (#267)
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/index.asciidoc
Labels: backport

#270 Adds APM breaking changes to Install Upgrade Guide (#267)
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/index.asciidoc
Labels: backport

#268 Adds Elasticsearch Hadoop breaking changes to Install Upgrade Guide
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/index.asciidoc
Labels: v7.0.0, v7.1.0, v8.0.0

#271 Adds Logstash breaking changes to Install Upgrade Guide
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/index.asciidoc
Labels: v7.0.0, v7.1.0, v8.0.0

#274 Adds Logstash breaking changes to Install Upgrade Guide (#271)
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/index.asciidoc
Labels: backport

#273 Adds Beats highlights to Install Upgrade Guide
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.0.0, v7.1.0, v8.0.0

#275 [Infra UI] Fixing Kubernetes memory field typo
  docs/en/infraops/installation.asciidoc
Labels: Infrastructure monitoring, review, v6.7.0, v7.0.0, v7.1.0, v8.0.0

#283 Adds more Elasticsearch breaking changes
  docs/en/install-upgrade/breaking.asciidoc
Labels: v8.0.0

#278 Updates X-Pack and Upgrade Assistant details
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: v6.7.0

#277 [7.0] Adds Beats highlights to Install Upgrade Guide
  docs/en/install-upgrade/highlights.asciidoc
Labels: backport, v7.0.0

#288 Adds ingest and ml breaking changes
  docs/en/install-upgrade/breaking.asciidoc
Labels: v7.0.0

#290 Removes 2.x references from Install Upgrade breaking changes
  docs/en/install-upgrade/breaking.asciidoc
Labels: v7.0.0, v7.1.0, v8.0.0

#292 Changes title and adds subtitle for gke-on-prem book
  docs/en/gke-on-prem/index.asciidoc
Labels: v8.0.0

#291 Adds ILM breaking changes
  docs/en/install-upgrade/breaking.asciidoc
Labels: v8.0.0

#293 Fixes list continuation issues
  docs/en/stack/security/troubleshooting.asciidoc
Labels: v6.3.4, v6.4.4, v6.5.5, v6.6.3, v6.7.0, v7.0.0, v7.1.0, v8.0.0

#282 Adds Elasticsearch 8.0 notable breaking changes
  docs/en/install-upgrade/breaking.asciidoc
Labels: v8.0.0

#294 Fixes link in gke-on-prem-architecture
  docs/en/gke-on-prem/gke-on-prem-architecture.asciidoc
Labels: v8.0.0

#313 [7.0] Backport: Add linux examples (#198)
  docs/en/getting-started/get-started-stack.asciidoc
Labels: backport, review

#314 [6.7] Backport: Link to infrastructure monitoring docs from the stack getting started…
  docs/en/getting-started/get-started-stack.asciidoc
Labels: backport, review

#315 [7.0] Backport: Link to infrastructure monitoring docs from the stack getting started
  docs/en/getting-started/get-started-stack.asciidoc
Labels: backport, review

#285 [Infra UI] Adding note required field for metric detail page and fixing typos
  docs/en/infraops/installation.asciidoc
Labels: Infrastructure monitoring, review

#317 [Backport][7.x][Infra UI] Adding note required field for metric detail page and fixing typos (#285)
  docs/en/infraops/installation.asciidoc
Labels: backport

#316 [Backport][7.0][Infra UI] Adding note required field for metric detail page and fixing typos (#285
  docs/en/infraops/installation.asciidoc
Labels: backport

#289 [DOCS] Remove scale attributes
  docs/en/stack/monitoring/how-monitoring-works.asciidoc
Labels: v6.5.5, v6.6.3, v6.7.0, v7.0.0, v7.1.0, v8.0.0

#319 [DOCS] Fix typo
  docs/en/stack/security/authentication/ldap-realm.asciidoc
Labels: v7.1.0
