Repository elastic/stack-docs, pull requests merged in 2020-02, with the labels that each got.

#834 [DOCS] Fixes Elasticsearch release highlights and breaking changes
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.6.0

#833 [DOCS] Adds overview of anomaly detection algorithms
  docs/en/stack/ml/anomaly-detection/algorithms.asciidoc
  docs/en/stack/ml/anomaly-detection/analyzing.asciidoc
  docs/en/stack/ml/anomaly-detection/overview.asciidoc
Labels: :ml, v7.5.3, v7.6.0, v7.7.0, v8.0.0

#836 Updates the Kibana breaking changes
  docs/en/install-upgrade/breaking.asciidoc
Labels: v7.6.0

#835 [Docs][SIEM] Detections UI corrections
  docs/en/siem/detection-engine-intro.asciidoc
  docs/en/siem/images/all-rules.png
  docs/en/siem/images/rule-query-example.png
  docs/en/siem/rules-ui-create.asciidoc
Labels: v7.6.0

#837 [Docs][SIEM] 7.x siem ui corrections
  docs/en/siem/detection-engine-intro.asciidoc
  docs/en/siem/images/all-rules.png
  docs/en/siem/images/rule-query-example.png
  docs/en/siem/rules-ui-create.asciidoc
Labels: backport

#838 [Docs][SIEM]7.6 siem ui corrections
  docs/en/siem/detection-engine-intro.asciidoc
  docs/en/siem/images/all-rules.png
  docs/en/siem/images/rule-query-example.png
  docs/en/siem/rules-ui-create.asciidoc
Labels: backport, v7.6.0

#699 [SIEM] [Docs] Detection engine rules API
  docs/en/siem/detection-engine-intro.asciidoc
  docs/en/siem/images/detections-ui.png
  docs/en/siem/images/hosts-ui.png
  docs/en/siem/images/ml-ui.png
  docs/en/siem/images/network-ui.png
  docs/en/siem/images/overview-ui.png
  docs/en/siem/index-api-overview.asciidoc
  docs/en/siem/index.asciidoc
  docs/en/siem/prebuilt-rule-reference.asciidoc
  docs/en/siem/privileges-api-overview.asciidoc
  docs/en/siem/rules-api-bulk-actions.asciidoc
  docs/en/siem/rules-api-create.asciidoc
  docs/en/siem/rules-api-delete.asciidoc
  docs/en/siem/rules-api-export.asciidoc
  docs/en/siem/rules-api-find.asciidoc
  docs/en/siem/rules-api-get.asciidoc
  docs/en/siem/rules-api-import.asciidoc
  docs/en/siem/rules-api-overview.asciidoc
  docs/en/siem/rules-api-prebuilt.asciidoc
  docs/en/siem/rules-api-update.asciidoc
  docs/en/siem/rules-ui-create.asciidoc
  docs/en/siem/siem-ui.asciidoc
  docs/en/siem/signals-api-overview.asciidoc
  docs/en/siem/tags-api-overview.asciidoc
  docs/en/siem/tune-anomaly-results.asciidoc
Labels: v7.6.0

#839 [Docs][SIEM] 7.x Rules API
  docs/en/siem/detection-engine-intro.asciidoc
  docs/en/siem/images/detections-ui.png
  docs/en/siem/images/hosts-ui.png
  docs/en/siem/images/ml-ui.png
  docs/en/siem/images/network-ui.png
  docs/en/siem/images/overview-ui.png
  docs/en/siem/index-api-overview.asciidoc
  docs/en/siem/index.asciidoc
  docs/en/siem/prebuilt-rule-reference.asciidoc
  docs/en/siem/privileges-api-overview.asciidoc
  docs/en/siem/rules-api-bulk-actions.asciidoc
  docs/en/siem/rules-api-create.asciidoc
  docs/en/siem/rules-api-delete.asciidoc
  docs/en/siem/rules-api-export.asciidoc
  docs/en/siem/rules-api-find.asciidoc
  docs/en/siem/rules-api-get.asciidoc
  docs/en/siem/rules-api-import.asciidoc
  docs/en/siem/rules-api-overview.asciidoc
  docs/en/siem/rules-api-prebuilt.asciidoc
  docs/en/siem/rules-api-update.asciidoc
  docs/en/siem/rules-ui-create.asciidoc
  docs/en/siem/siem-ui.asciidoc
  docs/en/siem/signals-api-overview.asciidoc
  docs/en/siem/tags-api-overview.asciidoc
  docs/en/siem/tune-anomaly-results.asciidoc
Labels: backport

#840 [Docs][SIEM] 7.6 Rules API
  docs/en/siem/detection-engine-intro.asciidoc
  docs/en/siem/images/detections-ui.png
  docs/en/siem/images/hosts-ui.png
  docs/en/siem/images/ml-ui.png
  docs/en/siem/images/network-ui.png
  docs/en/siem/images/overview-ui.png
  docs/en/siem/index-api-overview.asciidoc
  docs/en/siem/index.asciidoc
  docs/en/siem/prebuilt-rule-reference.asciidoc
  docs/en/siem/privileges-api-overview.asciidoc
  docs/en/siem/rules-api-bulk-actions.asciidoc
  docs/en/siem/rules-api-create.asciidoc
  docs/en/siem/rules-api-delete.asciidoc
  docs/en/siem/rules-api-export.asciidoc
  docs/en/siem/rules-api-find.asciidoc
  docs/en/siem/rules-api-get.asciidoc
  docs/en/siem/rules-api-import.asciidoc
  docs/en/siem/rules-api-overview.asciidoc
  docs/en/siem/rules-api-prebuilt.asciidoc
  docs/en/siem/rules-api-update.asciidoc
  docs/en/siem/rules-ui-create.asciidoc
  docs/en/siem/siem-ui.asciidoc
  docs/en/siem/signals-api-overview.asciidoc
  docs/en/siem/tags-api-overview.asciidoc
  docs/en/siem/tune-anomaly-results.asciidoc
Labels: backport

#841 [DOCS] Fixes trained model terminology
  docs/en/stack/ml/df-analytics/ml-inference.asciidoc
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
Labels: :ml, v7.7.0, v8.0.0

#845 [DOCS] Adds screenshots to classification example
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-classification-details.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-evaluation.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-job.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-results.jpg
Labels: :ml, v7.6.1, v7.7.0, v8.0.0

#842 [DOCS] Adds screenshots to regression example
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-regression-details.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-job.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-results.jpg
Labels: :ml, v7.6.1, v7.7.0, v8.0.0

#854 [Docs][SIEM]Escapes asterisk character in apm indices
  docs/en/siem/rule-details/web-application-suspicious-activity-no-user-agent.asciidoc
  docs/en/siem/rule-details/web-application-suspicious-activity-post-request-declined.asciidoc
  docs/en/siem/rule-details/web-application-suspicious-activity-sqlmap-user-agent.asciidoc
  docs/en/siem/rule-details/web-application-suspicious-activity-unauthorized-method.asciidoc
Labels: v7.6.0

#855 [Docs][SIEM]Escapes asterisk character in apm indices
  docs/en/siem/rule-details/web-application-suspicious-activity-no-user-agent.asciidoc
  docs/en/siem/rule-details/web-application-suspicious-activity-post-request-declined.asciidoc
  docs/en/siem/rule-details/web-application-suspicious-activity-sqlmap-user-agent.asciidoc
  docs/en/siem/rule-details/web-application-suspicious-activity-unauthorized-method.asciidoc
Labels: backport

#856 [Docs][SIEM]Escapes asterisk character in apm indices
  docs/en/siem/rule-details/web-application-suspicious-activity-no-user-agent.asciidoc
  docs/en/siem/rule-details/web-application-suspicious-activity-post-request-declined.asciidoc
  docs/en/siem/rule-details/web-application-suspicious-activity-sqlmap-user-agent.asciidoc
  docs/en/siem/rule-details/web-application-suspicious-activity-unauthorized-method.asciidoc
Labels: backport

#858 [Docs][SIEM]Adds missing http tab and filebeat modules
  docs/en/siem/installation.asciidoc
  docs/en/siem/siem-ui.asciidoc
Labels: v7.6.0

#860 [Docs][SIEM ]7.6 add tab descriptions
  docs/en/siem/installation.asciidoc
  docs/en/siem/siem-ui.asciidoc
Labels: backport, v7.6.0

#844 [DOCS] Adds feature importance to regression and classification docs
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
  docs/en/stack/ml/shared-ml-concepts.asciidoc
Labels: :ml, v7.6.0, v7.7.0, v8.0.0

#859 [Docs][SIEM ]7.x add tab descriptions
  docs/en/siem/installation.asciidoc
  docs/en/siem/siem-ui.asciidoc
Labels: backport

#862 [Docs][SIEM]Fixes APM text and link
  docs/en/siem/siem-ui.asciidoc
Labels: backport

#850 [Docs][SIEM]Adds APM indices
  docs/en/siem/overview.asciidoc
  docs/en/siem/siem-ui.asciidoc
Labels: v7.6.0

#863 [Docs][SIEM]Adds APM indices
  docs/en/siem/overview.asciidoc
  docs/en/siem/siem-ui.asciidoc
Labels: backport

#864 [Docs][SIEM]Adds APM indices
  docs/en/siem/overview.asciidoc
  docs/en/siem/siem-ui.asciidoc
Labels: backport

#846 [DOCS] Collapses APIs in outlier example
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
Labels: :ml, v7.5.3, v7.6.1, v7.7.0, v8.0.0

#867 [DOCS] Adds Kibana 7.6.0 highlights
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.6.0

#869 [DOCS] Adds APM machine learning jobs
  docs/en/stack/ml/anomaly-detection/create-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/images/ml-data-recognizer-apm.jpg
Labels: :ml, v7.6.1, v7.7.0, v8.0.0

#847 [7.6][docs] Add APM tagged regions for 7.6.0
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.6.0

#868 [DOCS]: Add SIEM UI overview updates for 7.6
  docs/en/siem/images/events-count.png
  docs/en/siem/images/overview-ui.png
  docs/en/siem/siem-ui.asciidoc
Labels: Team:SIEM

#871 [7.x] [DOCS]: Add SIEM UI overview updates for 7.6 (#868)
  docs/en/siem/images/events-count.png
  docs/en/siem/images/overview-ui.png
  docs/en/siem/siem-ui.asciidoc
Labels: backport

#872 [DOCS][SIEM] Add SIEM UI overview updates for 7.6 (#868) (#871)
  docs/en/siem/images/events-count.png
  docs/en/siem/images/overview-ui.png
  docs/en/siem/siem-ui.asciidoc
Labels: backport, v7.6.0

#873 [Docs][SIEM]Updates for Detections configuration requirements and errors
  docs/en/siem/detection-engine-intro.asciidoc
  docs/en/siem/installation.asciidoc
  docs/en/siem/privileges-api-overview.asciidoc
Labels: v7.6.0

#876 [7.x] [Docs][SIEM]Updates for Detections configuration requirements and errors (#873)
  docs/en/siem/detection-engine-intro.asciidoc
  docs/en/siem/installation.asciidoc
  docs/en/siem/privileges-api-overview.asciidoc
Labels: backport

#877 [7.6] [Docs][SIEM]Updates for Detections configuration requirements and errors (#873)
  docs/en/siem/detection-engine-intro.asciidoc
  docs/en/siem/installation.asciidoc
  docs/en/siem/privileges-api-overview.asciidoc
Labels: backport

#824 [DOCS] Augments list of machine learning privileges
  docs/en/stack/ml/setup.asciidoc
Labels: :ml, v7.5.3, v7.6.0, v7.7.0, v8.0.0

#879 [DOCS] Adds DFA limitation regarding feature importance
  docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
Labels: :ml, v7.6.1, v7.7.0, v8.0.0

#880 [DOCS] Adds Further readings section to the lang ident docs
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
Labels: :ml, v7.6.1, v7.7.0, v8.0.0

#882 [Docs][SIEM] Add https requirement to detections
  docs/en/siem/detection-engine-intro.asciidoc
Labels: v7.6.0

#886 [7.x] [Docs][SIEM] Add https requirement to detections (#882)
  docs/en/siem/detection-engine-intro.asciidoc
Labels: backport

#887 [7.6] [Docs][SIEM] Add https requirement to detections (#882)
  docs/en/siem/detection-engine-intro.asciidoc
Labels: backport

#881 [DOCS] Clarify feature importance values
  docs/en/stack/ml/shared-ml-concepts.asciidoc
Labels: :ml, v7.6.1, v7.7.0, v8.0.0

#878 [DOCS] Remove cluster privilege requirement
  docs/en/stack/ml/setup.asciidoc
Labels: :ml, v7.7.0, v8.0.0

#884 [DOCS] Makes the DFA limitations section more succinct
  docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
Labels: :ml, v7.6.1, v7.7.0, v8.0.0

#890 [DOCS] Refines DFA memory limitation
  docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
Labels: :ml, v7.6.1, v7.7.0, v8.0.0

#891 [DOCS] Adds ML limitation for frozen indices
  docs/en/stack/ml/anomaly-detection/limitations.asciidoc
Labels: :ml, v6.8.7, v7.5.3, v7.6.1, v7.7.0, v8.0.0

#892 [DOCS] Adds class_score to the classification example
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
Labels: :ml, v7.6.1, v7.7.0, v8.0.0

#885 [DOCS] Adds section to the classification docs that helps interpret results
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
Labels: :ml, v7.6.1, v7.7.0, v8.0.0

#874 [Docs][SIEM] Adds tuning detection rules section
  docs/en/siem/detection-engine-intro.asciidoc
  docs/en/siem/images/edit-dect-rule-filter.png
  docs/en/siem/images/edit-dect-rule-query.png
  docs/en/siem/images/edit-dect-rule.png
  docs/en/siem/index.asciidoc
  docs/en/siem/prebuilt-rules-reference.asciidoc
  docs/en/siem/rule-details/ssh-secure-shell-to-the-internet.asciidoc
  docs/en/siem/rule-details/unusual-parent-child-relationship-.asciidoc
  docs/en/siem/rule-details/unusual-process-network-connection.asciidoc
  docs/en/siem/rules-ui-create.asciidoc
  docs/en/siem/tune-rule-signals.asciidoc
Labels: v7.6.0

#893 [7.x] [Docs][SIEM] Adds tuning detection rules section (#874)
  docs/en/siem/detection-engine-intro.asciidoc
  docs/en/siem/images/edit-dect-rule-filter.png
  docs/en/siem/images/edit-dect-rule-query.png
  docs/en/siem/images/edit-dect-rule.png
  docs/en/siem/index.asciidoc
  docs/en/siem/prebuilt-rules-reference.asciidoc
  docs/en/siem/rule-details/ssh-secure-shell-to-the-internet.asciidoc
  docs/en/siem/rule-details/unusual-parent-child-relationship-.asciidoc
  docs/en/siem/rule-details/unusual-process-network-connection.asciidoc
  docs/en/siem/rules-ui-create.asciidoc
  docs/en/siem/tune-rule-signals.asciidoc
Labels: backport

#894 [7.6] [Docs][SIEM] Adds tuning detection rules section (#874)
  docs/en/siem/detection-engine-intro.asciidoc
  docs/en/siem/images/edit-dect-rule-filter.png
  docs/en/siem/images/edit-dect-rule-query.png
  docs/en/siem/images/edit-dect-rule.png
  docs/en/siem/index.asciidoc
  docs/en/siem/prebuilt-rules-reference.asciidoc
  docs/en/siem/rule-details/ssh-secure-shell-to-the-internet.asciidoc
  docs/en/siem/rule-details/unusual-parent-child-relationship-.asciidoc
  docs/en/siem/rule-details/unusual-process-network-connection.asciidoc
  docs/en/siem/rules-ui-create.asciidoc
  docs/en/siem/tune-rule-signals.asciidoc
Labels: backport

#889 [DOCS] Adds feature influence and importance to Glossary
  docs/en/glossary/glossary.asciidoc
Labels: :ml, v8.0.0

#896 [7.x] [DOCS][Endpoint]: Add temp Endpoint Docs Home (#895)
  docs/en/endpoint/images/help-button.png
  docs/en/endpoint/index.asciidoc
Labels: backport

#897 [7.6] [DOCS][Endpoint]: Add temp Endpoint Docs Home (#895)
  docs/en/endpoint/images/help-button.png
  docs/en/endpoint/index.asciidoc
Labels: backport

#899 [7.x] [DOCS]: Fix endpoint image (#898)
  docs/en/endpoint/index.asciidoc
Labels: backport

#900 [7.6] [DOCS]: Fix endpoint image (#898)
  docs/en/endpoint/index.asciidoc
Labels: backport

#843 [DOCS] Adds a page that lists the modules with OOTB ML jobs
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
Labels: :ml, v7.5.3, v7.6.0, v7.7.0, v8.0.0

#904 [DOCS] Fine-tunes monitored activity log types in OOTB ML jobs docs
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
Labels: :ml, v7.5.3, v7.6.1, v7.7.0, v8.0.0

#905 [DOCS] Adds ML related blog posts to the anomaly detection examples page
  docs/en/stack/ml/anomaly-detection/examples.asciidoc
Labels: :ml, v7.6.1, v7.7.0, v8.0.0

#906 [DOCS] Reorganizes the OOTB SIEM jobs by agent type
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
Labels: :ml, v7.5.3, v7.6.1, v7.7.0, v8.0.0

#909 [DOCS] Renames OOTB jobs page and separates the categories to individual pages
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
Labels: :ml, v7.5.3, v7.6.1, v7.7.0, v8.0.0

#910 [Docs][SIEM]Corrects tuning prebuilt rules section title
  docs/en/siem/tune-rule-signals.asciidoc
Labels: backport, v7.6.0, v7.6.1, v8.0.0

#911 [7.x] corrects tuning prebuilt rules section title (#910)
  docs/en/siem/tune-rule-signals.asciidoc
Labels: backport

#912 [7.6] corrects tuning prebuilt rules section title (#910)
  docs/en/siem/tune-rule-signals.asciidoc
Labels: backport

#901 Switch to standard ESS trial links
  docs/en/getting-started/get-started-stack.asciidoc
  docs/en/install-upgrade/installing-stack.asciidoc
  docs/en/logs/logs-installation.asciidoc
  docs/en/metrics/installation.asciidoc
  docs/en/siem/installation.asciidoc
  docs/en/siem/machine-learning.asciidoc
  docs/en/stack/ml/setup.asciidoc
Labels: v6.8.7, v7.5.3, v7.6.1, v7.7.0, v8.0.0

#908 [Docs][SIEM]Removes winlogbeat from the suspicious_login_activity_ecs ml job description
  docs/en/siem/machine-learning.asciidoc
Labels: needs_backport, v7.6.0

#914 [7.6] removes winlogbeat from linux ml job (#908)
  docs/en/siem/machine-learning.asciidoc
Labels: backport

#913 [7.x] removes winlogbeat from linux ml job (#908)
  docs/en/siem/machine-learning.asciidoc
Labels: backport

#888 [DOCS] Adds influencer to Stack glossary
  docs/en/glossary/glossary.asciidoc
  docs/en/stack/ml/anomaly-detection/influencers.asciidoc
Labels: :ml, v7.6.1, v7.7.0, v8.0.0

#916 [DOCS] Adds ML related blog posts to the DFA examples page
  docs/en/stack/ml/df-analytics/examples.asciidoc
Labels: :ml, v7.6.1, v7.7.0, v8.0.0
