Repository elastic/stack-docs, pull requests merged in 2020-11, with the labels that each got.

#1435 docs: change APM to Observability highlights
  docs/en/install-upgrade/highlights.asciidoc
  docs/en/install-upgrade/index.asciidoc
  docs/en/install-upgrade/redirects.asciidoc
Labels: v7.10.0

#1436 [7.x] docs: change APM to Observability (#1435)
  docs/en/install-upgrade/highlights.asciidoc
  docs/en/install-upgrade/index.asciidoc
  docs/en/install-upgrade/redirects.asciidoc
Labels: backport

#1437 [7.10] docs: change APM to Observability (#1435)
  docs/en/install-upgrade/highlights.asciidoc
  docs/en/install-upgrade/index.asciidoc
  docs/en/install-upgrade/redirects.asciidoc
Labels: backport

#1438 [7.10] docs: uncomment APM breaking changes
  docs/en/install-upgrade/breaking.asciidoc
Labels: v7.10.0

#1440 Redirect Beats highlights to the observability "what's new" topic
  docs/en/install-upgrade/highlights.asciidoc
  docs/en/install-upgrade/redirects.asciidoc
Labels: v7.10.0

#1441 [7.x] Redirect Beats highlights to the observability what's new topic (#1440)
  docs/en/install-upgrade/highlights.asciidoc
  docs/en/install-upgrade/redirects.asciidoc
Labels: backport

#1442 [7.10] Redirect Beats highlights to the observability what's new topic (#1440)
  docs/en/install-upgrade/highlights.asciidoc
  docs/en/install-upgrade/redirects.asciidoc
Labels: backport

#1443 Add data tier defs to glossary
  docs/en/glossary/glossary.asciidoc
Labels: v8.0.0

#1444 Remove coming tags
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.10.0

#1445 [DOCS] Adds scroll_size related recommendation to AD at scale
  docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
Labels: :ml, v7.10.1, v7.11, v7.9.4, v8.0.0

#1446 [7.x] [DOCS] Adds scroll_size related recommendation to AD at scale (#1445)
  docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
Labels: :ml, backport, v7.11

#1447 [7.10] [DOCS] Adds scroll_size related recommendation to AD at scale (#1445)
  docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
Labels: :ml, backport, v7.10.0

#1448 [7.9] [DOCS] Adds scroll_size related recommendation to AD at scale (#1445)
  docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
Labels: :ml, backport, v7.9.4

#1449 [DOCS] Adds chunking_config recommendation to AD at scale
  docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
Labels: :ml, v7.10.1, v7.11, v7.9.4, v8.0.0

#1450 [7.x] [DOCS] Adds chunking_config recommendation to AD at scale (#1449)
  docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
Labels: :ml, backport, v7.11

#1451 [7.10] [DOCS] Adds chunking_config recommendation to AD at scale (#1449)
  docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
Labels: :ml, backport, v7.10.1

#1452 [7.9] [DOCS] Adds chunking_config recommendation to AD at scale (#1449)
  docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
Labels: :ml, backport, v7.9.4

#1456 [DOCS] Fine-tunes scroll_size related recommendation in AD at scale
  docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
Labels: :ml, v7.10.1, v7.11, v7.9.4, v8.0.0

#1457 [7.x] [DOCS] Fine-tunes scroll_size related recommendation in AD at scale. (#1456)
  docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
Labels: :ml, backport, v7.11

#1458 [7.10] [DOCS] Fine-tunes scroll_size related recommendation in AD at scale. (#1456)
  docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
Labels: :ml, backport, v7.10.1

#1459 [7.9] [DOCS] Fine-tunes scroll_size related recommendation in AD at scale. (#1456)
  docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
Labels: :ml, backport, v7.9.4

#1454 [DOCS] Refreshes and removes screenshots from regression example
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-regression-job-1.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-job-2.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-job-3.jpg
Labels: :ml, v7.10.1, v7.11, v8.0.0

#1460 [7.x][DOCS] Refreshes and removes screenshots from regression example (#1454)
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-regression-job-1.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-job-2.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-job-3.jpg
Labels: backport

#1461 [7.10][DOCS] Refreshes and removes screenshots from regression example (#1454)
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-regression-job-1.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-job-2.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-job-3.jpg
Labels: backport

#1453 [DOCS] Clarify machine learning setup
  docs/en/stack/ml/setup.asciidoc
Labels: :ml, v7.10.1, v7.11, v8.0.0

#1462 [7.x][DOCS] ML setup clarifications (#1453)
  docs/en/stack/ml/setup.asciidoc
Labels: backport

#1463 [7.10][DOCS] ML setup clarifications (#1453)
  docs/en/stack/ml/setup.asciidoc
Labels: backport

#1455 [DOCS] Removes classification screenshots; adds tip
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-classification-job-2.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-job-3.jpg
Labels: :ml, v7.11, v8.0.0

#1465 [7.x][DOCS] Removes classification screenshots; adds tip (#1455)
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-classification-job-2.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-job-3.jpg
Labels: backport

#1464 [DOCS] Adds screenshot to anomaly detection jobs docs
  docs/en/stack/ml/anomaly-detection/images/ml-single-metric-job-summary.jpg
  docs/en/stack/ml/anomaly-detection/ml-jobs.asciidoc
Labels: :ml, v7.10.1, v7.11, v8.0.0

#1466 [7.x] [DOCS] Adds screenshot to anomaly detection jobs docs. (#1464)
  docs/en/stack/ml/anomaly-detection/images/ml-single-metric-job-summary.jpg
  docs/en/stack/ml/anomaly-detection/ml-jobs.asciidoc
Labels: :ml, backport, v7.11

#1467 [7.10] [DOCS] Adds screenshot to anomaly detection jobs docs. (#1464)
  docs/en/stack/ml/anomaly-detection/images/ml-single-metric-job-summary.jpg
  docs/en/stack/ml/anomaly-detection/ml-jobs.asciidoc
Labels: :ml, backport, v7.10.0

#1468 [7.9] [DOCS] Adds screenshot to anomaly detection jobs docs. (#1464)
  docs/en/stack/ml/anomaly-detection/images/ml-single-metric-job-summary.jpg
  docs/en/stack/ml/anomaly-detection/ml-jobs.asciidoc
Labels: :ml, backport, v7.9.4

#1469 [DOCS] Augment feature importance details for classification
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-classification-decision-plot.png
  docs/en/stack/ml/df-analytics/images/flights-classification-importance.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-decision-plot.png
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
Labels: :ml, v7.11, v8.0.0

#1472 [7.x][DOCS] Augment feature importance details for classification (#1469)
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-classification-decision-plot.png
  docs/en/stack/ml/df-analytics/images/flights-classification-importance.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-decision-plot.png
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
Labels: backport

#1471 [DOCS] Reviews anomaly detection limitations
  docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-overview.asciidoc
Labels: :ml, v7.10.1, v7.11, v8.0.0

#1475 [7.10] [DOCS] Reviews anomaly detection limitations (#1471)
  docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-overview.asciidoc
Labels: :ml, backport, v7.10.1

#1474 [7.x] [DOCS] Reviews anomaly detection limitations (#1471)
  docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-overview.asciidoc
Labels: :ml, backport, v7.11
