Repository elastic/stack-docs, pull requests merged in 2020-09, with the labels that each got.

#1349 docs: add Observability terms to glossary
  docs/en/glossary/glossary.asciidoc
Labels: v7.9.0

#1350 Adjust ML mappings known issue
  docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
Labels: :ml, v7.10.0, v7.9.1

#1353 [DOCS] Adds Working with anomaly detection at scale to ML AD docs
  docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
Labels: :ml, v7.10.0, v7.9.1, v8.0.0

#1354 [7.x] [DOCS] Adds Working with anomaly detection at scale to ML AD docs (#1353)
  docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
Labels: :ml, backport, v7.10.0

#1355 [7.9] [DOCS] Adds Working with anomaly detection at scale to ML AD docs (#1353)
  docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
Labels: :ml, backport, v7.9.1

#1357 [7.x] [DOCS] Adds further info to foreceast section in AD at scale. (#1356)
  docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
Labels: :ml, backport, v7.10.0

#1358 [7.9] [DOCS] Adds further info to foreceast section in AD at scale. (#1356)
  docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
Labels: :ml, backport, v7.9.1

#1360 [DOCS] Adds feature importance regression example
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-regression-details.png
  docs/en/stack/ml/df-analytics/images/flights-regression-importance.png
  docs/en/stack/ml/df-analytics/images/flights-regression-job-1.png
  docs/en/stack/ml/df-analytics/images/flights-regression-job-3.png
  docs/en/stack/ml/df-analytics/images/flights-regression-results.png
Labels: :ml, v7.10.0, v8.0.0

#1361 [7.x][DOCS] Adds feature importance regression example (#1360)
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-regression-details.png
  docs/en/stack/ml/df-analytics/images/flights-regression-importance.png
  docs/en/stack/ml/df-analytics/images/flights-regression-job-1.png
  docs/en/stack/ml/df-analytics/images/flights-regression-job-3.png
  docs/en/stack/ml/df-analytics/images/flights-regression-results.png
Labels: backport

#1362 [DOCS] Updates list of data frame analytics APIs
  docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
Labels: :ml, v7.10.0, v7.9.2, v8.0.0

#1365 [DOCS] Adds classification AUC ROC metric description
  docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
Labels: :ml, v7.10.0, v8.0.0

#1367 [7.x] [DOCS] Adds classification AUC ROC metric description (#1365)
  docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
Labels: :ml, backport, v7.10.0

#1369 [DOCS] Feature importance clarification
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
Labels: :ml, v7.10.0, v7.7.2, v7.8.2, v7.9.2, v8.0.0

#1368 [DOCS] Fix classification score details in example
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
Labels: :ml, v7.10.0, v7.7.2, v7.8.2, v7.9.2, v8.0.0

#1371 [DOCS] Changes experimental to beta in DFA documentation
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/dfa-outlier-detection.asciidoc
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/hyperparameters.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-phases.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-encoding.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
  docs/en/stack/ml/df-analytics/ml-inference.asciidoc
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
  docs/en/stack/ml/df-analytics/ml-supervised-workflow.asciidoc
Labels: :ml, v7.10.0, v8.0.0

#1373 [7.x] [DOCS] Changes experimental to beta in DFA documentation. (#1371)
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/dfa-outlier-detection.asciidoc
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/hyperparameters.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-phases.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-encoding.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
  docs/en/stack/ml/df-analytics/ml-inference.asciidoc
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
  docs/en/stack/ml/df-analytics/ml-supervised-workflow.asciidoc
Labels: backport

#1375 [DOCS] Changes beta to experimental in DFA documentation
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/dfa-outlier-detection.asciidoc
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/dfanalytics-examples.asciidoc
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/hyperparameters.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-phases.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-encoding.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
  docs/en/stack/ml/df-analytics/ml-inference.asciidoc
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
  docs/en/stack/ml/df-analytics/ml-supervised-workflow.asciidoc
Labels: :ml, v7.10.0, v8.0.0

#1376 [7.x][DOCS] Changes beta to experimental in DFA documentation (#1375)
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/dfa-outlier-detection.asciidoc
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/dfanalytics-examples.asciidoc
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/hyperparameters.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-phases.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-encoding.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
  docs/en/stack/ml/df-analytics/ml-inference.asciidoc
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
  docs/en/stack/ml/df-analytics/ml-supervised-workflow.asciidoc
Labels: backport

#1374 [DOCS] Clarify impact of objective on class scores
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/images/confusion-matrix-binary-accuracy.jpg
  docs/en/stack/ml/df-analytics/images/confusion-matrix-multiclass-recall.jpg
Labels: :ml, v7.10.0, v8.0.0

#1377 [7.x][DOCS] Clarify impact of objective on class scores (#1374)
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/images/confusion-matrix-binary-accuracy.jpg
  docs/en/stack/ml/df-analytics/images/confusion-matrix-multiclass-recall.jpg
Labels: backport

#1370 [DOCS] Adds DFA limitation item about number of training documents
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
Labels: :ml, v7.10.0, v7.9.2, v8.0.0

#1381 [7.9] [DOCS] Adds DFA limitation item about number of training documents (#1370)
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
Labels: backport

#1380 [7.x] [DOCS] Adds DFA limitation item about number of training documents (#1370)
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
Labels: backport

#1379 [DOCS] Add total feature importance to regression example
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-regression-total-importance.png
Labels: :ml, v7.10.0, v8.0.0

#1378 [DOCS] Add total feature importance to overview
  docs/en/stack/ml/df-analytics/images/flights-regression-decision-plot.png
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
Labels: :ml, v7.10.0, v8.0.0

#1382 [DOCS] Add total feature importance to classification example
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/images/diamonds-classification-total-importance.png
  docs/en/stack/ml/df-analytics/images/flights-classification-details.png
  docs/en/stack/ml/df-analytics/images/flights-classification-evaluation.png
  docs/en/stack/ml/df-analytics/images/flights-classification-job-3.png
  docs/en/stack/ml/df-analytics/images/flights-classification-results.png
  docs/en/stack/ml/df-analytics/images/flights-classification-total-importance.png
  docs/en/stack/ml/df-analytics/images/flights-regression-total-importance.png
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
Labels: :ml, v7.10.0, v8.0.0

#1385 [7.x][DOCS] Add total feature importance to classification example (#1382)
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/images/diamonds-classification-total-importance.png
  docs/en/stack/ml/df-analytics/images/flights-classification-details.png
  docs/en/stack/ml/df-analytics/images/flights-classification-evaluation.png
  docs/en/stack/ml/df-analytics/images/flights-classification-job-3.png
  docs/en/stack/ml/df-analytics/images/flights-classification-results.png
  docs/en/stack/ml/df-analytics/images/flights-classification-total-importance.png
  docs/en/stack/ml/df-analytics/images/flights-regression-total-importance.png
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
Labels: backport

#1383 [DOCS] Add regression evaluation screenshot
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-regression-evaluation.png
  docs/en/stack/ml/df-analytics/images/flights-regression-results.png
Labels: :ml, v7.10.0, v8.0.0

#1386 [7.x][DOCS] Add regression evaluation screenshot (#1383)
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-regression-evaluation.png
  docs/en/stack/ml/df-analytics/images/flights-regression-results.png
Labels: backport

#1389 [7.9] docs: update apm include (#1387)
  docs/en/install-upgrade/highlights.asciidoc
Labels: backport

#1388 [7.x] docs: update apm include (#1387)
  docs/en/install-upgrade/highlights.asciidoc
Labels: backport
