Repository elastic/stack-docs, pull requests merged in 2020-12, with the labels that each got.

#1478 [DOCS] Refresh screenshots for prediction probability
  docs/en/stack/ml/df-analytics/images/flights-classification-decision-plot.png
  docs/en/stack/ml/df-analytics/images/flights-classification-details.png
  docs/en/stack/ml/df-analytics/images/flights-classification-importance.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-importance.png
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
Labels: :ml, v7.11, v8.0.0

#1439 [DOCS] Adds Moving trained models between clusters to docs
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Labels: :ml, v7.10.1, v7.11, v8.0.0

#1480 [7.x] [DOCS] Adds Moving trained models between clusters to docs (#1439)
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Labels: :ml, backport, v7.11

#1482 [DOCS] Fixes section level in Trained models docs
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Labels: :ml, v7.11, v8.0.0

#1483 [7.x] [DOCS] Fixes section level in Trained models docs. (#1482)
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Labels: :ml, backport, v7.11

#1477 [DOCS] Expands supplied configurations docs
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
Labels: :ml, v7.10.1, v7.11, v8.0.0

#1484 [7.x] [DOCS] Expands supplied configurations docs (#1477)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
Labels: :ml, backport, v7.11

#1485 [7.10] [DOCS] Expands supplied configurations docs (#1477)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
Labels: :ml, backport, v7.10.1

#1479 [7.x][DOCS] Refresh screenshots for prediction probability (#1478)
  docs/en/stack/ml/df-analytics/images/flights-classification-decision-plot.png
  docs/en/stack/ml/df-analytics/images/flights-classification-details.png
  docs/en/stack/ml/df-analytics/images/flights-classification-importance.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-importance.png
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
Labels: backport

#1486 [DOCS] Fixes API quick reference for trained models
  docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
Labels: :ml, v7.10.1, v7.11, v8.0.0

#1487 [7.x] [DOCS] Fixes API quick reference for trained models (#1486)
  docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
Labels: :ml, backport, v7.11

#1488 [7.10] [DOCS] Fixes API quick reference for trained models (#1486)
  docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
Labels: :ml, backport, v7.10.1

#1489 [DOCS] Fixes a typo in language identification docs
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
Labels: :ml, v7.10.1, v7.11, v7.7.2, v7.8.2, v7.9.4, v8.0.0

#1490 [7.x] [DOCS] Fixes a typo in language identification docs. (#1489)
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
Labels: :ml, backport, v7.11

#1491 [7.10] [DOCS] Fixes a typo in language identification docs. (#1489)
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
Labels: :ml, backport, v7.10.1

#1492 [7.9] [DOCS] Fixes a typo in language identification docs. (#1489)
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
Labels: :ml, backport, v7.9.4

#1493 [7.8] [DOCS] Fixes a typo in language identification docs. (#1489)
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
Labels: :ml, backport, v7.8.2

#1494 [7.7] [DOCS] Fixes a typo in language identification docs. (#1489)
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
Labels: :ml, backport, v7.7.2

#1496 [7.x] [DOCS] Fixes comment block on trained models page. (#1495)
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Labels: :ml, backport, v7.11

#1372 [DOCS] Adds runtime field limitation to AD limitations
  docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
Labels: :ml, v8.0.0

#1497 [7.x] [DOCS] Adds runtime field limitation to AD limitations (#1372)
  docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
Labels: :ml, backport, v7.11

#1499 [DOCS] Deprecate anomaly detection post data endpoint
  docs/en/glossary/glossary.asciidoc
  docs/en/stack/ml/anomaly-detection/create-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-datafeeds.asciidoc
  docs/en/stack/ml/get-started/ml-gs-next.asciidoc
Labels: :ml, v7.11, v8.0.0

#1500 [7.x][DOCS] Deprecate anomaly detection post data endpoint (#1499)
  docs/en/stack/ml/anomaly-detection/create-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-datafeeds.asciidoc
  docs/en/stack/ml/get-started/ml-gs-next.asciidoc
Labels: backport

#1498 [DOCS] Updates guide to exporting/importing models
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Labels: :ml, v7.11, v7.12, v8.0.0

#1501 [7.x][DOCS] Updates guide to exporting/importing models (#1498)
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Labels: backport

#1502 [7.11][DOCS] Updates guide to exporting/importing models (#1498)
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Labels: backport

#1470 [DOCS] Add machine learning overview to tutorial
  docs/en/stack/ml/get-started/ml-getting-started.asciidoc
Labels: :ml, v7.11, v8.0.0

#1508 [7.x][DOCS] Add machine learning overview to tutorial (#1470)
  docs/en/stack/ml/get-started/ml-getting-started.asciidoc
Labels: backport

#1509 [7.11][DOCS] Add machine learning overview to tutorial (#1470)
  docs/en/stack/ml/get-started/ml-getting-started.asciidoc
Labels: backport
