Repository elastic/stack-docs, pull requests merged in 2020-10, with the labels that each got.

#1384 [DOCS] Adds limitation item about restarting DFA job after upgrade
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
Labels: :ml, v7.10.0, v8.0.0

#1392 [7.x] [DOCS] Adds limitation item about restarting DFA job after upgrade (#1384)
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
Labels: :ml, backport, v7.10.0

#1363 [DOCS] Add metadata and discovery analysis jobs for security integration
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Labels: :ml, v7.10.0, v8.0.0

#1393 [7.x][DOCS] Add metadata and discovery analysis jobs
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Labels: backport

#1391 [DOCS] Add concept of trained models
  docs/en/stack/ml/df-analytics/images/trained-model-management.png
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-concepts.asciidoc
  docs/en/stack/ml/df-analytics/ml-inference.asciidoc
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
  docs/en/stack/ml/redirects.asciidoc
Labels: :ml, v7.10.0, v8.0.0

#1394 [DOCS] Adds data frame analytics at scale page to the ML DFA docs
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-scale.asciidoc
Labels: :ml, v7.10.0, v7.9.2, v8.0.0

#1395 [7.x] [DOCS] Adds data frame analytics at scale page to the ML DFA docs (#1394)
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-scale.asciidoc
Labels: :ml, backport, v7.10.0

#1396 [7.9] [DOCS] Adds data frame analytics at scale page to the ML DFA docs (#1394)
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-scale.asciidoc
Labels: :ml, backport, v7.9.2

#1366 [DOCS] Adds Metrics AD configurations to OOTB jobs
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
Labels: :ml, v7.10.0, v8.0.0

#1400 [7.10] [DOCS] Adds Metrics AD configurations to OOTB jobs (#1366)
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
Labels: :ml, backport, v7.10.0

#1399 [7.x] [DOCS] Adds Metrics AD configurations to OOTB jobs (#1366)
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
Labels: :ml, backport, v7.11

#1402 [DOCS] Changes links in OOTB job descriptions
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
Labels: :ml, v7.10.0, v7.11, v8.0.0

#1403 [7.x][DOCS] Remove links from OOTB jobs
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
Labels: v7.10.0, v7.11

#1398 [DOCS] Adds MSLE and Huber evaluation metrics to conceptual docs
  docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
Labels: v7.10.0, v7.11, v7.9.2, v8.0.0

#1405 [7.x] [DOCS] Adds MSLE and Huber evaluation metrics to conceptual docs (#1398)
  docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
Labels: :ml, backport, v7.11

#1406 [7.10] [DOCS] Adds MSLE and Huber evaluation metrics to conceptual docs (#1398)
  docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
Labels: :ml, backport, v7.10.0

#1407 [7.9] [DOCS] Adds MSLE and Huber evaluation metrics to conceptual docs (#1398)
  docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
Labels: :ml, backport, v7.9.2

#1401 [DOCS] Updates screenshots in regression and classification examples
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-classification-job-1.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-job-1.png
  docs/en/stack/ml/df-analytics/images/flights-classification-job-2.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-job-2.png
  docs/en/stack/ml/df-analytics/images/flights-classification-job-3.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-job-3.png
  docs/en/stack/ml/df-analytics/images/flights-classification-results.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-results.png
  docs/en/stack/ml/df-analytics/images/flights-classification-total-importance.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-total-importance.png
  docs/en/stack/ml/df-analytics/images/flights-regression-details.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-details.png
  docs/en/stack/ml/df-analytics/images/flights-regression-evaluation.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-evaluation.png
  docs/en/stack/ml/df-analytics/images/flights-regression-job-1.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-job-1.png
  docs/en/stack/ml/df-analytics/images/flights-regression-job-2.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-job-2.png
  docs/en/stack/ml/df-analytics/images/flights-regression-job-3.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-job-3.png
  docs/en/stack/ml/df-analytics/images/flights-regression-results.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-results.png
  docs/en/stack/ml/df-analytics/images/flights-regression-total-importance.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-total-importance.png
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
Labels: :ml, v7.10.0, v7.11, v8.0.0

#1410 [7.x] [DOCS] Updates screenshots in regression and classification examples (#1401)
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-classification-job-1.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-job-1.png
  docs/en/stack/ml/df-analytics/images/flights-classification-job-2.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-job-2.png
  docs/en/stack/ml/df-analytics/images/flights-classification-job-3.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-job-3.png
  docs/en/stack/ml/df-analytics/images/flights-classification-results.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-results.png
  docs/en/stack/ml/df-analytics/images/flights-classification-total-importance.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-total-importance.png
  docs/en/stack/ml/df-analytics/images/flights-regression-details.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-details.png
  docs/en/stack/ml/df-analytics/images/flights-regression-evaluation.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-evaluation.png
  docs/en/stack/ml/df-analytics/images/flights-regression-job-1.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-job-1.png
  docs/en/stack/ml/df-analytics/images/flights-regression-job-2.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-job-2.png
  docs/en/stack/ml/df-analytics/images/flights-regression-job-3.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-job-3.png
  docs/en/stack/ml/df-analytics/images/flights-regression-results.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-results.png
  docs/en/stack/ml/df-analytics/images/flights-regression-total-importance.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-total-importance.png
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
Labels: :ml, backport, v7.11

#1411 [7.10] [DOCS] Updates screenshots in regression and classification examples (#1401)
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-classification-job-1.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-job-1.png
  docs/en/stack/ml/df-analytics/images/flights-classification-job-2.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-job-2.png
  docs/en/stack/ml/df-analytics/images/flights-classification-job-3.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-job-3.png
  docs/en/stack/ml/df-analytics/images/flights-classification-results.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-results.png
  docs/en/stack/ml/df-analytics/images/flights-classification-total-importance.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-total-importance.png
  docs/en/stack/ml/df-analytics/images/flights-regression-details.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-details.png
  docs/en/stack/ml/df-analytics/images/flights-regression-evaluation.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-evaluation.png
  docs/en/stack/ml/df-analytics/images/flights-regression-job-1.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-job-1.png
  docs/en/stack/ml/df-analytics/images/flights-regression-job-2.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-job-2.png
  docs/en/stack/ml/df-analytics/images/flights-regression-job-3.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-job-3.png
  docs/en/stack/ml/df-analytics/images/flights-regression-results.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-results.png
  docs/en/stack/ml/df-analytics/images/flights-regression-total-importance.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-total-importance.png
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
Labels: :ml, backport, v7.10.0

#1412 [7.x] [DOCS] Changes links in OOTB job descriptions (#1402)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
Labels: :ml, backport, v7.11

#1413 [7.10] [DOCS] Changes links in OOTB job descriptions (#1402)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
Labels: :ml, backport, v7.10.0

#1415 [DOCS] Update coming tags in Installation and Upgrade Guide
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.10.0

#1414 [DOCS] Adds link to Uptime OOTB job description
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
Labels: :ml, v7.10.0, v7.11, v8.0.0

#1416 [7.x] [DOCS] Adds link to Uptime OOTB job description. (#1414)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
Labels: :ml, backport, v7.10.0

#1417 [7.10] [DOCS] Adds link to Uptime OOTB job description. (#1414)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
Labels: :ml, backport, v7.10.0

#1422 [DOCS] Changes links in stack getting started to point to the Observability guide
  docs/en/getting-started/get-started-stack.asciidoc
Labels: v7.10.0, v7.11, v8.0.0

#1423 [7.x] [DOCS] Changes links in stack getting started to point to the Observability guide (#1422)
  docs/en/getting-started/get-started-stack.asciidoc
Labels: backport, v7.11

#1424 [7.10] [DOCS] Changes links in stack getting started to point to the Observability guide (#1422)
  docs/en/getting-started/get-started-stack.asciidoc
Labels: backport, v7.10.0

#1421 [DOCS] Refreshes confusion matrix
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-classification-evaluation.png
Labels: :ml, v7.10.1

#1425 [7.x][DOCS] Refreshes confusion matrix (#1421)
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-classification-evaluation.png
Labels: backport

#1426 [DOCS] Refreshes confusion matrix (#1421)
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-classification-evaluation.png
Labels: :ml, v7.10.0, v7.11, v8.0.0

#1420 [DOCS] Adds AUC ROC prerequisite
  docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
Labels: :ml, v7.10.0, v7.11, v8.0.0

#1408 [DOCS] Changes experimental to beta in DFA docs
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/dfa-outlier-detection.asciidoc
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/dfanalytics-examples.asciidoc
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/hyperparameters.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-phases.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-scale.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-encoding.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
  docs/en/stack/ml/df-analytics/ml-inference.asciidoc
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
  docs/en/stack/ml/df-analytics/ml-supervised-workflow.asciidoc
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Labels: :ml, v7.11, v8.0.0

#1427 [7.x] [DOCS] Changes experimental to beta in DFA docs. (#1408)
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/dfa-outlier-detection.asciidoc
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/dfanalytics-examples.asciidoc
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/hyperparameters.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-phases.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-scale.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-encoding.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
  docs/en/stack/ml/df-analytics/ml-inference.asciidoc
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
  docs/en/stack/ml/df-analytics/ml-supervised-workflow.asciidoc
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Labels: :ml, backport, v7.11

#1359 [DOCS] Add feature importance to classification example
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-classification-importance.png
Labels: :ml, v7.10.0, v7.11, v8.0.0

#1428 [7.x][DOCS] Add feature importance to classification example (#1359)
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-classification-importance.png
Labels: backport

#1429 [7.10][DOCS] Add feature importance to classification example (#1359)
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-classification-importance.png
Labels: backport
