Repository elastic/stack-docs, pull requests merged in 2020-08, with the labels that each got.

#1322 [DOCS] Adds blog links to the DFA examples page
  docs/en/stack/ml/df-analytics/dfanalytics-examples.asciidoc
Labels: :ml, v7.10.0, v7.8.2, v7.9.0, v8.0.0

#1323 [DOCS] Adds inference API links to DFA API quick reference
  docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
Labels: :ml, v7.10.0, v7.8.2, v7.9.0, v8.0.0

#1267 [DOCS] Refresh regression screenshots with histograms
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-regression-details.png
  docs/en/stack/ml/df-analytics/images/flights-regression-job-1.png
  docs/en/stack/ml/df-analytics/images/flights-regression-job-2.png
  docs/en/stack/ml/df-analytics/images/flights-regression-results.png
Labels: :ml, v7.10.0, v7.9.0, v8.0.0

#1324 [7.x][DOCS] Refresh regression screenshots with histograms (#1267)
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-regression-details.png
  docs/en/stack/ml/df-analytics/images/flights-regression-job-1.png
  docs/en/stack/ml/df-analytics/images/flights-regression-job-2.png
  docs/en/stack/ml/df-analytics/images/flights-regression-results.png
Labels: backport

#1325 [7.9][DOCS] Refresh regression screenshots with histograms (#1267)
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-regression-details.png
  docs/en/stack/ml/df-analytics/images/flights-regression-job-1.png
  docs/en/stack/ml/df-analytics/images/flights-regression-job-2.png
  docs/en/stack/ml/df-analytics/images/flights-regression-results.png
Labels: backport

#1326 [DOCS] Enables ES highlights and breaking changes in Install Upgrade Guide
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.9.0

#1313 [DOCS] Adds feature encoding documentation under Concepts
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-concepts.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-encoding.asciidoc
Labels: :ml, v7.10.0, v7.8.1, v7.9.0, v8.0.0

#1327 [DOCS] Adds inference phase to how a DFA job works section
  docs/en/stack/ml/df-analytics/ml-dfa-phases.asciidoc
Labels: :ml, v7.10.0, v7.9.0, v8.0.0

#1306 [DOCS] Adds supervised ML workflow description to DFA overview
  docs/en/stack/ml/df-analytics/images/ml-dfa-lifecycle-diagram.png
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-phases.asciidoc
  docs/en/stack/ml/df-analytics/ml-supervised-workflow.asciidoc
  docs/en/stack/ml/df-analytics/supervised-lifecycle.adoc
Labels: :ml, v7.10.0, v7.9.0, v8.0.0

#1329 [7.9] [DOCS] Adds column title to overview table
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
Labels: :ml, v7.9.0

#1328 [DOCS] Fine-tunes wording in inference phase description
  docs/en/stack/ml/df-analytics/ml-dfa-phases.asciidoc
Labels: :ml, v7.10.0, v7.9.0, v8.0.0

#1330 [DOCS] Add Kibana privileges to glossary
  docs/en/glossary/glossary.asciidoc
Labels: v8.0.0

#1331 [DOCS] Refresh classification screenshots with histograms
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-classification-details.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-details.png
  docs/en/stack/ml/df-analytics/images/flights-classification-evaluation.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-evaluation.png
  docs/en/stack/ml/df-analytics/images/flights-classification-job-1.png
  docs/en/stack/ml/df-analytics/images/flights-classification-job-2.png
  docs/en/stack/ml/df-analytics/images/flights-classification-results.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-results.png
Labels: :ml, v7.10.0, v7.9.0, v8.0.0

#1332 [7.x][DOCS] Refresh classification screenshots with histograms (#1331)
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-classification-details.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-details.png
  docs/en/stack/ml/df-analytics/images/flights-classification-evaluation.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-evaluation.png
  docs/en/stack/ml/df-analytics/images/flights-classification-job-1.png
  docs/en/stack/ml/df-analytics/images/flights-classification-job-2.png
  docs/en/stack/ml/df-analytics/images/flights-classification-results.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-results.png
Labels: backport

#1333 [7.9][DOCS] Refresh classification screenshots with histograms (#1331)
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-classification-details.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-details.png
  docs/en/stack/ml/df-analytics/images/flights-classification-evaluation.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-evaluation.png
  docs/en/stack/ml/df-analytics/images/flights-classification-job-1.png
  docs/en/stack/ml/df-analytics/images/flights-classification-job-2.png
  docs/en/stack/ml/df-analytics/images/flights-classification-results.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-results.png
Labels: backport

#1335 [DOCS] Add Kibana highlights to Install Upgrade Guide
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.9.0

#1336 [DOCS] Uncomments APM breaking changes
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.9.0

#1338 Remove coming tags and activate links
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
Labels: review, v7.9.0

#1339 [DOCS] Adds further reading section to Influencers
  docs/en/stack/ml/anomaly-detection/ml-influencers.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
Labels: :ml, v7.10.0, v7.8.2, v7.9.0, v8.0.0

#1337 [DOCS] Adds ML troubleshooting for upgrade
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
Labels: :ml, v7.9.0

#1340 [7.x][DOCS] Adds ML troubleshooting for upgrade (#1337)
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
Labels: backport

#1341 [DOCS] Removes coming tags from installation upgrade guide
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.9.0

#1345 [DOCS] Fixes typo in OOTB metricbeat jobs
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
Labels: :ml, v7.10.0, v7.9.1, v8.0.0

#1346 [7.x] [DOCS] Fixes typo in OOTB metricbeat jobs. (#1345)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
Labels: backport

#1347 [7.9] [DOCS] Fixes typo in OOTB metricbeat jobs. (#1345)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
Labels: backport

#1348 [DOCS] Modifies OOTB jobs content
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
Labels: :ml, v7.10.0, v7.9.1, v8.0.0
