Repository elastic/stack-docs, pull requests merged in 2020-05, with the labels that each got.

#1029 [7.x] [Docs][SIEM]Structure update (#1027)
  docs/en/siem/installation.asciidoc
  docs/en/siem/machine-learning.asciidoc
  docs/en/siem/overview.asciidoc
  docs/en/siem/siem-ui.asciidoc
  docs/en/siem/tune-anomaly-results.asciidoc
Labels: backport

#1030 [7.7] [Docs][SIEM]Structure update (#1027)
  docs/en/siem/installation.asciidoc
  docs/en/siem/machine-learning.asciidoc
  docs/en/siem/overview.asciidoc
  docs/en/siem/siem-ui.asciidoc
  docs/en/siem/tune-anomaly-results.asciidoc
Labels: backport

#991 Deprecate`kibana` user in favor of `kibana_system` user
  docs/en/getting-started/get-started-docker.asciidoc
Labels: v7.8.0

#1031 Deprecate kibana user in favor of kibana_system user
  docs/en/getting-started/get-started-docker.asciidoc
Labels: backport, v7.8.0

#1034 [Docs][SIEM]Adds link to postman collection example
  docs/en/siem/rules-api-overview.asciidoc
Labels: v7.6.0, v7.7.0

#1035 [7.x] adds link to postman collection example (#1034)
  docs/en/siem/rules-api-overview.asciidoc
Labels: backport

#1036 [7.7] adds link to postman collection example (#1034)
  docs/en/siem/rules-api-overview.asciidoc
Labels: backport

#1037 [7.6] adds link to postman collection example (#1034)
  docs/en/siem/rules-api-overview.asciidoc
Labels: backport

#1041 Edits to introductory section (#940)
  docs/en/getting-started/get-started-stack.asciidoc
Labels: backport

#1042 Edits to introductory section (#940)
  docs/en/getting-started/get-started-stack.asciidoc
Labels: backport

#1043 Edits to introductory section (#940)
  docs/en/getting-started/get-started-stack.asciidoc
Labels: backport

#1044 Edits to introductory section (#940)
  docs/en/getting-started/get-started-stack.asciidoc
Labels: backport

#1045 [DOCS] Update links for breaking changes
  docs/en/install-upgrade/breaking.asciidoc
Labels: v7.8.0

#1040 [Docs][SIEM]Updates prebuilt endpoint rules look back time
  docs/en/siem/rule-details/adversary-behavior-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/credential-dumping-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/credential-dumping-prevented-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/credential-manipulation-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/credential-manipulation-prevented-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/exploit-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/exploit-prevented-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/malware-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/malware-prevented-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/permission-theft-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/permission-theft-prevented-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/process-injection-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/process-injection-prevented-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/ransomware-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/ransomware-prevented-elastic-endpoint.asciidoc
Labels: v7.7.0

#1049 [7.x] updates prebuilt endpoint rules look back time (#1040)
  docs/en/siem/rule-details/adversary-behavior-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/credential-dumping-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/credential-dumping-prevented-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/credential-manipulation-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/credential-manipulation-prevented-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/exploit-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/exploit-prevented-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/malware-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/malware-prevented-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/permission-theft-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/permission-theft-prevented-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/process-injection-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/process-injection-prevented-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/ransomware-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/ransomware-prevented-elastic-endpoint.asciidoc
Labels: backport

#1050 [7.8] updates prebuilt endpoint rules look back time (#1040)
  docs/en/siem/rule-details/adversary-behavior-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/credential-dumping-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/credential-dumping-prevented-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/credential-manipulation-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/credential-manipulation-prevented-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/exploit-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/exploit-prevented-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/malware-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/malware-prevented-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/permission-theft-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/permission-theft-prevented-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/process-injection-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/process-injection-prevented-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/ransomware-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/ransomware-prevented-elastic-endpoint.asciidoc
Labels: backport

#1051 [7.7] updates prebuilt endpoint rules look back time (#1040)
  docs/en/siem/rule-details/adversary-behavior-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/credential-dumping-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/credential-dumping-prevented-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/credential-manipulation-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/credential-manipulation-prevented-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/exploit-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/exploit-prevented-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/malware-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/malware-prevented-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/permission-theft-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/permission-theft-prevented-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/process-injection-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/process-injection-prevented-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/ransomware-detected-elastic-endpoint.asciidoc
  docs/en/siem/rule-details/ransomware-prevented-elastic-endpoint.asciidoc
Labels: backport

#1028 [DOCS] Amends the footnotes in the ML book
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
Labels: :ml, v7.7.1, v7.8.0, v8.0.0

#1039 [Docs][SIEM]Threat hunting ehancements
  docs/en/siem/images/siem-click-swipe.png
  docs/en/siem/images/siem-field-highlight.png
  docs/en/siem/siem-ui.asciidoc
Labels: v7.8.0

#1054 [7.x] [Docs][SIEM]Threat hunting ehancements (#1039)
  docs/en/siem/images/siem-click-swipe.png
  docs/en/siem/images/siem-field-highlight.png
  docs/en/siem/siem-ui.asciidoc
Labels: backport

#1055 [7.8] [Docs][SIEM]Threat hunting ehancements (#1039)
  docs/en/siem/images/siem-click-swipe.png
  docs/en/siem/images/siem-field-highlight.png
  docs/en/siem/siem-ui.asciidoc
Labels: backport

#1046 [DOCS] Fix link to Kibana breaking changes
  docs/en/install-upgrade/breaking.asciidoc
Labels: v7.7.1

#1038 [DOCS] Expands the analyzing phase with the analysis specific sub-phases
  docs/en/stack/ml/df-analytics/ml-dfa-phases.asciidoc
Labels: :ml, v7.8.0, v8.0.0

#1056 [DOCS] Clarify enabling Kibana on hosted Elasticsearch Service
  docs/en/getting-started/get-started-stack.asciidoc
Labels: v7.6.0, v7.7.0, v7.8.0

#1060 [7.6] [DOCS] Clarify enabling Kibana on hosted Elasticsearch Service (#1056)
  docs/en/getting-started/get-started-stack.asciidoc
Labels: backport

#1059 [7.7] [DOCS] Clarify enabling Kibana on hosted Elasticsearch Service (#1056)
  docs/en/getting-started/get-started-stack.asciidoc
Labels: backport

#1058 [7.8] [DOCS] Clarify enabling Kibana on hosted Elasticsearch Service (#1056)
  docs/en/getting-started/get-started-stack.asciidoc
Labels: backport

#1057 [7.x] [DOCS] Clarify enabling Kibana on hosted Elasticsearch Service (#1056)
  docs/en/getting-started/get-started-stack.asciidoc
Labels: backport

#1047 [DOCS] Update snapshot retention details
  docs/en/stack/ml/anomaly-detection/model-snapshots.asciidoc
Labels: :ml, v7.8.0, v7.9.0, v8.0.0

#1066 [7.x] [Docs][SIEM]Adds link to beats pipeline example and corrects typo (#1065)
  docs/en/siem/cases-kbn-actions-api.asciidoc
  docs/en/siem/siem-ui.asciidoc
Labels: backport

#1067 [7.8] [Docs][SIEM]Adds link to beats pipeline example and corrects typo (#1065)
  docs/en/siem/cases-kbn-actions-api.asciidoc
  docs/en/siem/siem-ui.asciidoc
Labels: backport

#1068 [7.7] [Docs][SIEM]Adds link to beats pipeline example and corrects typo (#1065)
  docs/en/siem/cases-kbn-actions-api.asciidoc
  docs/en/siem/siem-ui.asciidoc
Labels: backport

#1074 [DOCS] Update Logs app image in Logs Monitoring doc
  docs/en/logs/images/add-data.png
  docs/en/logs/images/logs-console.png
  docs/en/logs/images/logs-monitoring-architecture.png
  docs/en/logs/logs-installation.asciidoc
  docs/en/logs/logs-overview.asciidoc
  docs/en/logs/logs-ui-intro.asciidoc
Labels: v7.7.0, v7.8.0

#1077 [7.7] [DOCS] Update Logs app image in Logs Monitoring doc (#1074)
  docs/en/logs/images/add-data.png
  docs/en/logs/images/logs-console.png
  docs/en/logs/images/logs-monitoring-architecture.png
  docs/en/logs/logs-installation.asciidoc
  docs/en/logs/logs-overview.asciidoc
  docs/en/logs/logs-ui-intro.asciidoc
Labels: backport

#1076 [7.8] [DOCS] Update Logs app image in Logs Monitoring doc (#1074)
  docs/en/logs/images/add-data.png
  docs/en/logs/images/logs-console.png
  docs/en/logs/images/logs-monitoring-architecture.png
  docs/en/logs/logs-installation.asciidoc
  docs/en/logs/logs-overview.asciidoc
  docs/en/logs/logs-ui-intro.asciidoc
Labels: backport

#1075 [7.x] [DOCS] Update Logs app image in Logs Monitoring doc (#1074)
  docs/en/logs/images/add-data.png
  docs/en/logs/images/logs-console.png
  docs/en/logs/images/logs-monitoring-architecture.png
  docs/en/logs/logs-installation.asciidoc
  docs/en/logs/logs-overview.asciidoc
  docs/en/logs/logs-ui-intro.asciidoc
Labels: backport

#1070 [DOCS] Removes [discrete] attributes from DFA docs
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/dfa-outlierdetection.asciidoc
  docs/en/stack/ml/df-analytics/evaluatedf-api.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-phases.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
  docs/en/stack/ml/df-analytics/ml-inference.asciidoc
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
Labels: :ml, v7.8.0, v7.9.0, v8.0.0

#1079 [DOCS] Removes [discrete] attributes from anomaly detection docs
  docs/en/stack/ml/anomaly-detection/buckets.asciidoc
  docs/en/stack/ml/anomaly-detection/influencers.asciidoc
Labels: :ml, v7.7.1, v7.8.0, v7.9.0, v8.0.0

#1081 [Docs][SIEM]Adds ml admin role requirement
  docs/en/siem/detections/rules-ui-create.asciidoc
Labels: v7.8.0

#1084 [7.x] adds ml admin role requirement (#1081)
  docs/en/siem/detections/rules-ui-create.asciidoc
Labels: backport

#1085 [7.8] adds ml admin role requirement (#1081)
  docs/en/siem/detections/rules-ui-create.asciidoc
Labels: backport

#1082 [DOCS] Update images in Metrics Monitoring doc
  docs/en/metrics/images/add-data.png
  docs/en/metrics/images/infra-sysmon.png
  docs/en/metrics/images/metrics-monitoring-architecture.png
  docs/en/metrics/infra-ui-intro.asciidoc
  docs/en/metrics/infrastructure-metrics.asciidoc
  docs/en/metrics/installation.asciidoc
  docs/en/metrics/metrics-overview.asciidoc
Labels: v7.7.0, v7.8.0

#1088 [7.7] [DOCS] Update images in Metrics Monitoring doc (#1082)
  docs/en/metrics/images/add-data.png
  docs/en/metrics/images/infra-sysmon.png
  docs/en/metrics/images/metrics-monitoring-architecture.png
  docs/en/metrics/infra-ui-intro.asciidoc
  docs/en/metrics/infrastructure-metrics.asciidoc
  docs/en/metrics/installation.asciidoc
  docs/en/metrics/metrics-overview.asciidoc
Labels: backport

#1087 [7.8] [DOCS] Update images in Metrics Monitoring doc (#1082)
  docs/en/metrics/images/add-data.png
  docs/en/metrics/images/infra-sysmon.png
  docs/en/metrics/images/metrics-monitoring-architecture.png
  docs/en/metrics/infra-ui-intro.asciidoc
  docs/en/metrics/infrastructure-metrics.asciidoc
  docs/en/metrics/installation.asciidoc
  docs/en/metrics/metrics-overview.asciidoc
Labels: backport

#1086 [7.x] [DOCS] Update images in Metrics Monitoring doc (#1082)
  docs/en/metrics/images/add-data.png
  docs/en/metrics/images/infra-sysmon.png
  docs/en/metrics/images/metrics-monitoring-architecture.png
  docs/en/metrics/infra-ui-intro.asciidoc
  docs/en/metrics/infrastructure-metrics.asciidoc
  docs/en/metrics/installation.asciidoc
  docs/en/metrics/metrics-overview.asciidoc
Labels: backport

#1089 [DOCS] Fix endif in Glossary
  docs/en/glossary/glossary.asciidoc
Labels: v8.0.0

#1090 [Docs][SIEM]Adds list of signal notification placeholders
  docs/en/siem/detections/api/rules-api-create.asciidoc
  docs/en/siem/detections/rules-ui-create.asciidoc
Labels: v7.7.0

#1092 [7.x] adds list of rule notifications placeholders (#1090)
  docs/en/siem/detections/api/rules-api-create.asciidoc
  docs/en/siem/detections/rules-ui-create.asciidoc
Labels: backport

#1093 [7.8] adds list of rule notifications placeholders (#1090)
  docs/en/siem/detections/api/rules-api-create.asciidoc
  docs/en/siem/detections/rules-ui-create.asciidoc
Labels: backport

#1094 [7.7] adds list of rule notifications placeholders (#1090)
  docs/en/siem/detections/api/rules-api-create.asciidoc
  docs/en/siem/detections/rules-ui-create.asciidoc
Labels: backport

#1033 [Docs][SIEM]Adds field reference list
  docs/en/siem/field-ref.asciidoc
  docs/en/siem/index.asciidoc
  docs/en/siem/installation.asciidoc
Labels: v7.7.0

#1095 [7.x] [Docs][SIEM]Adds field reference list (#1033)
  docs/en/siem/field-ref.asciidoc
  docs/en/siem/index.asciidoc
  docs/en/siem/installation.asciidoc
Labels: backport

#1096 [7.8] [Docs][SIEM]Adds field reference list (#1033)
  docs/en/siem/field-ref.asciidoc
  docs/en/siem/index.asciidoc
  docs/en/siem/installation.asciidoc
Labels: backport

#1097 [7.7] [Docs][SIEM]Adds field reference list (#1033)
  docs/en/siem/field-ref.asciidoc
  docs/en/siem/index.asciidoc
  docs/en/siem/installation.asciidoc
Labels: backport

#1091 [DOCS] Enables mathematical formulate in DFA chapter and adds markup to a formula
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/index.asciidoc
Labels: :ml, v7.7.1, v7.8.0, v7.9.0, v8.0.0

#1080 [DOCS] Adds dedicated indices section to job tips with recommendation
  docs/en/stack/ml/anomaly-detection/job-tips.asciidoc
Labels: :ml, v7.8.0, v7.9.0, v8.0.0

#1100 [DOCS] Changes link in Anomaly Detection API quick reference
  docs/en/stack/ml/anomaly-detection/api-quickref.asciidoc
Labels: :ml, v7.7.1, v7.8.0, v7.9.0, v8.0.0

#1101 [DOCS] Expands forecast limitations
  docs/en/stack/ml/anomaly-detection/limitations.asciidoc
Labels: :ml, v7.7.1, v7.8.0, v7.9.0, v8.0.0

#1104 [DOCS] Removes outdated inference related limitation item
  docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
Labels: :ml, v7.7.1, v7.8.0, v7.9.0, v8.0.0

#1110 [7.x] Fix broken link to docs about configuring beats input in Logstash
  docs/en/stack/redirects.asciidoc
Labels: needs_backport

#1106 [7.8] Remove LS steps from the stack getting started (#1099)
  docs/en/getting-started/get-started-stack.asciidoc
Labels: backport

#1108 [DOCS] Add ML CPU scheduling limitation
  docs/en/stack/ml/anomaly-detection/limitations.asciidoc
  docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
Labels: :ml, v7.8.0, v7.9.0, v8.0.0

#1105 [7.x] Remove LS steps from the stack getting started (#1099)
  docs/en/getting-started/get-started-stack.asciidoc
Labels: backport

#1062 [DOCS] Adds loss function description to regression conceptual docs
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-concepts.asciidoc
Labels: :ml, v7.8.0, v7.9.0, v8.0.0

#1114 [DOCS] Removes top-level guides section from landing page
  docs/en/stack/landing-all.asciidoc
  docs/en/stack/landing.asciidoc
Labels: WIP
