Repository elastic/stack-docs, pull requests merged in 2020-01, with the labels that each got.

#758 [DOCS] Adds inference conceptual documentation
  docs/en/stack/ml/df-analytics/ml-dfa-concepts.asciidoc
  docs/en/stack/ml/df-analytics/ml-inference.asciidoc
Labels: :ml, v7.6.0, v8.0.0

#792 [7.5][DOCS] Remove hyperparam optimization link from DFA limitations
  docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
Labels: :ml, v7.5.2

#793 [7.5][DOCS] Adds hyperparameter optimization link to limitation text
  docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
Labels: :ml, v7.5.2

#799 [DOCS] Adds redirect for license expiration details
  docs/en/stack/get-started-trial.asciidoc
  docs/en/stack/license.asciidoc
  docs/en/stack/ml/get-started-trial.asciidoc
  docs/en/stack/redirects.asciidoc
  docs/en/stack/xpack-enabling.asciidoc
  docs/en/stack/xpack-settings.asciidoc
Labels: v7.5.2, v7.6.0, v8.0.0

#797 [Metrics UI] Update docs with AWS Metricset fields
  docs/en/metrics/aws-ec2-metricset.asciidoc
  docs/en/metrics/aws-rds-metricset.asciidoc
  docs/en/metrics/aws-s3-metricset.asciidoc
  docs/en/metrics/aws-sqs-metricset.asciidoc
  docs/en/metrics/docker-metricset.asciidoc
  docs/en/metrics/host-metricset.asciidoc
  docs/en/metrics/infrastructure-metrics.asciidoc
  docs/en/metrics/kubernetes-metricset.asciidoc
Labels: Infrastructure monitoring, v7.6.0, v8.0.0

#801 [DOCS] Adds hyperparameter optimization link to a DFA limitation item text
  docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
Labels: :ml, v7.5.2, v7.6.0, v8.0.0

#791 [DOCS] Adds nested objects related inference limitation
  docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
Labels: :ml, v7.6.0, v8.0.0

#803 [DOCS] Fixes out-dated links
  docs/en/install-upgrade/upgrading-stack.asciidoc
  docs/en/stack/ml/anomaly-detection/calendars.asciidoc
  docs/en/stack/ml/anomaly-detection/datafeeds.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-multi.asciidoc
  docs/en/stack/ml/anomaly-detection/getting-started-single.asciidoc
  docs/en/stack/ml/anomaly-detection/job-tips.asciidoc
  docs/en/stack/ml/anomaly-detection/jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/limitations.asciidoc
  docs/en/stack/ml/anomaly-detection/troubleshooting.asciidoc
Labels: v7.5.2, v7.6.0, v8.0.0

#805 Deprecate kibana_user role
  docs/en/stack/ml/anomaly-detection/getting-started.asciidoc
Labels: :ml, v7.6.0, v8.0.0

#806 [DOCS] Documents imbalanced class sizes and their effect on classification
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
Labels: :ml, v7.5.2, v7.6.0, v7.7.0, v8.0.0

#812 [SIEM][Docs]Sorts list of prebuilt ml jobs
  docs/en/siem/machine-learning.asciidoc
Labels: v7.6.0

#814 [SIEM][Docs]Sorts list of prebuilt ml jobs
  docs/en/siem/machine-learning.asciidoc
Labels: v7.6.0

#815 [DOCS] Adds ML limitation for date_nanos
  docs/en/stack/ml/anomaly-detection/limitations.asciidoc
Labels: :ml, v7.0.2, v7.1.2, v7.2.2, v7.3.2, v7.4.3, v7.5.2, v7.6.0, v7.7.0, v8.0.0

#804 [DOCS] Adds categorization wizard
  docs/en/stack/ml/anomaly-detection/create-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/images/ml-create-job.jpg
Labels: :ml, v7.6.0, v8.0.0

#817 [DOCS] Adds one-liner description of classification to the overview page
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
Labels: :ml, v7.5.3, v7.6.0, v7.7.0, v8.0.0

#810 [DOCS] Augment datafeed overview
  docs/en/stack/ml/anomaly-detection/datafeeds.asciidoc
Labels: :ml, v7.5.3, v7.6.0, v7.7.0, v8.0.0

#796 [Docs][SIEM] Detection engine ui documentation
  docs/en/siem/detection-engine-intro.asciidoc
  docs/en/siem/images/about-rule-pane.png
  docs/en/siem/images/all-rules.png
  docs/en/siem/images/create-new-rule.png
  docs/en/siem/images/detection-engine.png
  docs/en/siem/images/schedule-rule.png
  docs/en/siem/index.asciidoc
  docs/en/siem/installation.asciidoc
  docs/en/siem/overview.asciidoc
  docs/en/siem/prebuilt-rule-reference.asciidoc
  docs/en/siem/rules-ui-create.asciidoc
  docs/en/siem/siem-ui.asciidoc
Labels: v7.6.0

#819 [Docs][SIEM] Detections UI
  docs/en/siem/detection-engine-intro.asciidoc
  docs/en/siem/images/about-rule-pane.png
  docs/en/siem/images/all-rules.png
  docs/en/siem/images/create-new-rule.png
  docs/en/siem/images/detection-engine.png
  docs/en/siem/images/schedule-rule.png
  docs/en/siem/index.asciidoc
  docs/en/siem/installation.asciidoc
  docs/en/siem/overview.asciidoc
  docs/en/siem/prebuilt-rule-reference.asciidoc
  docs/en/siem/rules-ui-create.asciidoc
  docs/en/siem/siem-ui.asciidoc
Labels: backport

#820 [Docs][SIEM] 7.6 Detections UI
  docs/en/siem/detection-engine-intro.asciidoc
  docs/en/siem/images/about-rule-pane.png
  docs/en/siem/images/all-rules.png
  docs/en/siem/images/create-new-rule.png
  docs/en/siem/images/detection-engine.png
  docs/en/siem/images/schedule-rule.png
  docs/en/siem/index.asciidoc
  docs/en/siem/installation.asciidoc
  docs/en/siem/overview.asciidoc
  docs/en/siem/prebuilt-rule-reference.asciidoc
  docs/en/siem/rules-ui-create.asciidoc
  docs/en/siem/siem-ui.asciidoc
Labels: backport, v7.6.0

#818 [DOCS] Adds machine learning setup page
  docs/en/stack/ml/anomaly-detection/architecture.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-concepts.asciidoc
  docs/en/stack/ml/index.asciidoc
  docs/en/stack/ml/setup.asciidoc
  docs/en/stack/redirects.asciidoc
Labels: :ml, v7.5.3, v7.6.0, v7.7.0, v8.0.0

#821 [Docs][SIEM]Adds Detections UI permission error messages
  docs/en/siem/detection-engine-intro.asciidoc
Labels: v7.6.0

#826 [Docs][SIEM] General 7.6 updates
  docs/en/siem/images/timeline-ui.png
  docs/en/siem/siem-ui.asciidoc
Labels: v7.6.0

#827 [Docs][SIEM]General 7.6 updates
  docs/en/siem/images/timeline-ui.png
  docs/en/siem/siem-ui.asciidoc
Labels: backport

#828 [Docs][SIEM]General 7.6 updates
  docs/en/siem/images/timeline-ui.png
  docs/en/siem/siem-ui.asciidoc
Labels: backport

#816 [DOCS] Adds language identification documentation to the ML DFA docs
  docs/en/stack/ml/df-analytics/examples.asciidoc
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
Labels: :ml, v7.6.0, v7.7.0, v8.0.0

#832 [DOCS] Moves forecast limitations out of overview
  docs/en/stack/ml/anomaly-detection/forecasting.asciidoc
  docs/en/stack/ml/anomaly-detection/limitations.asciidoc
Labels: :ml, v7.5.3, v7.6.0, v7.7.0, v8.0.0

#829 [DOCS] Adds one liner about inference to the DFA overview page
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
Labels: :ml, v7.6.0, v7.7.0, v8.0.0

#830 [DOCS] Adds a paragraph about language identification to the inference conceptual docs
  docs/en/stack/ml/df-analytics/ml-inference.asciidoc
Labels: :ml, v7.6.0, v7.7.0, v8.0.0
