Repository elastic/stack-docs, pull requests merged in 2020-06, with the labels that each got.

#1115 [DOCS] Adds ESS APIs to landing page
  docs/en/stack/index-landing-all.adoc
  docs/en/stack/index-landing.adoc
  docs/en/stack/index-landing.asciidoc
  docs/en/stack/landing-all.asciidoc
  docs/en/stack/landing.asciidoc
  docs/en/stack/redirects-landing.adoc
Labels: v8.0.0

#1116 [DOCS] Replace docdir attributes with root attributes
  docs/en/getting-started/index.asciidoc
  docs/en/glossary/index.asciidoc
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
  docs/en/install-upgrade/index.asciidoc
  docs/en/siem/index.asciidoc
  docs/en/stack/index-landing.asciidoc
  docs/en/stack/ml/index.asciidoc
Labels: v8.0.0

#1117 [7.x][DOCS] Replace docdir attributes with root attributes (#1116)
  docs/en/getting-started/index.asciidoc
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
  docs/en/install-upgrade/index.asciidoc
  docs/en/siem/index.asciidoc
  docs/en/stack/index.asciidoc
  docs/en/stack/ml/index.asciidoc
Labels: backport

#1118 [7.8][DOCS] Replace docdir attributes with root attributes (#1116)
  docs/en/getting-started/index.asciidoc
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
  docs/en/install-upgrade/index.asciidoc
  docs/en/siem/index.asciidoc
  docs/en/stack/index.asciidoc
  docs/en/stack/ml/index.asciidoc
Labels: backport

#1119 [7.7][DOCS] Replace docdir attributes with root attributes (#1116)
  docs/en/getting-started/index.asciidoc
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
  docs/en/install-upgrade/index.asciidoc
  docs/en/siem/index.asciidoc
  docs/en/stack/index.asciidoc
  docs/en/stack/ml/index.asciidoc
Labels: backport

#1113 [DOCS] Adds ML DFA related content to the stack landing page
  docs/en/stack/landing-all.asciidoc
  docs/en/stack/landing.asciidoc
  docs/en/stack/redirects-landing.adoc
Labels: WIP, enhancement

#1120 [DOCS] Adds transform content to landing page
  docs/en/stack/index-landing.adoc
  docs/en/stack/landing-all.asciidoc
  docs/en/stack/landing.asciidoc
  docs/en/stack/redirects-landing.adoc
Labels: WIP, v8.0.0

#1121 [DOCS] Drafts layout of Observability content
  docs/en/stack/index-landing-observability-collapsible.adoc
  docs/en/stack/index-landing-observability.adoc
  docs/en/stack/landing-all.asciidoc
  docs/en/stack/landing-observability.asciidoc
Labels: WIP

#1052 [Docs][SIEM]Updates Cases for 7.8
  docs/en/siem/cases/api/actions-api/cases-actions-api-intro.asciidoc
  docs/en/siem/cases/api/cases-api/case-api-update-connector.asciidoc
  docs/en/siem/cases/api/cases-api/cases-api-assign-connector.asciidoc
  docs/en/siem/cases/api/cases-api/cases-api-associate-sn.asciidoc
  docs/en/siem/cases/api/cases-api/cases-api-create.asciidoc
  docs/en/siem/cases/api/cases-api/cases-api-find-connectors.asciidoc
  docs/en/siem/cases/api/cases-api/cases-api-update.asciidoc
  docs/en/siem/cases/api/cases-api/cases-api.asciidoc
  docs/en/siem/cases/cases-overview.asciidoc
  docs/en/siem/cases/cases-ui-integrations.asciidoc
  docs/en/siem/cases/images/cases-ui-connector.png
  docs/en/siem/cases/images/cases-ui-open.png
  docs/en/siem/images/cases-ui-home.png
Labels: v7.8.0

#1124 [7.x] [Docs][SIEM]Updates Cases for 7.8 (#1052)
  docs/en/siem/cases/api/actions-api/cases-actions-api-intro.asciidoc
  docs/en/siem/cases/api/cases-api/case-api-update-connector.asciidoc
  docs/en/siem/cases/api/cases-api/cases-api-assign-connector.asciidoc
  docs/en/siem/cases/api/cases-api/cases-api-associate-sn.asciidoc
  docs/en/siem/cases/api/cases-api/cases-api-create.asciidoc
  docs/en/siem/cases/api/cases-api/cases-api-find-connectors.asciidoc
  docs/en/siem/cases/api/cases-api/cases-api-update.asciidoc
  docs/en/siem/cases/api/cases-api/cases-api.asciidoc
  docs/en/siem/cases/cases-overview.asciidoc
  docs/en/siem/cases/cases-ui-integrations.asciidoc
  docs/en/siem/cases/images/cases-ui-connector.png
  docs/en/siem/cases/images/cases-ui-open.png
  docs/en/siem/images/cases-ui-home.png
Labels: backport

#1125 [7.8] [Docs][SIEM]Updates Cases for 7.8 (#1052)
  docs/en/siem/cases/api/actions-api/cases-actions-api-intro.asciidoc
  docs/en/siem/cases/api/cases-api/case-api-update-connector.asciidoc
  docs/en/siem/cases/api/cases-api/cases-api-assign-connector.asciidoc
  docs/en/siem/cases/api/cases-api/cases-api-associate-sn.asciidoc
  docs/en/siem/cases/api/cases-api/cases-api-create.asciidoc
  docs/en/siem/cases/api/cases-api/cases-api-find-connectors.asciidoc
  docs/en/siem/cases/api/cases-api/cases-api-update.asciidoc
  docs/en/siem/cases/api/cases-api/cases-api.asciidoc
  docs/en/siem/cases/cases-overview.asciidoc
  docs/en/siem/cases/cases-ui-integrations.asciidoc
  docs/en/siem/cases/images/cases-ui-connector.png
  docs/en/siem/cases/images/cases-ui-open.png
  docs/en/siem/images/cases-ui-home.png
Labels: backport

#1128 [DOCS] Simplifies offsets
  docs/en/stack/index-landing-all.adoc
  docs/en/stack/landing-stack.asciidoc
  docs/en/stack/redirects-landing.adoc
Labels: v8.0.0

#1103 [Docs][SIEM]Updates required fields section
  docs/en/siem/field-ref.asciidoc
Labels: v7.7.0

#1130 [7.x] [Docs][SIEM]Updates required fields section (#1103)
  docs/en/siem/field-ref.asciidoc
Labels: backport

#1131 [7.8] [Docs][SIEM]Updates required fields section (#1103)
  docs/en/siem/field-ref.asciidoc
Labels: backport

#1132 [7.7] [Docs][SIEM]Updates required fields section (#1103)
  docs/en/siem/field-ref.asciidoc
Labels: backport

#1123 [SIEM]Removes obsolete prebuilt rules
  docs/en/siem/detections/prebuilt-rules/prebuilt-rules-changelog.asciidoc
  docs/en/siem/detections/prebuilt-rules/prebuilt-rules-reference.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-desc-index.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/execution-via-signed-binary.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/suspicious-process-spawning-from-script-interpreter.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/suspicious-script-object-execution.asciidoc
  docs/en/siem/detections/prebuilt-rules/tune-rule-signals.asciidoc
Labels: needs_backport, v7.7.0

#1133 [7.x] removes obsolete rules (#1123)
  docs/en/siem/detections/prebuilt-rules/prebuilt-rules-changelog.asciidoc
  docs/en/siem/detections/prebuilt-rules/prebuilt-rules-reference.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-desc-index.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/execution-via-signed-binary.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/suspicious-process-spawning-from-script-interpreter.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/suspicious-script-object-execution.asciidoc
  docs/en/siem/detections/prebuilt-rules/tune-rule-signals.asciidoc
Labels: backport

#1134 [7.8] removes obsolete rules (#1123)
  docs/en/siem/detections/prebuilt-rules/prebuilt-rules-changelog.asciidoc
  docs/en/siem/detections/prebuilt-rules/prebuilt-rules-reference.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-desc-index.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/execution-via-signed-binary.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/suspicious-process-spawning-from-script-interpreter.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/suspicious-script-object-execution.asciidoc
  docs/en/siem/detections/prebuilt-rules/tune-rule-signals.asciidoc
Labels: backport

#1135 [7.7] removes obsolete rules (#1123)
  docs/en/siem/detections/prebuilt-rules/prebuilt-rules-changelog.asciidoc
  docs/en/siem/detections/prebuilt-rules/prebuilt-rules-reference.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-desc-index.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/execution-via-signed-binary.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/suspicious-process-spawning-from-script-interpreter.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/suspicious-script-object-execution.asciidoc
  docs/en/siem/detections/prebuilt-rules/tune-rule-signals.asciidoc
Labels: backport

#1122 [SIEM]Updates prebuilt rules for 7.8
  docs/en/siem/detections/prebuilt-rules/prebuilt-rules-changelog.asciidoc
  docs/en/siem/detections/prebuilt-rules/prebuilt-rules-reference.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-desc-index.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/anomalous-process-for-a-linux-population.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/anomalous-process-for-a-windows-population.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/attempt-to-disable-iptables-or-firewall.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/attempt-to-disable-syslog-service.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/base16-or-base32-encoding-decoding-activity.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/base64-encoding-decoding-activity.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/connection-to-external-network-via-telnet.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/connection-to-internal-network-via-telnet.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/enumeration-of-kernel-modules.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/file-deletion-via-shred.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/file-permission-modification-in-writable-directory.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/hex-encoding-decoding-activity.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/interactive-terminal-spawned-via-perl.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/interactive-terminal-spawned-via-python.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/kernel-module-removal.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/potential-disabling-of-selinux.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/potential-shell-via-web-server.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/setgid-bit-set-via-chmod.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/setuid-bit-set-via-chmod.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/sudoers-file-modification.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-linux-network-activity.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-linux-username.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-network-connection-via-rundll32.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-process-for-a-linux-host.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-process-for-a-windows-host.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-windows-network-activity.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-windows-remote-user.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-windows-user-privilege-elevation-activity.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-windows-username.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/virtual-machine-fingerprinting.asciidoc
Labels: v7.8.0

#1136 [7.x] [SIEM]Updates prebuilt rules for 7.8 (#1122)
  docs/en/siem/detections/prebuilt-rules/prebuilt-rules-changelog.asciidoc
  docs/en/siem/detections/prebuilt-rules/prebuilt-rules-reference.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-desc-index.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/anomalous-process-for-a-linux-population.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/anomalous-process-for-a-windows-population.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/attempt-to-disable-iptables-or-firewall.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/attempt-to-disable-syslog-service.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/base16-or-base32-encoding-decoding-activity.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/base64-encoding-decoding-activity.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/connection-to-external-network-via-telnet.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/connection-to-internal-network-via-telnet.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/enumeration-of-kernel-modules.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/file-deletion-via-shred.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/file-permission-modification-in-writable-directory.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/hex-encoding-decoding-activity.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/interactive-terminal-spawned-via-perl.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/interactive-terminal-spawned-via-python.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/kernel-module-removal.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/potential-disabling-of-selinux.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/potential-shell-via-web-server.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/setgid-bit-set-via-chmod.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/setuid-bit-set-via-chmod.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/sudoers-file-modification.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-linux-network-activity.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-linux-username.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-network-connection-via-rundll32.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-process-for-a-linux-host.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-process-for-a-windows-host.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-windows-network-activity.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-windows-remote-user.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-windows-user-privilege-elevation-activity.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-windows-username.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/virtual-machine-fingerprinting.asciidoc
Labels: backport

#1137 [7.8] [SIEM]Updates prebuilt rules for 7.8 (#1122)
  docs/en/siem/detections/prebuilt-rules/prebuilt-rules-changelog.asciidoc
  docs/en/siem/detections/prebuilt-rules/prebuilt-rules-reference.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-desc-index.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/anomalous-process-for-a-linux-population.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/anomalous-process-for-a-windows-population.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/attempt-to-disable-iptables-or-firewall.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/attempt-to-disable-syslog-service.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/base16-or-base32-encoding-decoding-activity.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/base64-encoding-decoding-activity.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/connection-to-external-network-via-telnet.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/connection-to-internal-network-via-telnet.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/enumeration-of-kernel-modules.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/file-deletion-via-shred.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/file-permission-modification-in-writable-directory.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/hex-encoding-decoding-activity.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/interactive-terminal-spawned-via-perl.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/interactive-terminal-spawned-via-python.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/kernel-module-removal.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/potential-disabling-of-selinux.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/potential-shell-via-web-server.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/setgid-bit-set-via-chmod.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/setuid-bit-set-via-chmod.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/sudoers-file-modification.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-linux-network-activity.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-linux-username.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-network-connection-via-rundll32.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-process-for-a-linux-host.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-process-for-a-windows-host.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-windows-network-activity.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-windows-remote-user.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-windows-user-privilege-elevation-activity.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/unusual-windows-username.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/virtual-machine-fingerprinting.asciidoc
Labels: backport

#1151 [DOCS] Updates path to Kibana highlights
  docs/en/install-upgrade/highlights.asciidoc
Labels: v8.0.0

#1149 [7.x] Add Ingest Manager Troubleshooting FAQ doc (#1148)
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#1150 [7.8] Add Ingest Manager Troubleshooting FAQ doc (#1148)
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#1147 Get ingest management docs ready to publish
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/overview.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: :Ingest, needs_backport

#1152 [7.x] Get ingest management docs ready to publish (#1147)
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/overview.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#1153 [7.8] Get ingest management docs ready to publish (#1147)
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/overview.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#1154 Fix broken link
  docs/en/ingest-management/getting-started.asciidoc
Labels: :Ingest

#1155 [7.x] fix broken link (#1154)
  docs/en/ingest-management/getting-started.asciidoc
Labels: backport

#1156 [7.8] fix broken link (#1154)
  docs/en/ingest-management/getting-started.asciidoc
Labels: backport

#1157 Temporarily comment out overview
  docs/en/ingest-management/index.asciidoc
Labels: :Ingest

#1158 [7.x] Temporarily comment out overview (#1157)
  docs/en/ingest-management/index.asciidoc
Labels: backport

#1159 [7.8] Temporarily comment out overview (#1157)
  docs/en/ingest-management/index.asciidoc
Labels: backport

#1162 [DOCS] Add data streams glossary def
  docs/en/glossary/glossary.asciidoc
Labels: v7.9.0, v8.0.0

#1161 [DOCS] Move Metrics content from Kibana doc to Metrics Monitoring guide
  docs/en/logs/configuring.asciidoc
  docs/en/logs/logs-ui-intro.asciidoc
  docs/en/metrics/configuring-metrics-source.asciidoc
  docs/en/metrics/explore-metrics-data.asciidoc
  docs/en/metrics/images/create-metrics-alert.png
  docs/en/metrics/images/infra-time-selector.png
  docs/en/metrics/images/infra-view-metrics.png
  docs/en/metrics/images/metrics-explorer-screen.png
  docs/en/metrics/images/metrics-integrations.png
  docs/en/metrics/images/time-filter-calendar.png
  docs/en/metrics/images/time-filter-clock.png
  docs/en/metrics/index.asciidoc
  docs/en/metrics/metrics-alerting.asciidoc
  docs/en/metrics/metrics-app-overview.asciidoc
  docs/en/metrics/metrics-explorer.asciidoc
  docs/en/metrics/metrics-installation.asciidoc
  docs/en/metrics/metrics-overview.asciidoc
Labels: v7.8.0

#1165 [7.8] [DOCS] Move Metrics content from Kibana doc to Metrics Monitoring guide (#1161)
  docs/en/logs/configuring.asciidoc
  docs/en/logs/logs-ui-intro.asciidoc
  docs/en/metrics/configuring-metrics-source.asciidoc
  docs/en/metrics/explore-metrics-data.asciidoc
  docs/en/metrics/images/create-metrics-alert.png
  docs/en/metrics/images/infra-time-selector.png
  docs/en/metrics/images/infra-view-metrics.png
  docs/en/metrics/images/metrics-explorer-screen.png
  docs/en/metrics/images/metrics-integrations.png
  docs/en/metrics/images/time-filter-calendar.png
  docs/en/metrics/images/time-filter-clock.png
  docs/en/metrics/index.asciidoc
  docs/en/metrics/metrics-alerting.asciidoc
  docs/en/metrics/metrics-app-overview.asciidoc
  docs/en/metrics/metrics-explorer.asciidoc
  docs/en/metrics/metrics-installation.asciidoc
  docs/en/metrics/metrics-overview.asciidoc
Labels: backport

#1164 [7.x] [DOCS] Move Metrics content from Kibana doc to Metrics Monitoring guide (#1161)
  docs/en/logs/configuring.asciidoc
  docs/en/logs/logs-ui-intro.asciidoc
  docs/en/metrics/configuring-metrics-source.asciidoc
  docs/en/metrics/explore-metrics-data.asciidoc
  docs/en/metrics/images/create-metrics-alert.png
  docs/en/metrics/images/infra-time-selector.png
  docs/en/metrics/images/infra-view-metrics.png
  docs/en/metrics/images/metrics-explorer-screen.png
  docs/en/metrics/images/metrics-integrations.png
  docs/en/metrics/images/time-filter-calendar.png
  docs/en/metrics/images/time-filter-clock.png
  docs/en/metrics/index.asciidoc
  docs/en/metrics/metrics-alerting.asciidoc
  docs/en/metrics/metrics-app-overview.asciidoc
  docs/en/metrics/metrics-explorer.asciidoc
  docs/en/metrics/metrics-installation.asciidoc
  docs/en/metrics/metrics-overview.asciidoc
Labels: backport

#1163 Get agent docs building
  docs/en/ingest-management/index.asciidoc
Labels: :Ingest, review

#1166 [7.x] Get agent docs building (#1163)
  docs/en/ingest-management/index.asciidoc
Labels: :Ingest, backport, v7.9.0

#1167 [7.8] Get agent docs building (#1163)
  docs/en/ingest-management/index.asciidoc
Labels: :Ingest, backport, v7.8.0

#1170 [7.8] Edit ingest management troubleshooting docs (#1160)
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: :Ingest, backport

#1169 [7.x] Edit ingest management troubleshooting docs (#1160)
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: :Ingest, backport

#1179 [DOCS] Modifies instruction in ML getting started to reflect UI changes
  docs/en/stack/ml/get-started/get-started-prereqs.asciidoc
Labels: :ml, v7.8.0, v7.9.0, v8.0.0

#1172 fix hyperlink typo for Beats issues
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: :Ingest, needs_backport

#1171 [DOCS] Uncomments Kibana breaking changes
  docs/en/install-upgrade/breaking.asciidoc
Labels: v7.8.0

#1173 [DOCS] Fixes problematic terminology
  docs/en/siem/detections/prebuilt-rules/prebuilt-rules-reference.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/network-connection-via-regsvr.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/network-connection-via-signed-binary.asciidoc
  docs/en/siem/detections/prebuilt-rules/rule-details/proxy-port-activity-to-the-internet.asciidoc
Labels: :ml, v7.7.2, v7.8.0, v7.9.0, v8.0.0

#1175 Edit ingest management getting started guide
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: :Ingest, needs_backport

#1181 [7.x] Edit ingest management getting started guide (#1175)
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#1182 [7.8] Edit ingest management getting started guide (#1175)
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#1168 Edit ingest management overview
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/ingest-management-limitations.asciidoc
  docs/en/ingest-management/ingest-management-overview.asciidoc
  docs/en/ingest-management/overview.asciidoc
Labels: :Ingest, review, v7.8.0, v7.9.0, v8.0.0

#1185 [7.x] Initial draft for ingest management overview (#1144)
  docs/en/ingest-management/images/data-source.png
  docs/en/ingest-management/images/data-streams.png
  docs/en/ingest-management/images/fleet.png
  docs/en/ingest-management/images/integrations.png
  docs/en/ingest-management/images/user-settings.png
  docs/en/ingest-management/ingest-management-overview.asciidoc
Labels: :Ingest, backport

#1186 [7.8] Initial draft for ingest management overview (#1144)
  docs/en/ingest-management/images/data-source.png
  docs/en/ingest-management/images/data-streams.png
  docs/en/ingest-management/images/fleet.png
  docs/en/ingest-management/images/integrations.png
  docs/en/ingest-management/images/user-settings.png
  docs/en/ingest-management/ingest-management-overview.asciidoc
Labels: :Ingest, backport

#1189 [7.x] Edit ingest management overview (#1168)
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/ingest-management-limitations.asciidoc
  docs/en/ingest-management/ingest-management-overview.asciidoc
  docs/en/ingest-management/overview.asciidoc
Labels: :Ingest, backport, v7.9.0

#1190 [7.8] Edit ingest management overview (#1168)
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/ingest-management-limitations.asciidoc
  docs/en/ingest-management/ingest-management-overview.asciidoc
  docs/en/ingest-management/overview.asciidoc
Labels: :Ingest, backport, v7.8.0

#1187 [7.x] fix hyperlink typo for Beats issues (#1172)
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: :Ingest, backport

#1188 [7.8] fix hyperlink typo for Beats issues (#1172)
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: :Ingest, backport

#1191 [DOCS] Fixes license management link
  docs/en/getting-started/get-started-stack.asciidoc
Labels: v8.0.0

#1194 [DOCS] Fix problems in ingest management docs found during testing
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/ingest-management-limitations.asciidoc
  docs/en/ingest-management/ingest-management-overview.asciidoc
  docs/en/ingest-management/overview.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: :Ingest, needs_backport

#1195 [7.x] [DOCS] Fix problems in ingest management docs found during testing (#1194)
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/ingest-management-limitations.asciidoc
  docs/en/ingest-management/ingest-management-overview.asciidoc
  docs/en/ingest-management/overview.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: :Ingest, backport, v7.9.0

#1196 [7.8] [DOCS] Fix problems in ingest management docs found during testing (#1194)
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/ingest-management-limitations.asciidoc
  docs/en/ingest-management/ingest-management-overview.asciidoc
  docs/en/ingest-management/overview.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: :Ingest, backport, v7.8.0

#1197 Change misleading sentence about required config settings
  docs/en/ingest-management/getting-started.asciidoc
Labels: :Ingest, needs_backport, v7.8.0, v8.0.0

#1199 [7.8] Change misleading sentence about required config settings (#1197)
  docs/en/ingest-management/getting-started.asciidoc
Labels: :Ingest, backport, v7.8.0

#1198 [7.x] Change misleading sentence about required config settings (#1197)
  docs/en/ingest-management/getting-started.asciidoc
Labels: :Ingest, backport, v7.9.0

#1200 [Docs][SIEM]Fixes prebuilt rules terminology and typo
  docs/en/siem/detections/api/rules-api-export.asciidoc
  docs/en/siem/detections/api/rules-api-prebuilt.asciidoc
Labels: v7.8.0

#1201 [7.x] fixes terminology and typo (#1200)
  docs/en/siem/detections/api/rules-api-export.asciidoc
  docs/en/siem/detections/api/rules-api-prebuilt.asciidoc
Labels: backport

#1202 [7.8] fixes terminology and typo (#1200)
  docs/en/siem/detections/api/rules-api-export.asciidoc
  docs/en/siem/detections/api/rules-api-prebuilt.asciidoc
Labels: backport

#1205 [DOCS] Fix ES-Hadoop 7.8 breaking changes
  docs/en/install-upgrade/breaking.asciidoc
Labels: v7.8.0

#1193 [DOCS] Updates screenshots in data frame analytics examples
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/ecommerce-outlier-job-1.png
  docs/en/stack/ml/df-analytics/images/ecommerce-outlier-job-2.png
  docs/en/stack/ml/df-analytics/images/ecommerce-outlier-job.jpg
  docs/en/stack/ml/df-analytics/images/ecommerce-transform-preview.jpg
  docs/en/stack/ml/df-analytics/images/ecommerce-transform-preview.png
  docs/en/stack/ml/df-analytics/images/flights-classification-job-1.png
  docs/en/stack/ml/df-analytics/images/flights-classification-job-2.png
  docs/en/stack/ml/df-analytics/images/flights-classification-job.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-details.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-details.png
  docs/en/stack/ml/df-analytics/images/flights-regression-job-1.png
  docs/en/stack/ml/df-analytics/images/flights-regression-job-2.png
  docs/en/stack/ml/df-analytics/images/flights-regression-job.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-results.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-results.png
  docs/en/stack/ml/df-analytics/images/outliers.jpg
  docs/en/stack/ml/df-analytics/images/outliers.png
Labels: :ml, v7.9.0, v8.0.0

#1206 [DOCS] Updates screenshots in view results getting started chapter
  docs/en/stack/ml/get-started/get-started-results.asciidoc
  docs/en/stack/ml/get-started/images/ml-gs-job1-analysis.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job1-analysis.png
  docs/en/stack/ml/get-started/images/ml-gs-job1-anomalies.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job1-anomalies.png
  docs/en/stack/ml/get-started/images/ml-gs-job2-explorer-anomaly.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job2-explorer-anomaly.png
  docs/en/stack/ml/get-started/images/ml-gs-job2-explorer-table.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job2-explorer-table.png
  docs/en/stack/ml/get-started/images/ml-gs-job2-explorer.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job2-explorer.png
  docs/en/stack/ml/get-started/images/ml-gs-job3-explorer.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job3-explorer.png
  docs/en/stack/ml/get-started/images/ml-gs-job4-explorer.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job4-explorer.png
  docs/en/stack/ml/get-started/images/ml-gs-web-results.jpg
  docs/en/stack/ml/get-started/images/ml-gs-web-results.png
Labels: :ml, v7.9.0, v8.0.0

#1208 [DOCS] Resizes the screenshots in view anomaly detection results
  docs/en/stack/ml/get-started/images/ml-gs-job1-analysis.png
  docs/en/stack/ml/get-started/images/ml-gs-job4-explorer.png
Labels: :ml, v7.9.0, v8.0.0

#1214 Adds alphabetical links to Glossary
  docs/en/glossary/glossary.asciidoc
  docs/en/glossary/index.asciidoc
  docs/en/glossary/intro.asciidoc
Labels: v8.0.0

#1218 Rename kibana user to kibana_system in sample dockerfile
  docs/en/getting-started/docker/elastic-docker-tls.yml
Labels: v7.8.0, v7.9.0, v8.0.0

#1211 Clean up ingest management docs
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/ingest-management-limitations.asciidoc
  docs/en/ingest-management/ingest-management-overview.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: :Ingest

#1220 [7.x] Clean up ingest management docs (#1211)
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/ingest-management-limitations.asciidoc
  docs/en/ingest-management/ingest-management-overview.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: :Ingest, backport

#1221 [7.8] Clean up ingest management docs (#1211)
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/ingest-management-limitations.asciidoc
  docs/en/ingest-management/ingest-management-overview.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: :Ingest, backport

#1203 [DOCS] Add ECS fields to Logs monitoring guide
  docs/en/logs/index.asciidoc
  docs/en/logs/logs-field-reference.asciidoc
  docs/en/logs/logs-installation.asciidoc
Labels: review, v7.8.0, v7.9.0

#1224 [DOCS] Document encryption key setting needed by Fleet
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: :Ingest, review

#1229 [7.8] [DOCS] Document encryption key setting needed by Fleet (#1224)
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: backport

#1228 [7.x] [DOCS] Document encryption key setting needed by Fleet (#1224)
  docs/en/ingest-management/getting-started.asciidoc
  docs/en/ingest-management/troubleshooting.asciidoc
Labels: :Ingest, backport

#1227 [7.8] [DOCS] Add ECS fields to Logs monitoring guide (#1203)
  docs/en/logs/index.asciidoc
  docs/en/logs/logs-field-reference.asciidoc
  docs/en/logs/logs-installation.asciidoc
Labels: backport

#1226 [7.x] [DOCS] Add ECS fields to Logs monitoring guide (#1203)
  docs/en/logs/index.asciidoc
  docs/en/logs/logs-field-reference.asciidoc
  docs/en/logs/logs-installation.asciidoc
Labels: backport

#1219 remove unnecessary options for elasticsearch-setup-passwords
  docs/en/getting-started/get-started-docker.asciidoc
Labels: :Security, v7.6.3, v7.7.2, v7.8.1, v7.9.0, v8.0.0

#1225 Use es03 cert for es03 node in docker
  docs/en/getting-started/docker/elastic-docker-tls.yml
Labels: v7.4.3, v7.5.3, v7.6.3, v7.7.2, v7.8.1, v7.9.0, v8.0.0

#1222 [DOCS] Adds screenshot for model snapshot management
  docs/en/stack/ml/anomaly-detection/images/ml-model-snapshots.png
  docs/en/stack/ml/anomaly-detection/model-snapshots.asciidoc
Labels: :ml, v7.9.0, v8.0.0

#1210 [DOCS] Split fields and metrics content in Metrics monitoring guide
  docs/en/metrics/aws-ec2-metricset.asciidoc
  docs/en/metrics/aws-rds-metricset.asciidoc
  docs/en/metrics/aws-s3-metricset.asciidoc
  docs/en/metrics/aws-sqs-metricset.asciidoc
  docs/en/metrics/docker-metricset.asciidoc
  docs/en/metrics/host-metricset.asciidoc
  docs/en/metrics/index.asciidoc
  docs/en/metrics/infrastructure-metrics.asciidoc
  docs/en/metrics/kubernetes-metricset.asciidoc
  docs/en/metrics/metrics-fields-reference.asciidoc
  docs/en/metrics/metrics-installation.asciidoc
Labels: review, v7.8.0, v7.9.0

#1232 [7.8] Split fields and metrics content (#1210)
  docs/en/metrics/aws-ec2-metricset.asciidoc
  docs/en/metrics/aws-rds-metricset.asciidoc
  docs/en/metrics/aws-s3-metricset.asciidoc
  docs/en/metrics/aws-sqs-metricset.asciidoc
  docs/en/metrics/docker-metricset.asciidoc
  docs/en/metrics/host-metricset.asciidoc
  docs/en/metrics/index.asciidoc
  docs/en/metrics/infrastructure-metrics.asciidoc
  docs/en/metrics/kubernetes-metricset.asciidoc
  docs/en/metrics/metrics-fields-reference.asciidoc
  docs/en/metrics/metrics-installation.asciidoc
Labels: backport

#1231 [7.x] Split fields and metrics content (#1210)
  docs/en/metrics/aws-ec2-metricset.asciidoc
  docs/en/metrics/aws-rds-metricset.asciidoc
  docs/en/metrics/aws-s3-metricset.asciidoc
  docs/en/metrics/aws-sqs-metricset.asciidoc
  docs/en/metrics/docker-metricset.asciidoc
  docs/en/metrics/host-metricset.asciidoc
  docs/en/metrics/index.asciidoc
  docs/en/metrics/infrastructure-metrics.asciidoc
  docs/en/metrics/kubernetes-metricset.asciidoc
  docs/en/metrics/metrics-fields-reference.asciidoc
  docs/en/metrics/metrics-installation.asciidoc
Labels: backport

#1213 [DOCS] Adds Kibana terms to glossary
  docs/en/glossary/glossary.asciidoc
  docs/en/glossary/index.asciidoc
Labels: v8.0.0
