Repository elastic/stack-docs, pull requests merged in 2020-07, with the labels that each got.

#1230 [Docs][SIEM]Adds ml rule prerequisites
  docs/en/siem/detections/detection-engine-intro.asciidoc
Labels: v7.8.0

#1235 [7.x] [Docs][SIEM]Adds ml rule prerequisites (#1230)
  docs/en/siem/detections/detection-engine-intro.asciidoc
Labels: backport

#1236 [7.8] [Docs][SIEM]Adds ml rule prerequisites (#1230)
  docs/en/siem/detections/detection-engine-intro.asciidoc
Labels: backport

#1207 [DOCS] Updates screenshots in create forecasts getting started chapter
  docs/en/stack/ml/get-started/get-started-forecasts.asciidoc
  docs/en/stack/ml/get-started/images/ml-gs-duration.jpg
  docs/en/stack/ml/get-started/images/ml-gs-duration.png
  docs/en/stack/ml/get-started/images/ml-gs-forecast-actual.jpg
  docs/en/stack/ml/get-started/images/ml-gs-forecast-actual.png
  docs/en/stack/ml/get-started/images/ml-gs-forecast-results.jpg
  docs/en/stack/ml/get-started/images/ml-gs-forecast-results.png
  docs/en/stack/ml/get-started/images/ml-gs-forecast.jpg
  docs/en/stack/ml/get-started/images/ml-gs-forecast.png
Labels: :ml, v7.9.0, v8.0.0

#1234 Change links to refactored Beats getting started docs
  docs/en/getting-started/get-started-stack.asciidoc
  docs/en/gke-on-prem/index.asciidoc
  docs/en/siem/installation.asciidoc
Labels: :Ingest

#1238 [7.x] Change links to refactored Beats getting started docs (#1234)
  docs/en/getting-started/get-started-stack.asciidoc
  docs/en/siem/installation.asciidoc
Labels: :Ingest, backport, v7.9.0

#1239 [DOCS] Clarifies machine learning nodes
  docs/en/glossary/glossary.asciidoc
  docs/en/stack/ml/setup.asciidoc
Labels: :ml, v7.9.0, v8.0.0

#1242 [DOCS] Removes Stack Overview source files
  docs/en/stack/help.asciidoc
  docs/en/stack/images/InstallationFlow.jpg
  docs/en/stack/images/management-license.png
  docs/en/stack/index.asciidoc
  docs/en/stack/introduction.asciidoc
  docs/en/stack/license.asciidoc
  docs/en/stack/redirects.asciidoc
Labels: v7.5.3, v7.6.3, v7.7.2, v7.8.1, v7.9.0, v8.0.0

#1243 [7.x][DOCS] Removes Stack Overview source files (#1242)
  docs/en/stack/help.asciidoc
  docs/en/stack/images/InstallationFlow.jpg
  docs/en/stack/images/management-license.png
  docs/en/stack/index.asciidoc
  docs/en/stack/introduction.asciidoc
  docs/en/stack/license.asciidoc
  docs/en/stack/redirects.asciidoc
Labels: backport

#1244 [7.8][DOCS] Removes Stack Overview source files (#1242)
  docs/en/stack/help.asciidoc
  docs/en/stack/images/InstallationFlow.jpg
  docs/en/stack/images/management-license.png
  docs/en/stack/index.asciidoc
  docs/en/stack/introduction.asciidoc
  docs/en/stack/license.asciidoc
  docs/en/stack/redirects.asciidoc
Labels: backport

#1245 [7.7][DOCS] Removes Stack Overview source files (#1242)
  docs/en/stack/help.asciidoc
  docs/en/stack/images/InstallationFlow.jpg
  docs/en/stack/images/management-license.png
  docs/en/stack/index.asciidoc
  docs/en/stack/introduction.asciidoc
  docs/en/stack/license.asciidoc
  docs/en/stack/redirects.asciidoc
Labels: backport

#1247 [DOCS] Remove redundant tagged region
  docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-api-quickref.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
Labels: :ml, v8.0.0

#1250 [7.x][DOCS] Remove redundant tagged region
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
Labels: backport

#1251 [7.8][DOCS] Reorganizes anomaly detection source to output file mappings
  docs/en/siem/detections/machine-learning/machine-learning.asciidoc
  docs/en/stack/ml/anomaly-detection/algorithms.asciidoc
  docs/en/stack/ml/anomaly-detection/analyzing.asciidoc
  docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc
  docs/en/stack/ml/anomaly-detection/create-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/forecasting.asciidoc
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/job-tips.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-api-quickref.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-buckets.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-calendars.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-concepts.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-datafeeds.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-influencers.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-model-snapshots.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-overview.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-rules.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/overview.asciidoc
  docs/en/stack/ml/anomaly-detection/stopping-ml.asciidoc
  docs/en/stack/ml/get-started/get-started-jobs.asciidoc
  docs/en/stack/ml/index.asciidoc
  docs/en/stack/ml/redirects.asciidoc
Labels: backport

#1249 [7.7][DOCS] Reorganizes anomaly detection source to output file mappings
  docs/en/siem/detections/machine-learning/machine-learning.asciidoc
  docs/en/stack/ml/anomaly-detection/algorithms.asciidoc
  docs/en/stack/ml/anomaly-detection/analyzing.asciidoc
  docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc
  docs/en/stack/ml/anomaly-detection/create-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/forecasting.asciidoc
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/job-tips.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-api-quickref.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-buckets.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-calendars.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-concepts.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-datafeeds.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-influencers.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-model-snapshots.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-overview.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-rules.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/overview.asciidoc
  docs/en/stack/ml/anomaly-detection/stopping-ml.asciidoc
  docs/en/stack/ml/get-started/get-started-jobs.asciidoc
  docs/en/stack/ml/index.asciidoc
  docs/en/stack/ml/redirects.asciidoc
Labels: backport

#1246 [DOCS] Reorganizes data frame analytics source to output file mappings
  docs/en/stack/landing-stack.asciidoc
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/dfa-outlier-detection.asciidoc
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/dfanalytics-examples.asciidoc
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/hyperparameters.asciidoc
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-concepts.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-phases.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
  docs/en/stack/ml/df-analytics/ml-inference.asciidoc
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
Labels: :ml, v8.0.0

#1253 [7.x][DOCS] Reorganizes data frame analytics source to output file mappings
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/dfa-outlier-detection.asciidoc
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/dfanalytics-examples.asciidoc
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/hyperparameters.asciidoc
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-concepts.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-phases.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
  docs/en/stack/ml/df-analytics/ml-inference.asciidoc
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
Labels: backport

#1254 [7.8][DOCS] Reorganizes data frame analytics source to output file mappings
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/dfa-outlier-detection.asciidoc
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/dfanalytics-examples.asciidoc
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/hyperparameters.asciidoc
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-concepts.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-phases.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
  docs/en/stack/ml/df-analytics/ml-inference.asciidoc
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
Labels: backport

#1255 [7.7][DOCS] Reorganizes data frame analytics source to output file mappings
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/dfa-outlier-detection.asciidoc
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/dfanalytics-examples.asciidoc
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/hyperparameters.asciidoc
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-concepts.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-phases.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
  docs/en/stack/ml/df-analytics/ml-inference.asciidoc
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
Labels: backport

#1252 [DOCS] Reorganizes ML tutorial source to output file mappings
  docs/en/stack/ml/get-started-trial.asciidoc
  docs/en/stack/ml/get-started/index.asciidoc
  docs/en/stack/ml/get-started/ml-getting-started.asciidoc
  docs/en/stack/ml/get-started/ml-gs-forecasts.asciidoc
  docs/en/stack/ml/get-started/ml-gs-jobs.asciidoc
  docs/en/stack/ml/get-started/ml-gs-next.asciidoc
  docs/en/stack/ml/get-started/ml-gs-results.asciidoc
  docs/en/stack/ml/get-started/ml-gs-visualizer.asciidoc
Labels: :ml, v8.0.0

#1256 [7.x][DOCS] Reorganizes ML tutorial source to output file mappings (#1252)
  docs/en/stack/ml/get-started-trial.asciidoc
  docs/en/stack/ml/get-started/index.asciidoc
  docs/en/stack/ml/get-started/ml-getting-started.asciidoc
  docs/en/stack/ml/get-started/ml-gs-forecasts.asciidoc
  docs/en/stack/ml/get-started/ml-gs-jobs.asciidoc
  docs/en/stack/ml/get-started/ml-gs-next.asciidoc
  docs/en/stack/ml/get-started/ml-gs-results.asciidoc
  docs/en/stack/ml/get-started/ml-gs-visualizer.asciidoc
Labels: backport

#1257 [7.8][DOCS] Reorganizes ML tutorial source to output file mappings (#1252)
  docs/en/stack/ml/get-started-trial.asciidoc
  docs/en/stack/ml/get-started/index.asciidoc
  docs/en/stack/ml/get-started/ml-getting-started.asciidoc
  docs/en/stack/ml/get-started/ml-gs-forecasts.asciidoc
  docs/en/stack/ml/get-started/ml-gs-jobs.asciidoc
  docs/en/stack/ml/get-started/ml-gs-next.asciidoc
  docs/en/stack/ml/get-started/ml-gs-results.asciidoc
  docs/en/stack/ml/get-started/ml-gs-visualizer.asciidoc
Labels: backport

#1258 [7.7][DOCS] Reorganizes ML tutorial source to output file mappings (#1252)
  docs/en/stack/ml/get-started-trial.asciidoc
  docs/en/stack/ml/get-started/index.asciidoc
  docs/en/stack/ml/get-started/ml-getting-started.asciidoc
  docs/en/stack/ml/get-started/ml-gs-forecasts.asciidoc
  docs/en/stack/ml/get-started/ml-gs-jobs.asciidoc
  docs/en/stack/ml/get-started/ml-gs-next.asciidoc
  docs/en/stack/ml/get-started/ml-gs-results.asciidoc
  docs/en/stack/ml/get-started/ml-gs-visualizer.asciidoc
Labels: backport

#1259 [DOCS] Removes ML content from index.asciidoc files
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/xpack-ml.asciidoc
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics.asciidoc
Labels: :ml, v8.0.0

#1260 [7.x][DOCS] Removes ML content from index.asciidoc files
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/xpack-ml.asciidoc
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics.asciidoc
Labels: backport

#1261 [7.8][DOCS] Removes ML content from index.asciidoc files
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/xpack-ml.asciidoc
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics.asciidoc
Labels: backport

#1262 [7.7][DOCS] Removes ML content from index.asciidoc files
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/xpack-ml.asciidoc
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics.asciidoc
Labels: backport

#1237 [DOCS] Clarify trial subscription levels
  docs/en/getting-started/get-started-docker.asciidoc
  docs/en/install-upgrade/installing-stack.asciidoc
Labels: v7.7.2, v7.8.1, v7.9.0, v8.0.0

#1263 [7.x][DOCS] Clarify trial subscription levels (#1237)
  docs/en/getting-started/get-started-docker.asciidoc
  docs/en/install-upgrade/installing-stack.asciidoc
Labels: backport

#1264 [7.8][DOCS] Clarify trial subscription levels (#1237)
  docs/en/getting-started/get-started-docker.asciidoc
  docs/en/install-upgrade/installing-stack.asciidoc
Labels: backport

#1265 [7.7][DOCS] Clarify trial subscription levels (#1237)
  docs/en/getting-started/get-started-docker.asciidoc
  docs/en/install-upgrade/installing-stack.asciidoc
Labels: backport

#1269 [DOCS] Makes it clear that only significant influencers are reported
  docs/en/stack/ml/anomaly-detection/ml-influencers.asciidoc
Labels: :ml, v7.8.1, v7.9.0, v8.0.0

#1268 [DOCS] Expands inference conceptual docs with aggregation section
  docs/en/stack/ml/df-analytics/ml-inference.asciidoc
Labels: :ml, v7.9.0, v8.0.0

#1276 [DOCS] Sorts APM ML modules
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
Labels: :ml, v7.9.0, v8.0.0

#1277 [7.x][DOCS] Sorts APM ML modules (#1276)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
Labels: backport

#1274 [DOCS] Adds Jupyter notebook link to loss function section of regression conceptual
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
Labels: :ml, v7.8.1, v7.9.0, v8.0.0

#1275 [DOCS] Sorts SIEM ML modules
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Labels: :ml, v7.9.0, v8.0.0

#1279 [7.x][DOCS] Sorts SIEM ML modules (#1275)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Labels: backport

#1280 [7.9][DOCS] Sorts SIEM ML modules (#1275)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Labels: backport

#1272 [DOCS] Updates to APM ML module for service maps
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
Labels: :ml, v7.10.0, v7.9.0, v8.0.0

#1266 [DOCS] Refresh outlier screenshots with histograms
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/images/ecommerce-outlier-job-1.png
  docs/en/stack/ml/df-analytics/images/ecommerce-outlier-job-2.png
  docs/en/stack/ml/df-analytics/images/ecommerce-transform-preview.png
  docs/en/stack/ml/df-analytics/images/outliers.png
Labels: :ml, v7.9.0, v8.0.0

#1281 [7.x][DOCS] Refresh outlier screenshots with histograms (#1266)
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/images/ecommerce-outlier-job-1.png
  docs/en/stack/ml/df-analytics/images/ecommerce-outlier-job-2.png
  docs/en/stack/ml/df-analytics/images/ecommerce-transform-preview.png
  docs/en/stack/ml/df-analytics/images/outliers.png
Labels: backport

#1282 [7.9][DOCS] Refresh outlier screenshots with histograms (#1266)
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/images/ecommerce-outlier-job-1.png
  docs/en/stack/ml/df-analytics/images/ecommerce-outlier-job-2.png
  docs/en/stack/ml/df-analytics/images/ecommerce-transform-preview.png
  docs/en/stack/ml/df-analytics/images/outliers.png
Labels: backport

#1284 [Docs][ML]Fixes broken SIEM link
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Labels: v7.10.0, v7.9.0, v8.0.0

#1283 [DOCS] Changes menu item name to Setup and security in ML book
  docs/en/stack/ml/anomaly-detection/xpack-ml.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics.asciidoc
  docs/en/stack/ml/setup.asciidoc
Labels: :ml, v7.10.0, v7.8.1, v7.9.0, v8.0.0

#1285 [DOCS] Fix apm-server-ref in installing-stack.asciidoc
  docs/en/install-upgrade/installing-stack.asciidoc
Labels: v7.8.1, v7.9.0, v8.0.0

#1288 [DOCS] Changes level offset for data frame analytics pages
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/dfa-outlier-detection.asciidoc
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/dfanalytics-examples.asciidoc
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/hyperparameters.asciidoc
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-concepts.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-phases.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
  docs/en/stack/ml/df-analytics/ml-inference.asciidoc
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
Labels: :ml, v8.0.0

#1287 [DOCS] Fix more apm-server-ref-links
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/overview.asciidoc
Labels: v7.10.0

#1289 [7.x][DOCS] Changes level offset for data frame analytics pages (#1288)
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/dfa-outlier-detection.asciidoc
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/dfanalytics-examples.asciidoc
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/hyperparameters.asciidoc
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-concepts.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-phases.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
  docs/en/stack/ml/df-analytics/ml-inference.asciidoc
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
Labels: backport

#1290 [7.9][DOCS] Changes level offset for data frame analytics pages (#1288)
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/dfa-outlier-detection.asciidoc
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/dfanalytics-examples.asciidoc
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/hyperparameters.asciidoc
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-concepts.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-phases.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
  docs/en/stack/ml/df-analytics/ml-inference.asciidoc
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
Labels: backport

#1292 [DOCS] Changes level offset for anomaly detection pages
  docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc
  docs/en/stack/ml/anomaly-detection/create-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/job-tips.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-api-quickref.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-buckets.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-calendars.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-concepts.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-datafeeds.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-influencers.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-model-snapshots.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-overview.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-rules.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/stopping-ml.asciidoc
  docs/en/stack/ml/anomaly-detection/xpack-ml.asciidoc
  docs/en/stack/ml/get-started/ml-gs-results.asciidoc
  docs/en/stack/ml/redirects.asciidoc
Labels: :ml, v8.0.0

#1293 [7.x][DOCS] Changes level offset for anomaly detection pages (#1292)
  docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc
  docs/en/stack/ml/anomaly-detection/create-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/job-tips.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-api-quickref.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-buckets.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-calendars.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-concepts.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-datafeeds.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-influencers.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-model-snapshots.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-overview.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-rules.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/stopping-ml.asciidoc
  docs/en/stack/ml/anomaly-detection/xpack-ml.asciidoc
  docs/en/stack/ml/get-started/ml-gs-results.asciidoc
  docs/en/stack/ml/redirects.asciidoc
Labels: backport

#1294 [DOCS] Removes temporary redirects
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/redirects.asciidoc
Labels: :ml, v8.0.0

#1295 [7.9][DOCS] Changes level offset for anomaly detection pages (#1292)
  docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc
  docs/en/stack/ml/anomaly-detection/create-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/job-tips.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-api-quickref.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-buckets.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-calendars.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-concepts.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-datafeeds.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-influencers.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-model-snapshots.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-overview.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-rules.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/stopping-ml.asciidoc
  docs/en/stack/ml/anomaly-detection/xpack-ml.asciidoc
  docs/en/stack/ml/get-started/ml-gs-results.asciidoc
  docs/en/stack/ml/redirects.asciidoc
Labels: backport

#1297 [7.8][DOCS] Changes level offset for anomaly detection pages (#1292)
  docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc
  docs/en/stack/ml/anomaly-detection/create-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/job-tips.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-api-quickref.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-buckets.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-calendars.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-concepts.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-datafeeds.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-influencers.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-model-snapshots.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-overview.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-rules.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/stopping-ml.asciidoc
  docs/en/stack/ml/anomaly-detection/xpack-ml.asciidoc
  docs/en/stack/ml/get-started/ml-gs-results.asciidoc
  docs/en/stack/ml/redirects.asciidoc
Labels: backport

#1296 [7.x][DOCS] Removes temporary redirects (#1294)
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/redirects.asciidoc
Labels: backport

#1298 [7.9][DOCS] Removes temporary redirects (#1294)
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/redirects.asciidoc
Labels: backport

#1299 [7.8][DOCS] Removes temporary redirects (#1294)
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/redirects.asciidoc
Labels: backport

#1270 [DOCS] Adds siem_cloudtrail module
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Labels: :ml, v7.9.0, v8.0.0

#1301 [7.x][DOCS] Adds siem_cloudtrail module (#1270)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Labels: backport

#1302 [7.9][DOCS] Adds siem_cloudtrail module (#1270)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Labels: backport

#1300 [DOCS] Rename binary_soft_classification evaluation
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
Labels: :ml, v7.10.0, v8.0.0

#1307 Change highlights path
  docs/en/install-upgrade/highlights.asciidoc
Labels: v8.0.0

#1278 [DOCS] Updates screenshots in getting started with ML and adds paragraph on annotations
  docs/en/stack/ml/get-started/images/ml-gs-annotations.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job1-analysis.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job1-analysis.png
  docs/en/stack/ml/get-started/images/ml-gs-job1-anomalies.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job1-anomalies.png
  docs/en/stack/ml/get-started/images/ml-gs-job2-explorer-anomaly.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job2-explorer-anomaly.png
  docs/en/stack/ml/get-started/images/ml-gs-job2-explorer-table.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job2-explorer-table.png
  docs/en/stack/ml/get-started/images/ml-gs-job2-explorer.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job2-explorer.png
  docs/en/stack/ml/get-started/images/ml-gs-job3-explorer.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job3-explorer.png
  docs/en/stack/ml/get-started/images/ml-gs-web-results.jpg
  docs/en/stack/ml/get-started/images/ml-gs-web-results.png
  docs/en/stack/ml/get-started/ml-gs-results.asciidoc
Labels: :ml, v7.10.0, v7.9.0, v8.0.0

#1309 [7.9] Change highlights path
  docs/en/install-upgrade/highlights.asciidoc
Labels: :Ingest, backport

#1310 [7.x] Change highlights path
  docs/en/install-upgrade/highlights.asciidoc
Labels: :Ingest, backport

#1273 [DOCS] Adds Deploying the model section to regression and classification conceptual
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
Labels: :ml, v7.8.1, v7.9.0, v8.0.0

#1312 [7.8][DOCS] Adds Deploying the model section to regression and classification conceptual
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
Labels: :ml, v7.8.1

#1311 Activate include for Beats highlights
  docs/en/install-upgrade/highlights.asciidoc
Labels: :Ingest, needs_backport, v7.10.0, v7.9.0

#1315 [7.x] Activate include for Beats highlights (#1311)
  docs/en/install-upgrade/highlights.asciidoc
Labels: backport, v7.10.0

#1316 [7.9] Activate include for Beats highlights (#1311)
  docs/en/install-upgrade/highlights.asciidoc
Labels: backport, v7.9.0

#1317 [Docs][ML]Updates ML job group names
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Labels: v7.9.0

#1318 [7.x] [Docs][ML]Updates ML job group names (#1317)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Labels: backport

#1319 [7.9] [Docs][ML]Updates ML job group names (#1317)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Labels: backport

#1314 [7.9] Add APM release highlights / breaking changes
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
Labels: blocked

#1304 [DOCS] Update machine learning security privileges
  docs/en/stack/ml/setup.asciidoc
Labels: :ml, WIP, v7.10.0, v7.9.0, v8.0.0

#1320 [7.x][DOCS] Update machine learning security privileges (#1304)
  docs/en/stack/ml/setup.asciidoc
Labels: backport

#1321 [7.9][DOCS] Update machine learning security privileges (#1304)
  docs/en/stack/ml/setup.asciidoc
Labels: backport
