Repository elastic/stack-docs, pull requests merged in 2021-03, with the labels that each got.

#1590 [DOCS] Link to preview data frame analytics API
  docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
Labels: :ml, v7.13.0, v8.0.0

#1595 [7.x][DOCS] Link to preview data frame analytics API (#1590)
  docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
Labels: backport

#1596 [DOCS] Adds trained model to glossary
  docs/en/glossary/glossary.asciidoc
Labels: :ml, v7.11.1, v7.12.0, v7.13.0, v8.0.0

#1597 [DOCS] Adds operator privileges to ML setup
  docs/en/stack/ml/setup.asciidoc
Labels: :ml, v7.12.0, v7.13.0, v8.0.0

#1599 [7.x][DOCS] Adds operator privileges to ML setup (#1597)
  docs/en/stack/ml/setup.asciidoc
Labels: backport

#1600 [7.12][DOCS] Adds operator privileges to ML setup (#1597)
  docs/en/stack/ml/setup.asciidoc
Labels: backport

#1592 [DOCS] Adds scatterplot matrix to regression and classification results
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-classification-details.png
  docs/en/stack/ml/df-analytics/images/flights-classification-results.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-details.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-results.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-total-importance.jpg
Labels: :ml, v7.12.0, v7.13.0, v8.0.0

#1601 [7.x][DOCS] Adds scatterplot matrix to data frame analytics examples (#1592)
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-classification-details.png
  docs/en/stack/ml/df-analytics/images/flights-classification-results.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-details.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-results.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-total-importance.jpg
Labels: backport

#1602 [7.12][DOCS] Adds scatterplot matrix to data frame analytics examples (#1592)
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-classification-details.png
  docs/en/stack/ml/df-analytics/images/flights-classification-results.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-details.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-results.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-total-importance.jpg
Labels: backport

#1604 [DOCS] Adds inference related terms to glossary
  docs/en/glossary/glossary.asciidoc
Labels: :ml, v8.0.0

#962 [DOCS] Clarifies machine learning rollup limitation
  docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
Labels: :ml, v7.6.3, v7.7.0, v7.8.0, v8.0.0

#1608 [7.x][DOCS] Clarifies machine learning rollup limitation (#962)
  docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
Labels: backport

#1609 [7.12][DOCS] Clarifies machine learning rollup limitation
  docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
Labels: backport

#1610 [7.11][DOCS] Clarifies machine learning rollup limitation
  docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
Labels: backport

#1611 [DOCS] Removes obsolete terms from glossary
  docs/en/glossary/glossary.asciidoc
Labels: v8.0.0

#1612 [DOCS] Add new alerting terms to glossary
  docs/en/glossary/glossary.asciidoc
Labels: v8.0.0

#1607 [DOCS] Reorganizes DFA limitations
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
Labels: :ml, v7.12.0, v7.13.0, v8.0.0

#1615 [7.x] [DOCS] Reorganizes DFA limitations (#1607)
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
Labels: :ml, backport, v7.13.0

#1616 [7.12] [DOCS] Reorganizes DFA limitations (#1607)
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
Labels: :ml, backport, v7.12.0

#1617 [7.11] [DOCS] Reorganizes DFA limitations (#1607)
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
Labels: :ml, backport, v7.11.2

#1618 Remove ES `type` definition
  docs/en/glossary/glossary.asciidoc
Labels: v8.0.0

#1620 [DOCS] Add 7.12 highlights to Installation Upgrade Guide
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.12.0

#1623 Remove coming tag for 7.12.0
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.12.0

#1624 [DOCS] Removes coming tags from highlights and breaking changes
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.12.0

#1625 [DOCS] Removes beta labels from DFA docs
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/dfa-outlier-detection.asciidoc
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/dfanalytics-examples.asciidoc
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/hyperparameters.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-feature-processors.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-phases.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-scale.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-encoding.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
  docs/en/stack/ml/df-analytics/ml-inference.asciidoc
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
  docs/en/stack/ml/df-analytics/ml-supervised-workflow.asciidoc
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Labels: :ml, v7.13.0, v8.0.0

#1628 [7.x] [DOCS] Removes beta labels from DFA docs. (#1625)
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/dfa-outlier-detection.asciidoc
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/dfanalytics-examples.asciidoc
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/hyperparameters.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-feature-processors.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-phases.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-scale.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-encoding.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
  docs/en/stack/ml/df-analytics/ml-inference.asciidoc
  docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
  docs/en/stack/ml/df-analytics/ml-supervised-workflow.asciidoc
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Labels: :ml, backport, v7.13.0

#1627 Update file upload privileges documenation
  docs/en/stack/ml/setup.asciidoc
Labels: :ml, v7.13.0, v8.0.0
