Repository elastic/stack-docs, pull requests merged in 2021-05, with the labels that each got.

#1653 [7.13] Update get-started-stack.asciidoc (#1650)
  docs/en/getting-started/get-started-stack.asciidoc
Labels: backport

#1652 [7.x] Update get-started-stack.asciidoc (#1650)
  docs/en/getting-started/get-started-stack.asciidoc
Labels: backport

#1649 [DOCS] Separates ES and Kibana security info on ML setup page
  docs/en/stack/ml/setup.asciidoc
Labels: :ml, v7.12.0, v7.13.0, v7.14.0, v8.0.0

#1655 [7.x] [DOCS] Separates ES and Kibana security info on ML setup page (#1649)
  docs/en/stack/ml/setup.asciidoc
Labels: :ml, backport, v7.14.0

#1656 [7.13] [DOCS] Separates ES and Kibana security info on ML setup page (#1649)
  docs/en/stack/ml/setup.asciidoc
Labels: :ml, backport, v7.13.0

#1657 [7.12] [DOCS] Separates ES and Kibana security info on ML setup page (#1649)
  docs/en/stack/ml/setup.asciidoc
Labels: :ml, backport, v7.12.1

#1659 [DOCS] Adds autoscaling info to Anomaly detection at scale
  docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
Labels: :ml, v7.12.1, v7.13.0, v7.14.0, v8.0.0

#1661 [7.x] [DOCS] Adds autoscaling info to Anomaly detection at scale (#1659)
  docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
Labels: :ml, backport, v7.14.0

#1662 [7.13] [DOCS] Adds autoscaling info to Anomaly detection at scale (#1659)
  docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
Labels: :ml, backport, v7.13.0

#1663 [7.12] [DOCS] Adds autoscaling info to Anomaly detection at scale (#1659)
  docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
Labels: :ml, backport, v7.12.1

#1668 [7.13] Add 7.13 Observability and APM content
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.13.0

#1669 [7.14] Add APM placeholder for 7.14
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.14.0

#1667 Adds page about recovering from a failed job to anomaly detection docs
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-restart-failed-jobs.asciidoc
Labels: :ml, v7.12.1, v7.13.0, v7.14.0, v8.0.0

#1672 [DOCS] Add Elastic agent upgrade link and note
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: v7.13.0, v7.14.0, v8.0.0

#1676 [7.x] Add agent content (#1672)
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: backport

#1677 [7.13] Add agent content (#1672)
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: backport

#1671 Add Beats BCs for 7.13
  docs/en/install-upgrade/breaking.asciidoc
Labels: v7.13.0

#1665 [DOCS] Add highlights to Install Upgrade Guide
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.13.0

#1675 [7.12] Adds page about recovering from a failed job to anomaly detection docs (#1667)
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-restart-failed-jobs.asciidoc
Labels: :ml, backport, v7.12.1

#1678 [DOCS] Remove 7.13.0 coming tags
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.13.0

#1673 [7.x] Adds page about recovering from a failed job to anomaly detection docs (#1667)
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-restart-failed-jobs.asciidoc
Labels: :ml, backport, v7.14.0
