Repository elastic/stack-docs, pull requests merged in 2021-08, with the labels that each got.

#1758 [DOCS] Reviews outlier detection docs and creates web log example
  docs/en/stack/ml/df-analytics/images/ecommerce-outlier-job-1.png
  docs/en/stack/ml/df-analytics/images/ecommerce-outlier-scatterplot.png
  docs/en/stack/ml/df-analytics/images/ecommerce-transform-preview.png
  docs/en/stack/ml/df-analytics/images/logs-transform-preview.jpg
  docs/en/stack/ml/df-analytics/images/outliers-scatterplot.jpg
  docs/en/stack/ml/df-analytics/images/outliers-scatterplot.png
  docs/en/stack/ml/df-analytics/images/outliers.jpg
  docs/en/stack/ml/df-analytics/images/outliers.png
  docs/en/stack/ml/df-analytics/images/weblog-outlier-job-1.jpg
  docs/en/stack/ml/df-analytics/images/weblog-outlier-scatterplot.jpg
  docs/en/stack/ml/df-analytics/ml-dfa-outlier-detection.asciidoc
  docs/en/stack/ml/get-started/ml-getting-started.asciidoc
Labels: :ml, v8.0.0

#1776 [DOCS] Remove coming tags from breaking changes + release highlights
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.15.0, v8.0.0

#1777 [DOCS] Remove coming tags from breaking changes + release highlights (#1776)
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
Labels: backport, v8.0.0

#1767 [DOCS] Uncomment 7.14 breaking changes
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.14.0

#1719 [DOCS] Update file data visualizer permissions
  docs/en/stack/ml/setup.asciidoc
Labels: :ml, v8.0.0, v7.15.0, v7.14.1

#1778 [DOCS] Adds a note about a workaround if DFA model is too large to fit into JVM
  docs/en/stack/ml/df-analytics/ml-dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-shared.asciidoc
Labels: :ml, v8.0.0, v7.15.0, v7.14.1

#1781 [7.x][DOCS] Adds a note about a workaround if DFA model is too large to fit into JVM
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
Labels: :ml, backport, v7.15.0

#1782 [7.14][DOCS] Adds a note about a workaround if DFA model is too large to fit into JVM
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
Labels: :ml, backport, v7.14.1

#1779 [7.x][DOCS] Update file data visualizer permissions (#1719)
  docs/en/stack/ml/setup.asciidoc
Labels: backport

#1780 [7.14][DOCS] Update file data visualizer permissions (#1719)
  docs/en/stack/ml/setup.asciidoc
Labels: backport

#1785 Fixes a bulleted list in DFA overview
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
Labels: :ml, v8.0.0

#1786 [DOCS] Removes File Data Visualizer term
  docs/en/stack/ml/setup.asciidoc
Labels: :ml, v8.0.0, v7.15.0

#1787 [7.x][DOCS] Removes File Data Visualizer term
  docs/en/stack/ml/setup.asciidoc
Labels: backport

#1753 [DOCS] Clean up anomaly detection overview and summary
  docs/en/stack/ml/anomaly-detection/create-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/images/ml-create-job.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-data-recognizer-apm.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-data-recognizer-auditbeat.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-data-recognizer-filebeat.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-data-recognizer-metricbeat.jpg
  docs/en/stack/ml/anomaly-detection/images/ml-data-recognizer-sample.jpg
  docs/en/stack/ml/anomaly-detection/job-tips.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-finding-anomalies.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-overview.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-datafeeds.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-influencers.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-jobs.asciidoc
  docs/en/stack/ml/get-started/ml-gs-forecasts.asciidoc
  docs/en/stack/ml/redirects.asciidoc
Labels: v8.0.0

#1783 [DOCS] Reviews regression docs
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-concepts.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-regression-loss-functions.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-regression.asciidoc
  docs/en/stack/ml/get-started/ml-getting-started.asciidoc
Labels: :ml, v8.0.0

#1793 [DOCS] Update datafeed details in ML docs
  docs/en/stack/ml/anomaly-detection/geographic-anomalies.asciidoc
  docs/en/stack/ml/anomaly-detection/mapping-anomalies.asciidoc
  docs/en/stack/ml/anomaly-detection/stopping-ml.asciidoc
Labels: :ml, v8.0.0, v7.15.0, v7.16.0

#1795 [7.x][DOCS] Update datafeed details in ML docs (#1793)
  docs/en/stack/ml/anomaly-detection/geographic-anomalies.asciidoc
  docs/en/stack/ml/anomaly-detection/mapping-anomalies.asciidoc
  docs/en/stack/ml/anomaly-detection/stopping-ml.asciidoc
Labels: backport

#1796 [7.15][DOCS] Update datafeed details in ML docs (#1793)
  docs/en/stack/ml/anomaly-detection/geographic-anomalies.asciidoc
  docs/en/stack/ml/anomaly-detection/mapping-anomalies.asciidoc
  docs/en/stack/ml/anomaly-detection/stopping-ml.asciidoc
Labels: backport

#1797 [DOCS] Add deleted pages for reorganized content
  docs/en/stack/ml/anomaly-detection/ml-ad-finding-anomalies.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
  docs/en/stack/ml/get-started/ml-gs-jobs.asciidoc
  docs/en/stack/ml/redirects.asciidoc
Labels: :ml, v8.0.0

#1792 [DOCS] Import and export jobs
  docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
  docs/en/stack/ml/move-jobs.asciidoc
Labels: :ml, v8.0.0, v7.15.0, v7.16.0

#1791 [7.x][DOCS] Import and export jobs
  docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
  docs/en/stack/ml/move-jobs.asciidoc
Labels: backport
