Repository elastic/stack-docs, pull requests merged in 2021-12, with the labels that each got.

#1898 ESS is also on Azure
  docs/en/getting-started/get-started-stack.asciidoc
Labels: v7.16.0

#1888 [DOCS] Update Docker getting started for the Stack
  docs/en/getting-started/docker/docker-compose.yml
  docs/en/getting-started/docker/elastic-docker-tls.yml
  docs/en/getting-started/docker/instances.yml
  docs/en/getting-started/get-started-docker.asciidoc
  docs/en/getting-started/index.asciidoc
  docs/en/getting-started/redirects.asciidoc
Labels: :Security, v8.0.0, v8.1.0

#1900 [DOCS] Update Docker getting started for the Stack (#1888)
  docs/en/getting-started/docker/docker-compose.yml
  docs/en/getting-started/docker/elastic-docker-tls.yml
  docs/en/getting-started/docker/instances.yml
  docs/en/getting-started/get-started-docker.asciidoc
  docs/en/getting-started/index.asciidoc
  docs/en/getting-started/redirects.asciidoc
Labels: v8.0.0

#1901 [DOCS] Update 7.16 ES Hadoop breaking changes
  docs/en/install-upgrade/breaking.asciidoc
Labels: v7.16.0

#1902 [DOCS] Uncomment 7.16 ES release highlights
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.16.0

#1903 [DOCS] Adds NLP folders to ML Guide
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
  docs/en/stack/ml/index.asciidoc
  docs/en/stack/ml/nlp/index.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-apis.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-lang-ident.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
  docs/en/stack/ml/nlp/ml-nlp.asciidoc
  docs/en/stack/ml/redirects.asciidoc
Labels: :ml, v8.0.0, v8.1.0

#1904 [8.0][DOCS] Adds NLP folders to ML Guide (#1903)
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
  docs/en/stack/ml/index.asciidoc
  docs/en/stack/ml/nlp/index.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-apis.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-lang-ident.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
  docs/en/stack/ml/nlp/ml-nlp.asciidoc
  docs/en/stack/ml/redirects.asciidoc
Labels: backport

#1908 Adds Extract information page to NLP docs
  docs/en/stack/ml/nlp/index.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-extract-info.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
Labels: :ml, v8.0.0, v8.1.0

#1909 [8.0] Adds Extract information page to NLP docs (#1908)
  docs/en/stack/ml/nlp/index.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-extract-info.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
Labels: backport

#1910 [7.16] Redirects link in Installation & Upgrade. (#1844)
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: backport

#1905 [DOCS] Draft NLP model deployment
  docs/en/stack/ml/nlp/index.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
  docs/en/stack/ml/nlp/ml-nlp.asciidoc
Labels: :ml, v8.0.0, v8.1.0

#1915 [8.0][DOCS] Draft NLP model deployment (#1905)
  docs/en/stack/ml/nlp/index.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
  docs/en/stack/ml/nlp/ml-nlp.asciidoc
Labels: backport

#1907 Updates the Beats breaking changes link
  docs/en/install-upgrade/breaking.asciidoc
Labels: v7.16.0

#1911 Drafts Classify text page for NLP docs
  docs/en/stack/ml/nlp/index.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-classify-text.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-extract-info.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-lang-ident.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
Labels: :ml, v8.0.0, v8.1.0

#1916 [8.0] Drafts Classify text page for NLP docs (#1911)
  docs/en/stack/ml/nlp/index.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-classify-text.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-extract-info.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-lang-ident.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
Labels: :ml, backport, v8.0.0

#1914 Drafts Search and compare section for NLP docs
  docs/en/stack/ml/nlp/index.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-search-compare.asciidoc
Labels: :ml, v8.0.0, v8.1.0

#1917 [8.0] Drafts Search and compare section for NLP docs (#1914)
  docs/en/stack/ml/nlp/index.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-search-compare.asciidoc
Labels: backport

#1919 Update .backportrc.json
  .backportrc.json
Labels: v8.0.0, v8.1.0

#1920 [8.0] Update .backportrc.json (#1919)
  .backportrc.json
Labels: backport

#1921 [7.17] Update .backportrc.json (#1919)
  .backportrc.json
Labels: backport

#1918 [DOCS] Add language identification model details
  docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
Labels: :ml, v8.0.0, v8.1.0

#1922 [DOCS] Add section for enrolling new nodes on Docker
  docs/en/getting-started/get-started-docker.asciidoc
Labels: :Security, v8.0.0, v8.1.0

#1924 [DOCS] Add section for enrolling new nodes on Docker (#1922)
  docs/en/getting-started/get-started-docker.asciidoc
Labels: :Security, v8.0.0

#1906 [DOCS] Update Docker Compose setup
  docs/en/getting-started/docker/.env
  docs/en/getting-started/docker/create-certs.yml
  docs/en/getting-started/docker/docker-compose.yml
  docs/en/getting-started/docker/elastic-docker-tls.yml
  docs/en/getting-started/docker/instances.yml
  docs/en/getting-started/get-started-docker.asciidoc
  docs/en/getting-started/index.asciidoc
Labels: :Security, v8.0.0, v8.1.0

#1925 [8.0] [DOCS] Update Docker Compose setup (#1906)
  docs/en/getting-started/docker/.env
  docs/en/getting-started/docker/create-certs.yml
  docs/en/getting-started/docker/docker-compose.yml
  docs/en/getting-started/docker/elastic-docker-tls.yml
  docs/en/getting-started/docker/instances.yml
  docs/en/getting-started/get-started-docker.asciidoc
  docs/en/getting-started/index.asciidoc
Labels: :Security, v8.0.0

#1923 [8.0][DOCS] Add language identification model details (#1918)
  docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
Labels: backport

#1913 [DOCS] Draft NLP inference
  docs/en/stack/ml/nlp/images/ml-nlp-discover-ner.png
  docs/en/stack/ml/nlp/images/ml-nlp-pipeline-ner.png
  docs/en/stack/ml/nlp/index.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-inference.asciidoc
  docs/en/stack/ml/nlp/ml-nlp.asciidoc
Labels: :ml, v8.0.0, v8.1.0

#1926 [8.0][DOCS] Draft NLP inference (#1913)
  docs/en/stack/ml/nlp/images/ml-nlp-discover-ner.png
  docs/en/stack/ml/nlp/images/ml-nlp-pipeline-ner.png
  docs/en/stack/ml/nlp/index.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-inference.asciidoc
  docs/en/stack/ml/nlp/ml-nlp.asciidoc
Labels: backport

#1927 [DOCS] Adds trained model deployment examples
  docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-inference.asciidoc
Labels: :ml, v8.0.0, v8.1.0

#1929 [DOCS] Adds language identification to NLP inference examples
  docs/en/stack/ml/nlp/images/ml-nlp-discover-lang.png
  docs/en/stack/ml/nlp/images/ml-nlp-pipeline-ner.png
  docs/en/stack/ml/nlp/ml-nlp-inference.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-lang-ident.asciidoc
Labels: :ml, v8.0.0, v8.1.0

#1928 [8.0][DOCS] Adds trained model deployment and language identification examples (#1927)
  docs/en/stack/ml/nlp/images/ml-nlp-discover-lang.png
  docs/en/stack/ml/nlp/images/ml-nlp-pipeline-ner.png
  docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-inference.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-lang-ident.asciidoc
Labels: backport
