Repository elastic/stack-docs, pull requests merged in 2021-11, with the labels that each got.

#1858 [DOCS] Updates ML setup page
  docs/en/stack/ml/assign-job-spaces.jpg
  docs/en/stack/ml/setup.asciidoc
  docs/en/stack/ml/spaces.jpg
Labels: :ml, v8.0.0, v7.16.0, v8.1.0

#1870 [8.0] [DOCS] Updates ML setup page (#1858)
  docs/en/stack/ml/assign-job-spaces.jpg
  docs/en/stack/ml/setup.asciidoc
  docs/en/stack/ml/spaces.jpg
Labels: :ml, backport, v8.0.0

#1871 [7.16] [DOCS] Updates ML setup page (#1858)
  docs/en/stack/ml/assign-job-spaces.jpg
  docs/en/stack/ml/setup.asciidoc
  docs/en/stack/ml/spaces.jpg
Labels: :ml, backport, v7.16.0

#1872 Adds setup page links to sections about ML node setup
  docs/en/stack/ml/anomaly-detection/ml-ad-finding-anomalies.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-outlier-detection.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-regression.asciidoc
Labels: :ml, v8.0.0, v7.16.0, v8.1.0

#1873 [7.16][DOCS] Adds setup page links to sections about ML node setup (#1872)
  docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
Labels: backport

#1874 [8.0][DOCS] Adds setup page links to sections about ML node setup (#1872)
  docs/en/stack/ml/anomaly-detection/ml-ad-finding-anomalies.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-outlier-detection.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-regression.asciidoc
Labels: backport

#1875 [7.15][DOCS] Adds setup page links to sections about ML node setup (#1872)
  docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
Labels: backport

#1878 [DOCS] Update include statements for ES 8.1 breaking changes
  docs/en/install-upgrade/breaking.asciidoc
Labels: v8.1.0

#1877 [DOCS] Update headings for ES 8.0 breaking changes
  docs/en/install-upgrade/breaking.asciidoc
Labels: v8.0.0

#1879 [DOCS] Uncomment include statements for 8.0 ES breaking changes
  docs/en/install-upgrade/breaking.asciidoc
Labels: v8.0.0

#1880 [DOCS] Fixes broken link
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.16.0, v7.15.3

#1881 [7.15][DOCS] Fixes broken link (#1880)
  docs/en/install-upgrade/highlights.asciidoc
Labels: backport

#1883 [DOCS] Updating Stack getting started for security ON
  docs/en/getting-started/get-started-stack.asciidoc
Labels: :Security, v8.0.0, v8.1.0

#1885 [DOCS] Updating Stack getting started for security ON (#1883)
  docs/en/getting-started/get-started-stack.asciidoc
Labels: backport, v8.0.0

#1886 [DOCS] Adds data views to glossary
  docs/en/glossary/glossary.asciidoc
Labels: enhancement

#1887 [DOCS] Update index pattern definition
  docs/en/glossary/glossary.asciidoc
Labels: enhancement

#1890 [DOCS] Fix link to ingest pipelines
  docs/en/stack/ml/df-analytics/ml-dfa-shared.asciidoc
Labels: :ml, v8.0.0, v7.16.0, v8.1.0

#1893 Remove links and references to journalbeat
  docs/en/getting-started/get-started-stack.asciidoc
  docs/en/gke-on-prem/gke-on-prem-deploy-beats.asciidoc
Labels: v8.0.0, v7.16.0, v8.1.0

#1894 [8.0] Remove links and references to journalbeat (#1893)
  docs/en/getting-started/get-started-stack.asciidoc
  docs/en/gke-on-prem/gke-on-prem-deploy-beats.asciidoc
Labels: backport

#1895 [7.16] Remove links and references to journalbeat (#1893)
  docs/en/getting-started/get-started-stack.asciidoc
Labels: backport

#1891 [8.0][DOCS] Fix link to ingest pipelines (#1890)
  docs/en/stack/ml/df-analytics/ml-dfa-shared.asciidoc
Labels: backport

#1892 [7.16][DOCS] Fix link to ingest pipelines (#1890)
  docs/en/stack/ml/df-analytics/ml-inference.asciidoc
Labels: backport

#1897 [DOCS] Adds highlights for Kibana
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.16.0

#1876 Import Cloud upgrade docs
  docs/en/install-upgrade/index.asciidoc
  docs/en/install-upgrade/upgrading-stack-cloud.asciidoc
  docs/en/install-upgrade/upgrading-stack-on-prem.asciidoc
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: v8.0.0, v8.1.0
