Repository elastic/stack-docs, pull requests merged in 2021-07, with the labels that each got.

#1737 [DOCS] Removes classification and regression links from Glossary
  docs/en/glossary/glossary.asciidoc
Labels: :ml, v8.0.0

#1731 [DOCS] Adds anomaly detection resources and advanced concepts sections
  docs/en/siem/detections/machine-learning/machine-learning.asciidoc
  docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-concepts.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-overview.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-resources.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/xpack-ml.asciidoc
  docs/en/stack/ml/get-started/ml-getting-started.asciidoc
  docs/en/stack/ml/redirects.asciidoc
Labels: :ml

#1732 [DOCS] Creates one pager for outlier detection
  docs/en/stack/ml/df-analytics/dfa-outlier-detection.asciidoc
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-outlier-detection.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-shared.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics.asciidoc
Labels: :ml, enhancement, v8.0.0

#1734 [DOCS] Adds feature influence link to glossary
  docs/en/glossary/glossary.asciidoc
Labels: :ml, v8.0.0

#1742 [DOCS] Fixes links to Kibana sample data documentation
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-outlier-detection.asciidoc
Labels: :ml, v7.13.3, v7.14.0, v7.15.0, v8.0.0

#1743 [7.13][DOCS] Fixes links to Kibana sample data documentation (#1742)
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
Labels: backport

#1744 [7.14][DOCS] Fixes links to Kibana sample data documentation (#1742)
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
Labels: backport

#1745 [7.x][DOCS] Fixes links to Kibana sample data documentation (#1742)
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
Labels: backport

#1746 [DOCS] Remove deleted pages
  docs/en/stack/index-landing-all-stack-collapsible.adoc
  docs/en/stack/index-landing-all-stack-docbuild.asciidoc
  docs/en/stack/index-landing-all-stack.adoc
  docs/en/stack/landing-all.asciidoc
  docs/en/stack/landing-observability.asciidoc
  docs/en/stack/landing-search.asciidoc
  docs/en/stack/landing-security.asciidoc
  docs/en/stack/landing-stack.asciidoc
  docs/en/stack/ml/redirects.asciidoc
Labels: :ml, v8.0.0

#1740 [DOCS] Adds sentence about job validation to outlier detection example
  docs/en/stack/ml/df-analytics/ml-dfa-outlier-detection.asciidoc
Labels: :ml, v8.0.0

#1741 [7.x][DOCS] Adds sentence about job validation to examples
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
Labels: :ml, v7.13.3, v7.14.0

#1736 [DOCS] Creates extended classification and regression sections
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/dfanalytics-examples.asciidoc
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-concepts.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-lang-ident.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-outlier-detection.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-shared.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-encoding.asciidoc
  docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
  docs/en/stack/ml/df-analytics/ml-inference.asciidoc
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Labels: :ml, enhancement, v8.0.0

#1738 [DOCS] Adds feature importance links back to Glossary
  docs/en/glossary/glossary.asciidoc
Labels: :ml, v8.0.0

#1747 [DOCS] Summarizes anomaly detection steps
  docs/en/stack/ml/anomaly-detection/create-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/job-tips.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-finding-anomalies.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-troubleshooting.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-restart-failed-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
  docs/en/stack/ml/anomaly-detection/stopping-ml.asciidoc
  docs/en/stack/ml/redirects.asciidoc
Labels: :ml, v8.0.0

#1751 [DOCS] Add redirects for broken links
  docs/en/stack/ml/anomaly-detection/job-tips.asciidoc
  docs/en/stack/ml/redirects.asciidoc
Labels: :ml, v8.0.0

#1752 [DOCS] Adds anchor for anomaly detection job links
  docs/en/stack/ml/anomaly-detection/ml-ad-finding-anomalies.asciidoc
  docs/en/stack/ml/redirects.asciidoc
  docs/en/stack/redirects-landing.adoc
Labels: :ml, v8.0.0

#1750 [DOCS] Moves anomaly detection concepts
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/job-tips.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-finding-anomalies.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-overview.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-buckets.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-calendars.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-concepts.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-datafeeds.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-influencers.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-model-snapshots.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-rules.asciidoc
  docs/en/stack/ml/get-started/ml-gs-results.asciidoc
  docs/en/stack/ml/redirects.asciidoc
Labels: :ml, v8.0.0

#1755 [7.x] [DOCS] Clarifies behavior of datafeeds with or without an end time (#1754)
  docs/en/stack/ml/anomaly-detection/ml-datafeeds.asciidoc
Labels: :ml, backport, enhancement, v7.15.0

#1756 [7.14] [DOCS] Clarifies behavior of datafeeds with or without an end time (#1754)
  docs/en/stack/ml/anomaly-detection/ml-datafeeds.asciidoc
Labels: :ml, backport, enhancement, v7.14.0

#1757 [7.13] [DOCS] Clarifies behavior of datafeeds with or without an end time (#1754)
  docs/en/stack/ml/anomaly-detection/ml-datafeeds.asciidoc
Labels: :ml, backport, enhancement, v7.13.3

#1762 [DOCS] Fine-tunes note in trained models docs
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Labels: :ml, v7.13.3, v7.14.0, v7.15.0, v8.0.0

#1763 [7.x] [DOCS] Fine-tunes note in trained models docs. (#1762)
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Labels: :ml, backport, v7.15.0

#1764 [7.14] [DOCS] Fine-tunes note in trained models docs. (#1762)
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Labels: :ml, backport, v7.14.0

#1765 [7.13] [DOCS] Fine-tunes note in trained models docs. (#1762)
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Labels: :ml, backport, v7.13.3

#1766 [DOCS] Uncomment 7.14 highlights
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.14.0

#1768 [DOCS] Add missing breaking change sections
  docs/en/install-upgrade/breaking.asciidoc
Labels: v8.0.0

#1769 [DOCS] Adds labs to glossary
  docs/en/glossary/glossary.asciidoc
Labels: v8.0.0

#1771 [DOCS] Move Kibana glossary to stack docs
  docs/en/glossary/glossary.asciidoc
Labels: v8.0.0
