Repository elastic/stack-docs, pull requests merged in 2021-10, with the labels that each got.

#1844 Redirects link in Installation & Upgrade
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: v8.0.0

#1839 [DOCS] Add intro; move tutorial
  docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-overview.asciidoc
  docs/en/stack/ml/get-started/ml-getting-started.asciidoc
  docs/en/stack/ml/get-started/ml-gs-forecasts.asciidoc
  docs/en/stack/ml/get-started/ml-gs-jobs.asciidoc
  docs/en/stack/ml/get-started/ml-gs-next.asciidoc
  docs/en/stack/ml/get-started/ml-gs-results.asciidoc
  docs/en/stack/ml/get-started/ml-gs-visualizer.asciidoc
  docs/en/stack/ml/index.asciidoc
  docs/en/stack/ml/machine-learning-intro.asciidoc
  docs/en/stack/ml/redirects.asciidoc
Labels: :ml, v8.0.0

#1850 docs: link to new APM book
  docs/en/getting-started/get-started-docker.asciidoc
  docs/en/glossary/glossary.asciidoc
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/index.asciidoc
  docs/en/install-upgrade/installing-stack.asciidoc
  docs/en/install-upgrade/overview.asciidoc
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: v7.16.0

#1865 [8.0] docs: link to new APM book (#1850)
  docs/en/getting-started/get-started-docker.asciidoc
  docs/en/glossary/glossary.asciidoc
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/index.asciidoc
  docs/en/install-upgrade/installing-stack.asciidoc
  docs/en/install-upgrade/overview.asciidoc
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: backport

#1866 [7.16] docs: link to new APM book (#1850)
  docs/en/getting-started/get-started-docker.asciidoc
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/index.asciidoc
  docs/en/install-upgrade/installing-stack.asciidoc
  docs/en/install-upgrade/overview.asciidoc
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: backport
