Repository elastic/stack-docs, pull requests merged in 2021-01, with the labels that each got.

#1510 [DOCS] Fixes branch in path to module
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
Labels: :ml, v7.10.1, v7.11, v7.12, v8.0.0

#1512 [7.x][DOCS] Fixes branch in path to module (#1510)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
Labels: backport

#1513 [7.11][DOCS] Fixes branch in path to module (#1510)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
Labels: backport

#1514 [7.10][DOCS] Fixes branch in path to module (#1510)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
Labels: backport

#1516 [DOCS] Fix highlights include. Fix coming tags
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.12

#1517 [DOCS] Reuse ES 7.11 highlights and breaking changes
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.11

#1515 [7.11] docs: Ready APM breaking changes
  docs/en/install-upgrade/breaking.asciidoc
Labels: v7.11

#1505 [DOCS] Update Data Visualizer details in machine learning tutorial
  docs/en/stack/ml/get-started/images/ml-gs-data-ip.jpg
  docs/en/stack/ml/get-started/images/ml-gs-data-keyword.jpg
  docs/en/stack/ml/get-started/images/ml-gs-data-metric.jpg
  docs/en/stack/ml/get-started/images/ml-gs-data-timestamp.jpg
  docs/en/stack/ml/get-started/ml-gs-visualizer.asciidoc
Labels: :ml, v7.11, v7.12, v8.0.0

#1518 [7.x][DOCS] Update Data Visualizer details in ML tutorial (#1505)
  docs/en/stack/ml/get-started/images/ml-gs-data-ip.jpg
  docs/en/stack/ml/get-started/images/ml-gs-data-keyword.jpg
  docs/en/stack/ml/get-started/images/ml-gs-data-metric.jpg
  docs/en/stack/ml/get-started/images/ml-gs-data-timestamp.jpg
  docs/en/stack/ml/get-started/ml-gs-visualizer.asciidoc
Labels: backport

#1519 [7.11][DOCS] Update Data Visualizer details in ML tutorial (#1505)
  docs/en/stack/ml/get-started/images/ml-gs-data-ip.jpg
  docs/en/stack/ml/get-started/images/ml-gs-data-keyword.jpg
  docs/en/stack/ml/get-started/images/ml-gs-data-metric.jpg
  docs/en/stack/ml/get-started/images/ml-gs-data-timestamp.jpg
  docs/en/stack/ml/get-started/ml-gs-visualizer.asciidoc
Labels: backport

#1506 [DOCS] Refresh screenshots in machine learning tutorial
  docs/en/stack/ml/get-started/images/ml-gs-annotations.jpg
  docs/en/stack/ml/get-started/images/ml-gs-create-web-jobs-1.jpg
  docs/en/stack/ml/get-started/images/ml-gs-forecast-actual.png
  docs/en/stack/ml/get-started/images/ml-gs-forecast-results.png
  docs/en/stack/ml/get-started/images/ml-gs-forecast.png
  docs/en/stack/ml/get-started/images/ml-gs-job1-analysis.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job1-anomalies.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job2-explorer-anomaly.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job2-explorer-table.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job2-explorer.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job3-explorer.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job4-explorer.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job4-explorer.png
  docs/en/stack/ml/get-started/images/ml-gs-user-annotation.jpg
  docs/en/stack/ml/get-started/images/ml-gs-web-results.jpg
  docs/en/stack/ml/get-started/ml-getting-started.asciidoc
  docs/en/stack/ml/get-started/ml-gs-forecasts.asciidoc
  docs/en/stack/ml/get-started/ml-gs-jobs.asciidoc
  docs/en/stack/ml/get-started/ml-gs-results.asciidoc
Labels: :ml, v7.11, v7.12, v8.0.0

#1520 [7.x][DOCS] Refresh screenshots in machine learning tutorial (#1506)
  docs/en/stack/ml/get-started/images/ml-gs-annotations.jpg
  docs/en/stack/ml/get-started/images/ml-gs-create-web-jobs-1.jpg
  docs/en/stack/ml/get-started/images/ml-gs-forecast-actual.png
  docs/en/stack/ml/get-started/images/ml-gs-forecast-results.png
  docs/en/stack/ml/get-started/images/ml-gs-forecast.png
  docs/en/stack/ml/get-started/images/ml-gs-job1-analysis.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job1-anomalies.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job2-explorer-anomaly.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job2-explorer-table.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job2-explorer.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job3-explorer.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job4-explorer.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job4-explorer.png
  docs/en/stack/ml/get-started/images/ml-gs-user-annotation.jpg
  docs/en/stack/ml/get-started/images/ml-gs-web-results.jpg
  docs/en/stack/ml/get-started/ml-getting-started.asciidoc
  docs/en/stack/ml/get-started/ml-gs-forecasts.asciidoc
  docs/en/stack/ml/get-started/ml-gs-jobs.asciidoc
  docs/en/stack/ml/get-started/ml-gs-results.asciidoc
Labels: backport

#1521 [7.11][DOCS] Refresh screenshots in machine learning tutorial (#1506)
  docs/en/stack/ml/get-started/images/ml-gs-annotations.jpg
  docs/en/stack/ml/get-started/images/ml-gs-create-web-jobs-1.jpg
  docs/en/stack/ml/get-started/images/ml-gs-forecast-actual.png
  docs/en/stack/ml/get-started/images/ml-gs-forecast-results.png
  docs/en/stack/ml/get-started/images/ml-gs-forecast.png
  docs/en/stack/ml/get-started/images/ml-gs-job1-analysis.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job1-anomalies.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job2-explorer-anomaly.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job2-explorer-table.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job2-explorer.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job3-explorer.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job4-explorer.jpg
  docs/en/stack/ml/get-started/images/ml-gs-job4-explorer.png
  docs/en/stack/ml/get-started/images/ml-gs-user-annotation.jpg
  docs/en/stack/ml/get-started/images/ml-gs-web-results.jpg
  docs/en/stack/ml/get-started/ml-getting-started.asciidoc
  docs/en/stack/ml/get-started/ml-gs-forecasts.asciidoc
  docs/en/stack/ml/get-started/ml-gs-jobs.asciidoc
  docs/en/stack/ml/get-started/ml-gs-results.asciidoc
Labels: backport

#1503 [DOCS] Add space limitations for ML objects
  docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
Labels: :ml, v7.11, v7.12, v8.0.0

#1523 [7.x][DOCS] Add space limitations for ML objects (#1503)
  docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
Labels: backport

#1524 [7.11][DOCS] Add space limitations for ML objects (#1503)
  docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
Labels: backport

#1525 [DOCS] Add Kibana breaking changes to Install Upgrade Guide
  docs/en/install-upgrade/breaking.asciidoc
Labels: v7.11

#1522 [DOCS] Expands hyperparameters conceptual docs
  docs/en/stack/ml/df-analytics/hyperparameters.asciidoc
Labels: :ml, v7.12, v8.0.0

#1526 [7.x] [DOCS] Expands hyperparameters conceptual docs (#1522)
  docs/en/stack/ml/df-analytics/hyperparameters.asciidoc
Labels: :ml, backport, v7.12

#1527 [DOCS] Remove unnecessary license details
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: v7.11, v7.12, v8.0.0

#1530 [7.x][DOCS] Remove unnecessary license details
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: backport

#1531 [7.11][DOCS] Remove unnecessary license details
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: backport

#1529 [DOCS] Remove unused installation file
  docs/en/siem/installation.asciidoc
Labels: v7.11, v7.12, v8.0.0

#1533 [7.11][DOCS] Remove unused installation file (#1529)
  docs/en/siem/installation.asciidoc
Labels: backport

#1532 [7.x][DOCS] Remove unused installation file (#1529)
  docs/en/siem/installation.asciidoc
Labels: backport

#1535 Updates instructions on how to import models
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Labels: :ml, v7.11, v7.12, v8.0.0

#1507 [DOCS] Add scatterplot matrix to outlier detection example
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/images/ecommerce-outlier-job-1.png
  docs/en/stack/ml/df-analytics/images/ecommerce-outlier-scatterplot.png
  docs/en/stack/ml/df-analytics/images/ecommerce-transform-preview.png
  docs/en/stack/ml/df-analytics/images/outliers-scatterplot.png
  docs/en/stack/ml/df-analytics/images/outliers.png
Labels: :ml, v7.11, v7.12, v8.0.0

#1536 [7.x] [DOCS] Add scatterplot matrix to outlier detection example (#1507)
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/images/ecommerce-outlier-job-1.png
  docs/en/stack/ml/df-analytics/images/ecommerce-outlier-scatterplot.png
  docs/en/stack/ml/df-analytics/images/ecommerce-transform-preview.png
  docs/en/stack/ml/df-analytics/images/outliers-scatterplot.png
  docs/en/stack/ml/df-analytics/images/outliers.png
Labels: backport

#1537 [7.11] [DOCS] Add scatterplot matrix to outlier detection example (#1507)
  docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
  docs/en/stack/ml/df-analytics/images/ecommerce-outlier-job-1.png
  docs/en/stack/ml/df-analytics/images/ecommerce-outlier-scatterplot.png
  docs/en/stack/ml/df-analytics/images/ecommerce-transform-preview.png
  docs/en/stack/ml/df-analytics/images/outliers-scatterplot.png
  docs/en/stack/ml/df-analytics/images/outliers.png
Labels: backport

#1539 [DOCS] Add scatterplot matrix to classification example
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-classification-scatterplot.png
Labels: :ml, v7.11, v7.12, v8.0.0

#1528 Add known issue for zero memory on Debian 8
  docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
Labels: :ml, v6.8.14, v7.10.2, v7.11, v7.12

#1541 [7.x] Add scatterplot matrix to classification example (#1539)
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-classification-scatterplot.png
Labels: backport

#1542 [7.11] Add scatterplot matrix to classification example (#1539)
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-classification-scatterplot.png
Labels: backport

#1543 [7.11][DOCS] Add known issue for zero memory on Debian 8 (#1528)
  docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
Labels: backport

#1544 [7.10][DOCS] Add known issue for zero memory on Debian 8 (#1528)
  docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
Labels: backport

#1545 [6.8][DOCS] Add known issue for zero memory on Debian 8
  docs/en/stack/ml/anomaly-detection/troubleshooting.asciidoc
Labels: backport

#1538 [DOCS] Add scatterplot matrix to regression example
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/flightdata-regression-scatterplot.png
Labels: :ml, v7.11, v7.12, v8.0.0

#1546 [7.x][DOCS] Add scatterplot matrix to regression example (#1538)
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/flightdata-regression-scatterplot.png
Labels: backport

#1547 [7.11][DOCS] Add scatterplot matrix to regression example (#1538)
  docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
  docs/en/stack/ml/df-analytics/images/flightdata-regression-scatterplot.png
Labels: backport

#1548 [DOCS] Update ML link for ES #68051
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Labels: :ml, v7.12, v8.0.0

#1549 [7.x][DOCS] Update ML link for ES #68051 (#1548)
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Labels: backport
