Repository elastic/stack-docs, pull requests merged in 2021-02, with the labels that each got.

#1540 [DOCS] Adds feature processor conceptual docs to ML book
  docs/en/stack/ml/df-analytics/images/frequency-encoding.jpg
  docs/en/stack/ml/df-analytics/images/ngram-encoding.jpg
  docs/en/stack/ml/df-analytics/images/one-hot-encoding.jpg
  docs/en/stack/ml/df-analytics/images/target-mean-encoding.jpg
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-concepts.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-feature-processors.asciidoc
Labels: :ml, v7.10.2, v7.11, v7.12, v8.0.0

#1552 [7.x] [DOCS] Adds feature processor conceptual docs to ML book (#1540)
  docs/en/stack/ml/df-analytics/images/frequency-encoding.jpg
  docs/en/stack/ml/df-analytics/images/ngram-encoding.jpg
  docs/en/stack/ml/df-analytics/images/one-hot-encoding.jpg
  docs/en/stack/ml/df-analytics/images/target-mean-encoding.jpg
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-concepts.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-feature-processors.asciidoc
Labels: :ml, backport, v7.12

#1553 [7.11] [DOCS] Adds feature processor conceptual docs to ML book (#1540)
  docs/en/stack/ml/df-analytics/images/frequency-encoding.jpg
  docs/en/stack/ml/df-analytics/images/ngram-encoding.jpg
  docs/en/stack/ml/df-analytics/images/one-hot-encoding.jpg
  docs/en/stack/ml/df-analytics/images/target-mean-encoding.jpg
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-concepts.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-feature-processors.asciidoc
Labels: :ml, backport, v7.11

#1554 [7.10] [DOCS] Adds feature processor conceptual docs to ML book (#1540)
  docs/en/stack/ml/df-analytics/images/frequency-encoding.jpg
  docs/en/stack/ml/df-analytics/images/ngram-encoding.jpg
  docs/en/stack/ml/df-analytics/images/one-hot-encoding.jpg
  docs/en/stack/ml/df-analytics/images/target-mean-encoding.jpg
  docs/en/stack/ml/df-analytics/index.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-concepts.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-feature-processors.asciidoc
Labels: :ml, backport, v7.10.2

#1551 [DOCS] Add the HLRC to the list. Closes #1550
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: enhancement

#1557 [DOCS] Add the HLRC to the list. Closes #1550 (#1551)
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: backport

#1556 [DOCS] Add the HLRC to the list. Closes #1550 (#1551)
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: backport

#1558 [DOCS] Add Kibana highlights to Install & Upgrade Guide
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.11

#1504 [DOCS] Adds security_linux and security_windows modules
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Labels: :ml, v7.11, v7.12, v8.0.0

#1561 [7.x][DOCS] Adds security_linux and security_windows modules (#1504)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Labels: backport

#1562 [7.11][DOCS] Adds security_linux and security_windows modules (#1504)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Labels: backport

#1560 Add Beats breaking changes to installation and upgrade guide
  docs/en/install-upgrade/breaking.asciidoc
Labels: v7.11

#1559 [DOCS] Remove unneeded ports from `docker-compose.yml` example
  docs/en/getting-started/docker/docker-compose.yml
Labels: v7.10.2, v7.11, v7.12, v8.0.0

#1564 [7.x] [DOCS] Remove unneeded ports from `docker-compose.yml` example (#1559)
  docs/en/getting-started/docker/docker-compose.yml
Labels: backport, v7.12

#1565 [7.11] [DOCS] Remove unneeded ports from `docker-compose.yml` example (#1559)
  docs/en/getting-started/docker/docker-compose.yml
Labels: backport, v7.11

#1566 [7.10] [DOCS] Remove unneeded ports from `docker-compose.yml` example (#1559)
  docs/en/getting-started/docker/docker-compose.yml
Labels: backport, v7.10.2

#1563 [DOCS] Adds link of Jupyter notebook about class assignment objective to classification docs
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
Labels: :ml, v7.10.2, v7.11, v7.12, v8.0.0

#1567 [7.x] [DOCS] Adds link of Jupyter notebook about class assignment objective to classification docs (#1563)
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
Labels: backport

#1568 [7.11] [DOCS] Adds link of Jupyter notebook about class assignment objective to classification docs (#1563)
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
Labels: backport

#1569 [7.10] [DOCS] Adds link of Jupyter notebook about class assignment objective to classification docs (#1563)
  docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
Labels: backport

#1574 [DOCS] Adds blog post links to DFA examples page
  docs/en/stack/ml/df-analytics/dfanalytics-examples.asciidoc
Labels: :ml, v7.11.1, v7.12, v8.0.0

#1575 [7.x] [DOCS] Adds blog post links to DFA examples page. (#1574)
  docs/en/stack/ml/df-analytics/dfanalytics-examples.asciidoc
Labels: :ml, backport, v7.12

#1576 [7.11] [DOCS] Adds blog post links to DFA examples page. (#1574)
  docs/en/stack/ml/df-analytics/dfanalytics-examples.asciidoc
Labels: :ml, backport, v7.11.1

#1577 [DOCS] Add EQL glossary def
  docs/en/glossary/glossary.asciidoc
Labels: v8.0.0

#1572 [DOCS] Address feedback on ML troubleshooting
  docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
Labels: :ml, v7.11.1, v7.12

#1578 [7.11][DOCS] Address feedback on ML troubleshooting (#1572)
  docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
Labels: backport

#1579 [7.10][DOCS] Address feedback on ML troubleshooting (#1572)
  docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
Labels: backport

#1580 [7.9][DOCS] Address feedback on ML troubleshooting (#1572)
  docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
Labels: backport

#1581 [DOCS] Fixes n-gram terminology
  docs/en/stack/ml/df-analytics/ml-dfa-feature-processors.asciidoc
Labels: :ml, v7.12, v8.0.0

#1582 [7.x][DOCS] Fixes n-gram terminology (#1581)
  docs/en/stack/ml/df-analytics/ml-dfa-feature-processors.asciidoc
Labels: backport

#1584 [DOCS] Adds custom rules to glossary
  docs/en/glossary/glossary.asciidoc
Labels: v8.0.0

#1585 [DOCS] Adds screenshot and short explanation on ROC curve in classification example
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-classification-roc-curve.jpg
Labels: :ml, v7.12, v7.13, v8.0.0

#1573 [DOCS] Adds anomaly detection alert config docs to ML book
  docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc
  docs/en/stack/ml/anomaly-detection/index.asciidoc
Labels: :ml, v7.12, v8.0.0

#1588 [7.x] [DOCS] Adds anomaly detection alert config docs to ML book (#1573)
  docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc
  docs/en/stack/ml/anomaly-detection/index.asciidoc
Labels: :ml, backport, v7.13

#1589 [7.12] [DOCS] Adds anomaly detection alert config docs to ML book (#1573)
  docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc
  docs/en/stack/ml/anomaly-detection/index.asciidoc
Labels: :ml, backport, v7.12

#1586 [7.x] [DOCS] Adds screenshot and short explanation on ROC curve in classification example (#1585)
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-classification-roc-curve.jpg
Labels: :ml, backport, v7.13

#1587 [7.12] [DOCS] Adds screenshot and short explanation on ROC curve in classification example (#1585)
  docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
  docs/en/stack/ml/df-analytics/images/flights-classification-roc-curve.jpg
Labels: :ml, backport, v7.12

#1591 [DOCS] Link to trained model aliases API
  docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
Labels: :ml, v7.13.0, v8.0.0

#1593 [DOCS] Expands inference conceptual with a note about aliases
  docs/en/stack/ml/df-analytics/ml-inference.asciidoc
Labels: :ml, v7.13.0, v8.0.0

#1594 [7.x] [DOCS] Expands inference conceptual with a note about aliases. (#1593)
  docs/en/stack/ml/df-analytics/ml-inference.asciidoc
Labels: :ml, backport, v7.13.0
