Repository elastic/stack-docs, pull requests merged in 2022-04, with the labels that each got.

#2094 [8.3] Update upgrading-stack.asciidoc (#2092)
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: backport-skip, v8.3.0

#2097 [8.0] Update upgrading-stack.asciidoc (#2092)
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: backport-skip, v8.0.2

#2101 Removes outdated DFA limitation
  docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
Labels: :ml, v8.2.0, backport-8.2, v8.3.0

#2095 [8.2] Update upgrading-stack.asciidoc (#2092)
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: v8.2.0, backport-skip

#2096 [DOCS] Update certificate path in Docker installation
  docs/en/getting-started/get-started-docker.asciidoc
Labels: v8.2.0, v8.0.1, backport-8.1, backport-8.0, backport-8.2, v8.1.3, v8.3.0

#2110 [DOCS] Comment out incomplete 8.2 links
  docs/en/install-upgrade/breaking.asciidoc
Labels: v8.2.0, backport-skip

#2111 [DOCs] Uncomment Elasticsearch breaking changes
  docs/en/install-upgrade/breaking.asciidoc
Labels: v8.2.0, backport-skip

#2100 [DOCS] Sync saved objects when deploying model
  docs/en/stack/ml/assign-job-spaces.jpg
  docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
  docs/en/stack/ml/setup.asciidoc
Labels: :ml, v8.2.0, backport-8.2, v8.3.0

#2116 Add Beats 8.2 BCs
  docs/en/install-upgrade/breaking.asciidoc
Labels: v8.2.0

#2112 [ML] show expected model outputs for each nlp task type
  docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
Labels: :ml, v8.2.0, backport-8.2, v8.3.0

#2119 [DOCS] Testing trained models in UI
  docs/en/stack/ml/nlp/images/ml-nlp-test-lang-ident.png
  docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
Labels: :ml, v8.2.0, backport-8.2, v8.3.0
