Repository elastic/stack-docs, pull requests merged in 2022-06, with the labels that each got.

#2152 [DOCS] Clean up 8.3 breaking change links
  docs/en/install-upgrade/breaking.asciidoc
Labels: backport-skip, v8.3.0

#2153 Add Farsi NER model to list of supported NLP models
  docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
Labels: :ml, backport-skip, v8.4.0

#2154 Improves readability on NLP model reference page
  docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
Labels: :ml, v8.3.0, backport-8.3, v8.4.0

#2158 [DOCS] Address linting issues
  docs/en/glossary/glossary.asciidoc
  docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc
  docs/en/stack/ml/anomaly-detection/geographic-anomalies.asciidoc
  docs/en/stack/ml/anomaly-detection/mapping-anomalies.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-outlier-detection.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfanalytics.asciidoc
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-lang-ident.asciidoc
Labels: :ml, backport-8.3, v8.4.0, v8.3.1

#2160 Fixes grammar based on linting tool results in NLP docs
  docs/en/stack/ml/nlp/ml-nlp-classify-text.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-inference.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-lang-ident.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-search-compare.asciidoc
Labels: :ml, backport-8.2, v8.2.1, backport-8.3, v8.4.0, v8.3.1

#2164 [DOCS] Removed reference to Stack GS
  docs/en/gke-on-prem/gke-on-prem-deploy-beats.asciidoc
  docs/en/gke-on-prem/gke-on-prem-introduction.asciidoc
Labels: v8.3.0, backport-8.3

#2163 Activate include for Beats breaking changes
  docs/en/install-upgrade/breaking.asciidoc
Labels: v8.3.0

#2156 Adds guide about how to revert to a model snapshot
  docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc
  docs/en/stack/ml/anomaly-detection/images/anomaly-job-model-snapshots.jpg
  docs/en/stack/ml/anomaly-detection/images/revert-model-snapshot.jpg
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-revert-model-snapshot.asciidoc
Labels: :ml, backport-8.2, v8.3.0, v8.2.1, backport-8.3, v8.4.0

#2172 [DOCS] Changes NLP examples to use proper JSON structure and objects
  docs/en/stack/ml/nlp/ml-nlp-classify-text.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-extract-info.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-search-compare.asciidoc
Labels: :ml, backport-8.3, v8.4.0, v8.3.1
