Repository elastic/stack-docs, pull requests merged in 2022-12, with the labels that each got.

#2274 [DOCS] Add comments for automated screenshots
  docs/en/stack/ml/anomaly-detection/geographic-anomalies.asciidoc
  docs/en/stack/ml/anomaly-detection/mapping-anomalies.asciidoc
Labels: :ml, v8.7.0, backport-8.6, v8.6.1

#2280 [8.6][DOCS] Removes reference to semantic search docs
  docs/en/stack/ml/nlp/ml-nlp-apis.asciidoc
Labels: :ml, v8.6.0

#2282 [DOCS] Stop a single node
  docs/en/install-upgrade/upgrading-elasticsearch.asciidoc
Labels: v8.5.0, backport-8.5

#2285 Add Cloud entries to shared glossary
  docs/en/glossary/terms/allocator-affinity.asciidoc
  docs/en/glossary/terms/allocator-tag.asciidoc
  docs/en/glossary/terms/console.asciidoc
  docs/en/glossary/terms/data-center.asciidoc
  docs/en/glossary/terms/deployment-template.asciidoc
  docs/en/glossary/terms/deployment.asciidoc
  docs/en/glossary/terms/ece.asciidoc
  docs/en/glossary/terms/eck.asciidoc
  docs/en/glossary/terms/elastic-stack.asciidoc
  docs/en/glossary/terms/elasticsearch-service.asciidoc
  docs/en/glossary/terms/hardware-profile.asciidoc
  docs/en/glossary/terms/host-runner.asciidoc
  docs/en/glossary/terms/instance-configuration.asciidoc
  docs/en/glossary/terms/instance-type.asciidoc
  docs/en/glossary/terms/instance.asciidoc
  docs/en/glossary/terms/kibana.asciidoc
  docs/en/glossary/terms/no-op.asciidoc
  docs/en/glossary/terms/solution.asciidoc
  docs/en/glossary/terms/vcpu.asciidoc
Labels: backport-skip

#2288 [DOCS] Add detections and alerts terminology
  docs/en/glossary/terms/action.asciidoc
  docs/en/glossary/terms/custom-rule.asciidoc
  docs/en/glossary/terms/detection-alert.asciidoc
  docs/en/glossary/terms/detection-rule.asciidoc
  docs/en/glossary/terms/elastic-security-indices.asciidoc
  docs/en/glossary/terms/endpoint-exception.asciidoc
  docs/en/glossary/terms/exception.asciidoc
  docs/en/glossary/terms/external-alert.asciidoc
  docs/en/glossary/terms/indicator-index.asciidoc
  docs/en/glossary/terms/kibana-privilege.asciidoc
  docs/en/glossary/terms/stack-alerts.asciidoc
  docs/en/glossary/terms/stack-rule.asciidoc
Labels: backport-skip, v8.7.0

#2277 Updates the Kibana bc links for 8.6
  docs/en/install-upgrade/breaking.asciidoc
Labels: backport-skip, v8.6.0
