Repository elastic/stack-docs, pull requests merged in 2022-01, with the labels that each got.

#1931 [Backport] [8.0] [1876] Import Cloud upgrade docs
  docs/en/install-upgrade/index.asciidoc
  docs/en/install-upgrade/upgrading-stack-cloud.asciidoc
  docs/en/install-upgrade/upgrading-stack-on-prem.asciidoc
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: v8.0.0

#1932 Minor fixup for Cloud upgrade steps
  docs/en/install-upgrade/upgrading-stack-cloud.asciidoc
Labels: v8.0.0

#1933 [Backport] [8.0] [1932]Minor fixup for Cloud upgrade steps
  docs/en/install-upgrade/upgrading-stack-cloud.asciidoc
Labels: v8.0.0

#1936 Use ess-leadin-short shared attr
  docs/en/install-upgrade/installing-stack.asciidoc
Labels: v7.16.2

#1935 [DOCS] Add 8.0 ES breaking changes for plugins and SQL JDBC
  docs/en/install-upgrade/breaking.asciidoc
Labels: v8.0.0

#1930 [DOC] explicate confidence interval on single metrics viewer
  docs/en/stack/ml/get-started/ml-gs-results.asciidoc
Labels: :ml, v8.0.0, v8.1.0, v7.17

#1937 [8.0][DOC] explicate confidence interval on single metrics viewer (#1930)
  docs/en/stack/ml/get-started/ml-gs-results.asciidoc
Labels: backport

#1938 [7.17][DOC] explicate confidence interval on single metrics viewer (#1930)
  docs/en/stack/ml/get-started/ml-gs-results.asciidoc
Labels: backport

#1939 Address comments from Cloud upgrade docs review
  docs/en/install-upgrade/upgrading-stack-cloud.asciidoc
Labels: v8.0.0, v8.1.0

#1940 [Backport] [8.0] [1939]Address comments from Cloud upgrade docs review
  docs/en/install-upgrade/upgrading-stack-cloud.asciidoc
Labels: v8.0.0

#1934 [ML] Adds common problems to NLP pipelines docs and add on_failure example
  docs/en/stack/ml/nlp/images/ml-nlp-pipeline-lang.png
  docs/en/stack/ml/nlp/ml-nlp-inference.asciidoc
Labels: :ml, v8.0.0, v8.1.0

#1941 [8.0] Adds common problems to NLP pipelines docs and add on_failure example
  docs/en/stack/ml/nlp/images/ml-nlp-pipeline-lang.png
  docs/en/stack/ml/nlp/ml-nlp-inference.asciidoc
Labels: backport

#1944 Update ml-nlp-lang-ident with zxx special case
  docs/en/stack/ml/nlp/ml-nlp-lang-ident.asciidoc
Labels: :ml, v8.1.0

#1945 Revert anomaly detection part to chapter
  docs/en/stack/ml/anomaly-detection/ml-ad-overview.asciidoc
Labels: :ml, v8.0.0, v8.1.0

#1946 [8.0] Revert anomaly detection part to chapter (#1945)
  docs/en/stack/ml/anomaly-detection/ml-ad-overview.asciidoc
Labels: backport

#1947 [DOCS] Update Kibana 7.17 highlights
  docs/en/install-upgrade/highlights.asciidoc
Labels: v7.17

#1948 [DOCS] Updates breaking changes in Install Upgrade Guidie
  docs/en/install-upgrade/breaking.asciidoc
Labels: v7.17

#1943 [DOCS] Split anomaly detection into multiple pages
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-algorithms.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-concepts.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-finding-anomalies.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-forecast.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-overview.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-plan.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-run-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-view-results.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-outlier-detection.asciidoc
  docs/en/stack/ml/redirects.asciidoc
Labels: :ml, v8.0.0, v8.1.0

#1950 [8.0][DOCS] Split anomaly detection into multiple pages (#1943)
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-algorithms.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-concepts.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-finding-anomalies.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-forecast.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-plan.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-run-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-view-results.asciidoc
Labels: backport

#1951 [DOCS] Removes APM NodeJS and RUM Javascript modules
  docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
Labels: :ml, v8.0.0, v8.1.0

#1953 [8.0][DOCS] Removes APM NodeJS and RUM Javascript modules (#1951)
  docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
Labels: backport

#1868 Adds image to classification page
  docs/en/stack/ml/df-analytics/images/classification-vis.png
  docs/en/stack/ml/df-analytics/ml-dfa-classification.asciidoc
Labels: :ml, v8.0.0, v8.1.0

#1956 [8.0] Adds image to classification page (#1868)
  docs/en/stack/ml/df-analytics/images/classification-vis.png
  docs/en/stack/ml/df-analytics/ml-dfa-classification.asciidoc
Labels: :ml, backport, v8.0.0

#1957 Updates screenshots in DFA docs
  docs/en/stack/ml/df-analytics/images/flights-classification-details.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-details.png
  docs/en/stack/ml/df-analytics/images/flights-classification-job-1.jpg
  docs/en/stack/ml/df-analytics/images/flights-classification-results.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-details.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-job-1.jpg
  docs/en/stack/ml/df-analytics/images/flights-regression-results.jpg
  docs/en/stack/ml/df-analytics/images/trained-model-management.jpg
  docs/en/stack/ml/df-analytics/images/weblog-outlier-job-1.jpg
  docs/en/stack/ml/df-analytics/ml-dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-outlier-detection.asciidoc
Labels: :ml, v8.1.0

#1949 [DOCS] Fix link to Kibana 7.17 release notes
  docs/en/install-upgrade/breaking.asciidoc
Labels: v7.17
