Repository elastic/stack-docs, pull requests merged in 2022-02, with the labels that each got.

#1954 [DOCS] Update APM transaction module description
  docs/en/stack/ml/anomaly-detection/images/link.svg
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
Labels: :ml, v8.0.0, v8.1.0

#1961 [8.0][DOCS] Update APM transaction module description (#1954)
  docs/en/stack/ml/anomaly-detection/images/link.svg
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
Labels: backport

#1963 [DOCS] Restructure Apache job list as table with links
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
Labels: :ml, v8.0.0, v8.1.0

#1965 [8.0][DOCS] Restructure Apache job list as table with links (#1963)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
Labels: backport

#1971 [8.1][DOCS] Restructure Apache job list as table with links (#1963)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
Labels: backport

#1972 [DOCS] Comment out ES migration guide
  docs/en/install-upgrade/breaking.asciidoc
Labels: v8.2.0

#1959 Activate Beats breaking changes include
  docs/en/install-upgrade/breaking.asciidoc
Labels: v7.17

#1977 [DOCS] Updated link to Kibana
  docs/en/install-upgrade/upgrading-kibana.asciidoc
Labels: v8.0.0, v8.1.0, v8.2.0

#1978 [DOCS] Updated link to Kibana (#1977)
  docs/en/install-upgrade/upgrading-kibana.asciidoc
Labels: backport

#1979 [DOCS] Updated link to Kibana (#1977)
  docs/en/install-upgrade/upgrading-kibana.asciidoc
Labels: backport

#1980 [DOCS] Add note about API compat mode.
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: v8.0.0, v8.1.0, v8.2.0

#1981 [DOCS] Add note about API compat mode. (#1980)
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: backport

#1982 [DOCS] Add note about API compat mode. (#1980)
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: backport

#1983 [DOCS] Temporarily removed link to API compat topic
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: v8.0.0

#1985 Re-add link to API compat topic
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: v8.0.0

#1986 [DOCS] Fix link in Stack Upgrade Guide
  docs/en/install-upgrade/upgrading-elasticsearch.asciidoc
Labels: v8.0.0, v8.1.0, v8.2.0

#1987 [8.1] [DOCS] Fix link in Stack Upgrade Guide (#1986)
  docs/en/install-upgrade/upgrading-elasticsearch.asciidoc
Labels: backport

#1988 [8.0] [DOCS] Fix link in Stack Upgrade Guide (#1986)
  docs/en/install-upgrade/upgrading-elasticsearch.asciidoc
Labels: backport

#1990 [DOCS] Link to the 7.17 upgrade assistant docs
  docs/en/glossary/glossary.asciidoc
  docs/en/install-upgrade/upgrading-stack-cloud.asciidoc
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: v8.0.0, v8.1.0, v8.2.0

#1991 [main] [DOCS] Link to the 7.17 upgrade assistant docs (#1990)
  docs/en/glossary/glossary.asciidoc
  docs/en/install-upgrade/upgrading-stack-cloud.asciidoc
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: backport

#1992 [8.1] [DOCS] Link to the 7.17 upgrade assistant docs (#1990)
  docs/en/glossary/glossary.asciidoc
  docs/en/install-upgrade/upgrading-stack-cloud.asciidoc
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: backport

#1994 [DOCS] Restructure Auditbeat jobs in tables
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
Labels: :ml, v8.0.0, v8.1.0, v8.2.0

#1998 Update upgrading-stack-cloud.asciidoc
  docs/en/install-upgrade/upgrading-stack-cloud.asciidoc
Labels: v8.0.0, v8.1.0, v8.2.0

#1995 [8.1][DOCS] Restructure Auditbeat jobs in tables (#1994)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
Labels: backport

#1996 [8.0][DOCS] Restructure Auditbeat jobs in tables (#1994)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
Labels: backport

#1999 [DOCS] Restructures log jobs in table
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc
Labels: :ml, v8.0.0, v8.1.0, v8.2.0

#2000 [8.1][DOCS] Update upgrading-stack-cloud.asciidoc (#1998)
  docs/en/install-upgrade/upgrading-stack-cloud.asciidoc
Labels: backport

#2001 [8.0][DOCS] Update upgrading-stack-cloud.asciidoc (#1998)
  docs/en/install-upgrade/upgrading-stack-cloud.asciidoc
Labels: backport

#1997 Update upgrading-kibana.asciidoc
  docs/en/install-upgrade/upgrading-kibana.asciidoc
Labels: v8.0.0, v8.1.0, v8.2.0

#2003 [8.1][DOCS] Restructures log jobs in table (#1999)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc
Labels: backport

#2002 [DOCS] Restructures Metricbeat jobs in table
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
Labels: :ml, v8.0.0, v8.1.0, v8.2.0

#2007 [8.1][DOCS] Update upgrading-kibana.asciidoc (#1997)
  docs/en/install-upgrade/upgrading-kibana.asciidoc
Labels: backport

#2008 [8.0][DOCS] Update upgrading-kibana.asciidoc (#1997)
  docs/en/install-upgrade/upgrading-kibana.asciidoc
Labels: backport

#2004 [8.0][DOCS] Restructures log jobs in table (#1999)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc
Labels: backport

#2006 [DOCS] Restructures Metrics jobs in table
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc
Labels: :ml, v8.0.0, v8.1.0, v8.2.0

#2009 [DOCS] Restructures Nginx jobs in table
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
Labels: :ml, v8.0.0, v8.1.0, v8.2.0

#2013 [8.1][DOCS] Restructures Metrics jobs in table (#2006)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc
Labels: backport

#2014 [8.0][DOCS] Restructures Metrics jobs in table (#2006)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc
Labels: backport

#2010 [8.1][DOCS] Restructures Metricbeat jobs in table (#2002)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
Labels: backport

#2011 [8.0][DOCS] Restructures Metricbeat jobs in table (#2002)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
Labels: backport

#2015 [8.1][DOCS] Restructures Nginx jobs in table
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
Labels: backport

#2016 [8.0][DOCS] Restructures Nginx jobs in table
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
Labels: backport

#2012 [DOCS] Restructures Uptime jobs in table
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
Labels: :ml, v8.0.0, v8.1.0, v8.2.0

#2020 Update highlights.asciidoc
  docs/en/install-upgrade/highlights.asciidoc
Labels: v8.0.0

#2017 [8.1][DOCS] Restructures Uptime jobs in table (#2012)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
Labels: backport

#1974 [DOCS] Fixes Kibana 8.0.0 breaking changes
  docs/en/install-upgrade/breaking.asciidoc
Labels: v8.0.0

#2018 [8.0][DOCS] Restructures Uptime jobs in table (#2012)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
Labels: backport

#2005 [DOCS] Fixes Kibana 8.0.0 breaking changes
  docs/en/install-upgrade/breaking.asciidoc
Labels: v8.0.0

#2021 Remove Homebrew instructions from getting started docs
  docs/en/getting-started/get-started-stack.asciidoc
Labels: v8.0.0

#2022 [8.1] Remove Homebrew instructions from getting started docs (#2021)
  docs/en/getting-started/get-started-stack.asciidoc
Labels: backport

#2023 [8.0] Remove Homebrew instructions from getting started docs (#2021)
  docs/en/getting-started/get-started-stack.asciidoc
Labels: backport

#2024 [DOCS] Re-add anchor for stack upgrade order
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: v8.0.0, v8.1.0, v8.2.0

#2025 [8.1] [DOCS] Re-add anchor for stack upgrade order (#2024)
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: backport

#2026 [8.0] [DOCS] Re-add anchor for stack upgrade order (#2024)
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: backport

#2028 [DOCS] Fix CCS cluster compatibility
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: v8.0.0, v8.1.0, v8.2.0

#2029 [8.1] Fix CCS cluster compatibility (#2028)
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: backport, v8.1.0

#2030 [8.0] Fix CCS cluster compatibility (#2028)
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: backport

#2031 [DOCS] Omit link to logging config changes
  docs/en/install-upgrade/upgrading-kibana.asciidoc
Labels: v8.1.0, v8.2.0, v8.0.1

#2033 [8.0][DOCS] Omit link to logging config changes
  docs/en/install-upgrade/upgrading-kibana.asciidoc
Labels: backport

#2034 [8.1] [DOCS] Fixes Kibana breaking changes links
  docs/en/install-upgrade/breaking.asciidoc
Labels: v8.1.0

#1955 [DOCS] Restructures reference for preconfigured security jobs
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Labels: :ml, v8.1.0, v8.2.0, v8.0.1

#2035 [8.1][DOCS] Restructures reference for preconfigured security jobs (#1955)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Labels: backport

#2036 [8.0][DOCS] Restructures reference for preconfigured security jobs (#1955)
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Labels: backport

#2027 [DOCS] Remove anchor from upgrade docs
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: v8.0.0, v8.1.0, v8.2.0

#2037 [8.1] [DOCS] Remove anchor from upgrade docs (#2027)
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: backport

#2038 [main] [DOCS] Remove anchor from upgrade docs (#2027)
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: backport

#1989 [DOCS] Add list of supported NLP model architectures
  docs/en/stack/ml/nlp/index.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-resources.asciidoc
Labels: :ml, v8.1.0, v8.2.0

#2042 Update upgrading-kibana.asciidoc
  docs/en/install-upgrade/upgrading-kibana.asciidoc
Labels: v8.2.0

#2044 [8.0] Update upgrading-kibana.asciidoc
  docs/en/install-upgrade/upgrading-kibana.asciidoc
Labels: v8.0.0

#2040 [8.1][DOCS] Add list of supported NLP model architectures (#1989)
  docs/en/stack/ml/nlp/index.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-resources.asciidoc
Labels: backport

#2041 [8.0][DOCS] Add list of supported NLP model architectures (#1989)
  docs/en/stack/ml/nlp/index.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-resources.asciidoc
Labels: backport

#2047 Augments the readme
  README.md
Labels: v8.2.0

#2048 [8.1] Augments the readme (#2047)
  README.md
Labels: backport

#2049 [8.0] Augments the readme (#2047)
  README.md
Labels: backport

#2051 [DOCS] Fix links to ML APIs - part 1
  docs/en/stack/ml/anomaly-detection/ml-api-quickref.asciidoc
Labels: :ml, v8.2.0, v8.0.1, v8.1.1

#2052 [8.1][DOCS] Fix links to ML APIs - part 1 (#2051)
  docs/en/stack/ml/anomaly-detection/ml-api-quickref.asciidoc
Labels: backport

#2053 [8.0][DOCS] Fix links to ML APIs - part 1 (#2051)
  docs/en/stack/ml/anomaly-detection/ml-api-quickref.asciidoc
Labels: backport

#2050 [DOCS] Fix links to ML APIs
  docs/en/stack/ml/anomaly-detection/ml-api-quickref.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-calendars.asciidoc
Labels: :ml, v8.2.0, v8.0.1, v8.1.1

#2054 [8.1][DOCS] Fix links to ML APIs (#2050)
  docs/en/stack/ml/anomaly-detection/ml-api-quickref.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-calendars.asciidoc
Labels: backport

#2055 [8.0][DOCS] Fix links to ML APIs (#2050)
  docs/en/stack/ml/anomaly-detection/ml-api-quickref.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-calendars.asciidoc
Labels: backport

#2059 [8.0] [DOCS] Add Elastic Security breaking changes to Installation and Upgrade Guide (#2039)
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/index.asciidoc
Labels: backport

#2058 [8.1] [DOCS] Add Elastic Security breaking changes to Installation and Upgrade Guide (#2039)
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/index.asciidoc
Labels: backport

#2062 [8.0] [DOCS] Update upgrade steps for minor/patch releases (#2057)
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/upgrading-elasticsearch.asciidoc
  docs/en/install-upgrade/upgrading-kibana.asciidoc
  docs/en/install-upgrade/upgrading-stack-cloud.asciidoc
  docs/en/install-upgrade/upgrading-stack-on-prem.asciidoc
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: backport, v8.0.1

#2061 [8.1] [DOCS] Update upgrade steps for minor/patch releases (#2057)
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/upgrading-elasticsearch.asciidoc
  docs/en/install-upgrade/upgrading-kibana.asciidoc
  docs/en/install-upgrade/upgrading-stack-cloud.asciidoc
  docs/en/install-upgrade/upgrading-stack-on-prem.asciidoc
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: backport

#2056 [DOCS] Remove ES Hadoop breaking changes in 8.1+
  docs/en/install-upgrade/breaking.asciidoc
  docs/en/install-upgrade/redirects.asciidoc
Labels: v8.2.0, v8.1.1

#2046 [DOCS] Add Elastic Security highlights to Installation and Upgrade Guide
  docs/en/install-upgrade/highlights.asciidoc
Labels: v8.0.0, v8.1.0

#2065 [8.0] [DOCS] Add Elastic Security highlights to Installation and Upgrade Guide (#2046)
  docs/en/install-upgrade/highlights.asciidoc
Labels: backport

#2064 [8.1] [DOCS] Add Elastic Security highlights to Installation and Upgrade Guide (#2046)
  docs/en/install-upgrade/highlights.asciidoc
Labels: backport

#2019 Update ootb-ml-jobs-siem.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Labels: :ml, v7.17, backport-skip

#2068 [DOCS] Minor typos on get-started-stack.asciidoc (#1973)
  docs/en/getting-started/get-started-stack.asciidoc
Labels: v8.1.0, v8.2.0, v8.0.1, backport-8.1, backport-8.0

#2069 [DOCS] Pull Getting Started Docker files from elasticsearch repo
  docs/en/getting-started/docker/.env
  docs/en/getting-started/docker/docker-compose.yml
  docs/en/getting-started/get-started-docker.asciidoc
Labels: v8.1.0, v8.2.0, v8.0.1, backport-8.1, backport-8.0
