Repository elastic/stack-docs, pull requests merged in 2022-09, with the labels that each got.

#2223 Adds text similarity task to the NLP docs
  docs/en/stack/ml/nlp/ml-nlp-classify-text.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-search-compare.asciidoc
Labels: :ml, backport-skip, v8.5.0

#2222 Updates classification conceptual docs
  docs/en/stack/ml/df-analytics/ml-dfa-classification.asciidoc
Labels: :ml, backport-skip, v8.5.0

#2221 [DOCS] Improves influencer documentation
  docs/en/stack/ml/anomaly-detection/ml-influencers.asciidoc
Labels: :ml, backport-8.4, v8.5.0, v8.4.2

#2181 [DOCS] Reworks the Examples section in anomaly detection docs
  docs/en/stack/ml/anomaly-detection/anomaly-how-tos.asciidoc
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-concepts.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-overview.asciidoc
  docs/en/stack/ml/get-started/ml-gs-forecasts.asciidoc
  docs/en/stack/ml/get-started/ml-gs-jobs.asciidoc
  docs/en/stack/ml/get-started/ml-gs-next.asciidoc
  docs/en/stack/ml/get-started/ml-gs-results.asciidoc
  docs/en/stack/ml/get-started/ml-gs-visualizer.asciidoc
  docs/en/stack/ml/redirects.asciidoc
Labels: :ml, backport-8.4, v8.5.0, v8.4.2

#2231 Update .backportrc.json
  .backportrc.json
Labels: backport-skip

#2232 Add 8.5 to mergify
  .mergify.yml
Labels: backport-skip

#2233 [DOCS] Fix hard-coded link in glossary
  docs/en/glossary/glossary.asciidoc
Labels: backport-skip

#2234 [DOCS] Change inference functionality to beta
  docs/en/stack/ml/nlp/ml-nlp.asciidoc
Labels: :ml, v8.5.0, backport-8.5, v8.6.0

#2236 Update .mergify.yml
  .mergify.yml
Labels: backport-skip

#2237 [8.5][DOCS] Change inference functionality to beta (#2234)
  docs/en/stack/ml/nlp/ml-nlp.asciidoc
Labels: backport
