Repository elastic/stack-docs, pull requests merged in 2022-05, with the labels that each got.

#2091 add note to use 127.0.0.1 when connecting to Kibana docker container
  docs/en/getting-started/get-started-docker.asciidoc
Labels: backport-8.1

#2099 [DOCS] Add Elastic Security breaking changes to Installation and Upgrade Guide for 8.2
  docs/en/install-upgrade/breaking.asciidoc
Labels: v8.2.0, backport-8.2, release-notes

#2125 Adds Painless-related deprecation warnings limitation and removes POST data API limitation
  docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
Labels: :ml, v7.17, v8.2.0, backport-8.1, backport-8.0, backport-7.17, backport-8.2, v8.1.3, v8.3.0, v8.0.2

#2130 [DOCS] Adds Eland install instructions to NLP model import
  docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
Labels: :ml, v8.2.0, backport-8.2, v8.3.0

#2132 [DOCS] Adds authentication methods to NLP import guide
  docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
Labels: :ml, v8.2.0, backport-8.2, v8.3.0

#2123 [DOCS] Deprecate deployment infer API
  docs/en/stack/ml/nlp/ml-nlp-apis.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
Labels: :ml, backport-skip, v8.3.0

#2135 [DOCS] Fix nesting of eland authentication methods
  docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
Labels: :ml, backport-8.2, v8.3.0, v8.2.1

#2137 [DOCS] Remove trained model testing limitation
  docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
Labels: :ml, backport-skip, v8.3.0

#2138 Adds question answering task to Extract information NLP docs
  docs/en/stack/ml/nlp/ml-nlp-extract-info.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
Labels: :ml, backport-skip, v8.3.0

#2140 [DOCS] Updates list of security and auditbeat anomaly detection configurations
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
  docs/en/stack/ml/redirects.asciidoc
Labels: :ml, backport-skip, v8.3.0

#2141 Clarify login flow
  docs/en/getting-started/get-started-docker.asciidoc
Labels: enhancement, backport-8.1, backport-8.0, backport-8.2

#2145 Adds 8.3 to backport and mergify tools
  .backportrc.json
  .mergify.yml
Labels: backport-skip, v8.4.0

#2149 Removes/updates screenshots in ML docs
  docs/en/stack/ml/anomaly-detection/images/ml-single-metric-job-summary.jpg
  docs/en/stack/ml/anomaly-detection/images/multibucketanalysis.jpg
  docs/en/stack/ml/anomaly-detection/images/overview-forecast.jpg
  docs/en/stack/ml/anomaly-detection/images/overview-smv.jpg
  docs/en/stack/ml/anomaly-detection/job-tips.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-finding-anomalies.asciidoc
  docs/en/stack/ml/df-analytics/images/trained-model-management.jpg
  docs/en/stack/ml/df-analytics/ml-dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
  docs/en/stack/ml/get-started/images/ml-gs-create-web-jobs-1.jpg
  docs/en/stack/ml/get-started/ml-gs-jobs.asciidoc
Labels: :ml, v8.3.0, backport-8.3, v8.4.0

#2146 Adds guide about creating anomaly jobs from Lens visuals
  docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc
  docs/en/stack/ml/anomaly-detection/images/create-ad-job-from-lens.jpg
  docs/en/stack/ml/anomaly-detection/images/select-layer-for-job.jpg
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-jobs-from-visuals.asciidoc
Labels: :ml, v8.3.0, backport-8.3, v8.4.0
