Repository elastic/stack-docs, pull requests merged in 2022-07, with the labels that each got.

#2176 Update definition of Elastic Agent
  docs/en/glossary/glossary.asciidoc
Labels: backport-8.3

#2174 [DOCS] Improves NLP docs by adding details on deployment setting options
  docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
Labels: :ml, backport-skip, v8.4.0

#2182 [DOCS] Adds links to the inference example that point to the NLP blog posts
  docs/en/stack/ml/nlp/ml-nlp-inference.asciidoc
Labels: :ml, backport-8.2, v8.2.1, backport-8.3, v8.4.0, v8.3.1, nlp

#2186 [DOCS] Add missing links in anomaly detection resources
  docs/en/stack/ml/anomaly-detection/ml-ad-resources.asciidoc
Labels: :ml, backport-8.1, backport-8.0, backport-8.2, backport-8.3, v8.4.0

#2192 Update .mergify.yml
  .mergify.yml
Labels: backport-skip

#2191 Update .backportrc.json
  .backportrc.json
Labels: backport-skip

#2193 [DOCS] Add/Update time series data and related terms
  docs/en/glossary/glossary.asciidoc
Labels: backport-skip
