Repository elastic/stack-docs, pull requests merged in 2022-08, with the labels that each got.

#2183 [ML] Add suitable scoring functions for Text embedding models
  docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
Labels: :ml, backport-8.1, backport-8.0, backport-8.2, backport-8.3, v8.4.0, nlp

#2198 [DOCS] Adds technical preview admonition to NLP landing page
  docs/en/stack/ml/nlp/ml-nlp.asciidoc
Labels: :ml, backport-8.1, backport-8.0, backport-8.2, v8.0.2, v8.2.1, v8.1.4, backport-8.3, v8.4.0, v8.3.3, backport-8.4

#2204 [DOCS] Add notes about security for ML anomaly detection job results
  docs/en/stack/ml/setup.asciidoc
Labels: :ml, backport-7.17, backport-8.3, backport-8.4

#2210 [DOCS] Refresh screenshots in mapping anomalies
  docs/en/stack/ml/anomaly-detection/images/weblogs-anomaly-explorer-vectors.jpg
  docs/en/stack/ml/anomaly-detection/images/weblogs-anomaly-explorer-vectors.png
  docs/en/stack/ml/anomaly-detection/images/weblogs-data-visualizer-choropleth.jpg
  docs/en/stack/ml/anomaly-detection/images/weblogs-data-visualizer-choropleth.png
  docs/en/stack/ml/anomaly-detection/images/weblogs-multimetric-wizard-vector.jpg
  docs/en/stack/ml/anomaly-detection/images/weblogs-multimetric-wizard-vector.png
  docs/en/stack/ml/anomaly-detection/mapping-anomalies.asciidoc
Labels: :ml, backport-skip, v8.5.0

#2209 [DOCS] Adds list of supported functions to jobs-from-visualizations guide
  docs/en/stack/ml/anomaly-detection/ml-jobs-from-visuals.asciidoc
Labels: :ml, backport-8.3, v8.4.0, v8.3.3, backport-8.4

#2213 Updates Kibana breaking changes link for 8.4.0
  docs/en/install-upgrade/breaking.asciidoc
Labels: v8.4.0

#2215 Update link for Beats breaking changes include
  docs/en/install-upgrade/breaking.asciidoc
Labels: v8.4.0

#2217 [DOCS] Add Elastic Security breaking changes to Installation and Upgrade Guide for 8.4
  docs/en/install-upgrade/breaking.asciidoc
Labels: release-notes, v8.4.0, backport-8.4

#2219 Auto-generate preview links for DOC PRs
  .github/workflows/docs-preview-links.yml
Labels: backport-8.4, v8.5.0
