Repository elastic/stack-docs, pull requests merged in 2023-03, with the labels that each got.

#2338 Adjusts the description of regression and classification algorithms
  docs/en/stack/ml/df-analytics/ml-dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-regression.asciidoc
Labels: :ml, v8.7.0, backport-8.6, v8.6.1, v8.8.0, backport-8.7

#2352 [DOCS] Updates NLP deployment docs with more info on model test
  docs/en/stack/ml/nlp/images/ml-nlp-test-lang-ident.png
  docs/en/stack/ml/nlp/images/ml-nlp-test-ner.png
  docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
Labels: :ml, nlp, v8.7.0, backport-8.6, v8.6.1, v8.8.0, backport-8.7

#2355 Update security breaking changes link from 8.6 to 8.7
  docs/en/install-upgrade/breaking.asciidoc
Labels: release-notes, v8.7.0, backport-8.7
