Repository elastic/stack-docs, pull requests merged in 2023-08, with the labels that each got.

#2492 Restore deep link to knn semantic search
  docs/en/stack/ml/nlp/ml-nlp-text-emb-vector-search-example.asciidoc
Labels: backport-8.9

#2503 [8.7] [Install/Upgrade] Fix Beats 8.8 breaking changes (#2502)
  docs/en/install-upgrade/breaking.asciidoc
Labels: backport

#2504 [8.6] [Install/Upgrade] Fix Beats 8.8 breaking changes (#2502)
  docs/en/install-upgrade/breaking.asciidoc
Labels: backport

#2505 [DOCS] Updates ML getting started
  docs/en/stack/ml/get-started/images/ml-gs-data-keyword.jpg
  docs/en/stack/ml/get-started/images/ml-gs-data-metric.jpg
  docs/en/stack/ml/get-started/ml-getting-started.asciidoc
  docs/en/stack/ml/get-started/ml-gs-forecasts.asciidoc
  docs/en/stack/ml/get-started/ml-gs-jobs.asciidoc
  docs/en/stack/ml/get-started/ml-gs-results.asciidoc
  docs/en/stack/ml/get-started/ml-gs-visualizer.asciidoc
Labels: :ml, backport-8.8, v8.9.0, v8.8.2, backport-8.9, v8.10

#2510 Add ECE to air-gapped install page
  docs/en/install-upgrade/air-gapped-install.asciidoc
Labels: backport-8.9

#2512 [8.9] Add ECE to air-gapped install page (#2510)
  docs/en/install-upgrade/air-gapped-install.asciidoc
Labels: backport

#2513 Fix link to Enterprise Search release notes
  docs/en/install-upgrade/breaking.asciidoc
Labels: v8.9.0, backport-8.9, v8.10

#2517 [DOCS] Fixes NLP size requirement on model reference page
  docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
Labels: :ml, backport-8.8, v8.9.0, v8.8.2, backport-8.9, v8.10

#2496 Add package ml jobs
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Labels: backport-8.9

#2521 Agent upgrade order
  docs/en/install-upgrade/air-gapped-install.asciidoc
Labels: backport-8.9

#2523 Update mergify and backport tool for 8.10
  .backportrc.json
  .mergify.yml
Labels: backport-skip

#2524 [DOCS] Improves documentation about deploying DFA trained models
  docs/en/stack/ml/df-analytics/images/ml-dfa-inference-pipeline.png
  docs/en/stack/ml/df-analytics/images/ml-dfa-inference-processor.png
  docs/en/stack/ml/df-analytics/images/ml-dfa-trained-models-ui.png
  docs/en/stack/ml/df-analytics/ml-dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-shared.asciidoc
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Labels: :ml, v8.10, backport-8.10, v8.11

#2526 [8.10] [DOCS] Improves documentation about deploying DFA trained models (#2524)
  docs/en/stack/ml/df-analytics/images/ml-dfa-inference-pipeline.png
  docs/en/stack/ml/df-analytics/images/ml-dfa-inference-processor.png
  docs/en/stack/ml/df-analytics/images/ml-dfa-trained-models-ui.png
  docs/en/stack/ml/df-analytics/ml-dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-regression.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-shared.asciidoc
  docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Labels: backport

#2527 [DOCS] Fixes field type in ELSER conceptual
  docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
Labels: :ml, nlp, ELSER, backport-8.8, v8.9.0, v8.8.2, backport-8.9, v8.10, backport-8.10, v8.11

#2530 [8.10] [DOCS] Fixes field type in ELSER conceptual. (#2527)
  docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
Labels: backport

#2533 [8.10] [DOCS] Add default ports for Elastic Stack components (#2531)
  docs/en/install-upgrade/installing-stack.asciidoc
Labels: backport

#2534 [DOCS] Removes // from start trained model deployment link
  docs/en/stack/ml/nlp/ml-nlp-apis.asciidoc
Labels: backport-8.9

#2535 [DOCS] Removes // from filebeat link
  docs/en/siem/overview.asciidoc
Labels: v7.8.0

#2537 Removes // from spaces link
  docs/en/glossary/terms/feature-controls.asciidoc
Labels: v8.1.0, v8.9.0, backport-8.9, v8.10, backport-8.10
