Repository elastic/stack-docs, pull requests merged in 2023-02, with the labels that each got.

#2323 Removes reference to semantic search endpoint from docs
  docs/en/stack/ml/nlp/ml-nlp-apis.asciidoc
Labels: :ml, backport-skip, v8.7.0

#2324 Update .backportrc.json for 8.7
  .backportrc.json
Labels: backport-skip, v8.7.0

#2325 Update .mergify.yml
  .mergify.yml
Labels: backport-skip

#2328 [DOCS] Adds description of the geo anomaly job to the job types page
  docs/en/stack/ml/anomaly-detection/ml-ad-job-types.asciidoc
Labels: :ml, v8.7.0, v8.8.0, backport-8.7

#2330 [DOCS] Adds info about available field statistics in AD and DFA wizards
  docs/en/stack/ml/anomaly-detection/job-tips.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-classification.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-outlier-detection.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-regression.asciidoc
  docs/en/stack/ml/get-started/ml-getting-started.asciidoc
  docs/en/stack/ml/get-started/ml-gs-jobs.asciidoc
  docs/en/stack/ml/get-started/ml-gs-visualizer.asciidoc
Labels: :ml, v8.7.0, v8.8.0, backport-8.7

#2326 [ML] Adds an ML landing page to ML book
  docs/en/stack/ml/index-custom-title-page.html
Labels: :ml, v8.7.0, v8.8.0, backport-8.7

#2333 [DOCS] Fixes typo in link text
  docs/en/stack/ml/index-custom-title-page.html
Labels: :ml, v8.7.0, v8.8.0, backport-8.7

#2335 Update NLP example to use semantic search
  docs/en/stack/ml/nlp/ml-nlp-text-emb-vector-search-example.asciidoc
Labels: :ml, v8.7.0, backport-8.7

#2339 Update ML docs for NER support
  docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
Labels: :ml, nlp, backport-8.4, v8.5.0, v8.4.2, backport-8.5, v8.7.0, backport-8.6, v8.6.1, v8.8.0, backport-8.7
