Repository elastic/stack-docs, pull requests merged in 2023-01, with the labels that each got.

#2300 [DOCS] Fix 8.6 breaking changes
  docs/en/install-upgrade/breaking.asciidoc
Labels: v8.6.0

#2301 [DOCS] Amends the instructions in the anomaly detection tutorial
  docs/en/stack/ml/get-started/ml-gs-jobs.asciidoc
  docs/en/stack/ml/get-started/ml-gs-results.asciidoc
Labels: :ml, backport-8.4, v8.5.0, v8.4.2, backport-8.5, v8.6.0, v8.7.0, backport-8.6

#2305 Adds docs about how anomaly scores are calculated
  docs/en/stack/ml/anomaly-detection/images/detailed-single-metric.jpg
  docs/en/stack/ml/anomaly-detection/images/renormalization-score-reduction.jpg
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-concepts.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-explain.asciidoc
Labels: :ml, v8.7.0, backport-8.6, v8.6.1

#2307 [DOCS] Adds anomaly job types docs to ML book
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-concepts.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-job-types.asciidoc
Labels: :ml, v8.5.0, backport-8.5, v8.7.0, backport-8.6, v8.6.1

#2310 Marks recommended models in the third party models list
  docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
Labels: :ml, nlp, v8.7.0, backport-8.6, v8.6.1

#2312 Adds limitation item about anomaly detection jobs and frozen tier data
  docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
Labels: :ml, v8.7.0, backport-8.6, v8.6.1

#2311 Fixes GH links on Apache and Nginx OOTB job pages
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
Labels: :ml, backport-7.17, backport-8.2, v8.2.1, backport-8.3, v8.3.3, backport-8.4, v8.5.0, v8.4.2, v7.17.7, backport-8.5, v8.7.0, backport-8.6, v8.6.1

#2314 Removes pages from the how-to section
  docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
  docs/en/stack/ml/anomaly-detection/anomaly-how-tos.asciidoc
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-run-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
  docs/en/stack/ml/get-started/ml-gs-results.asciidoc
  docs/en/stack/ml/redirects.asciidoc
Labels: :ml, v8.7.0, backport-8.6, v8.6.1
