Repository elastic/stack-docs, pull requests merged in 2023-07, with the labels that each got.

#2452 [DOCS] Added missing quotations for "docs" post request
  docs/en/stack/ml/nlp/ml-nlp-extract-info.asciidoc
Labels: backport-8.8, v8.9.0, v8.8.2, backport-8.9, v8.10

#2453 Fixes indentation on third party models page
  docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
Labels: :ml, backport-8.8, v8.9.0, v8.8.2, backport-8.9, v8.10

#2456 [DOCS] Removes sentence similarity models from QA list
  docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
Labels: :ml, nlp, backport-8.9

#2459 [DOCS] Fixes typo on text embedding page
  docs/en/stack/ml/nlp/ml-nlp-text-emb-vector-search-example.asciidoc
Labels: :ml, backport-8.3, nlp, backport-8.4, backport-8.5, backport-8.6, backport-8.7, backport-8.8, backport-8.9

#2467 [DOCS] Updates screenshot of start trained model deployment
  docs/en/stack/ml/nlp/images/ml-nlp-deploy-elser.png
  docs/en/stack/ml/nlp/images/ml-nlp-deployment-id-elser.png
  docs/en/stack/ml/nlp/images/ml-nlp-deployment-id.png
  docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
Labels: :ml, nlp, ELSER, v8.9.0, backport-8.9, v8.10

#2469 [DOCS] Amends text with embedding_size info
  docs/en/stack/ml/nlp/ml-nlp-text-emb-vector-search-example.asciidoc
Labels: :ml, nlp, backport-8.8, v8.9.0, v8.8.2, backport-8.9, v8.10

#2474 Temporarily remove deep link to knn semantic search
  docs/en/stack/ml/nlp/ml-nlp-text-emb-vector-search-example.asciidoc
Labels: :ml, v8.9.0, backport-8.9, v8.10

#2478 Adds xlm roberta to the list of supported NLP model architectures
  docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
Labels: nlp, backport-8.9, v8.10

#2472 [DOCS] Adds ELSER benchmark info
  docs/en/stack/ml/nlp/images/ml-nlp-elser-average-ndcg.png
  docs/en/stack/ml/nlp/images/ml-nlp-elser-ndcg10-beir.png
  docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
Labels: :ml, WIP, nlp, ELSER, backport-8.8, v8.9.0, v8.8.2, backport-8.9, v8.10

#2458 Add air-gapped install docs
  docs/en/install-upgrade/air-gapped-install.asciidoc
  docs/en/install-upgrade/images/air-gapped-configure-logging.png
  docs/en/install-upgrade/index.asciidoc
Labels: backport-8.8, backport-8.9

#2484 Updates broken manifest file links
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Labels: bug, backport-8.7, backport-8.8, backport-8.9

#2488 Add air-gapped install instructions for Elasticsearch and Machine Learning
  docs/en/install-upgrade/air-gapped-install.asciidoc
Labels: backport-8.8, backport-8.9

#2489 [DOCS] Update breaking changes links
  docs/en/install-upgrade/breaking.asciidoc
Labels: backport-skip, v8.9.0

#2493 Link to Kibana 8.9 breaking changes
  docs/en/install-upgrade/breaking.asciidoc
Labels: backport-skip, v8.9.0

#2477 [DOCS] Update security breaking changes link from 8.8.2 to 8.9.0
  docs/en/install-upgrade/breaking.asciidoc
Labels: release-notes, backport-8.9
