Repository elastic/stack-docs, pull requests merged in 2024-06, with the labels that each got.

#2678 Fixed typo
  docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
Labels: :ml, backport-8.13, backport-8.14

#2727 [8.14] Fixed typo (#2678)
  docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
Labels: backport

#2728 [8.13] Fixed typo (#2678)
  docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
Labels: backport

#2729 [main] Fixed typo (#2678)
  docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
Labels: backport-skip

#2713 Update ml-limitations.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
Labels: v8.13, v8.14, v.8.15, backport-8.14, backport-8.15

#2730 [8.14] [Backport] Update ml-limitations.asciidoc (#2713)
  docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
Labels: :ml, backport, v8.14

#2731 [Forwardport] Update ml-limitations.asciidoc (#2713)
  docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
Labels: :ml, backport-skip, v.8.15

#2732 Add license
  LICENSE
  README.md
Labels: backport-7.17, backport-8.14

#2714 Adds anomaly detection FAQ items to the Troubleshooting page
  docs/en/stack/ml/anomaly-detection/ml-ad-troubleshooting.asciidoc
Labels: :ml, v8.13, backport-8.13, v8.14, v.8.15, backport-8.14

#2739 Update ml-nlp-deploy-models.asciidoc (#2738)
  docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
Labels: :ml, backport-skip, nlp, v.8.15

#2740 Fixes typo in ML getting started
  docs/en/stack/ml/get-started/ml-getting-started.asciidoc
Labels: :ml, v8.13, backport-8.13, v8.14, v.8.15, backport-8.14
