Repository elastic/stack-docs, pull requests merged in 2024-09, with the labels that each got.

#2777 [DOCS] [URGENT] Update e5 warranty verbiage
  docs/en/stack/ml/nlp/ml-nlp-e5.asciidoc
Labels: backport-8.15

#2781 Fixes screenshot in categorization job how-to
  docs/en/stack/ml/anomaly-detection/images/ml-category-analyzer.png
  docs/en/stack/ml/anomaly-detection/ml-detect-categories.asciidoc
Labels: :ml, v8.14, v.8.15, backport-8.14, backport-8.15, v8.16

#2785 Updates link text on Metrics configuration page
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc
Labels: :ml, v8.14, v.8.15, backport-8.14, backport-8.15, v8.16

#2784 Adds population job how to guide
  docs/en/stack/ml/anomaly-detection/anomaly-how-tos.asciidoc
  docs/en/stack/ml/anomaly-detection/images/ml-population-anomalies.png
  docs/en/stack/ml/anomaly-detection/images/ml-population-anomaly.png
  docs/en/stack/ml/anomaly-detection/images/ml-population-wizard.png
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-ad-job-types.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-detect-categories.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-population-analysis.asciidoc
  docs/en/stack/ml/redirects.asciidoc
Labels: :ml, v8.14, v.8.15, backport-8.14, backport-8.15, v8.16

#2790 Add 8.x branch to backport and mergify configuration
  .backportrc.json
  .mergify.yml
Labels: backport-8.16

#2796 [DOCS] Adds pre-cleaning recommendation to ELSER docs
  docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
Labels: :ml, nlp, ELSER, v.8.15, backport-8.15, v8.16, backport-8.16
