Repository elastic/stack-docs, pull requests merged in 2024-11, with the labels that each got.

#2864 Updates phrasing when referring to pages
  docs/en/stack/ml/anomaly-detection/ml-ad-run-jobs.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-detect-categories.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-jobs-from-visuals.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-population-analysis.asciidoc
  docs/en/stack/ml/anomaly-detection/ml-revert-model-snapshot.asciidoc
  docs/en/stack/ml/df-analytics/ml-dfa-shared.asciidoc
  docs/en/stack/ml/get-started/ml-gs-results.asciidoc
  docs/en/stack/ml/get-started/ml-gs-visualizer.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-e5.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-inference.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-ner-example.asciidoc
  docs/en/stack/ml/setup.asciidoc
Labels: v8.16, backport-8.16

#2866 Updates ELSER documentation to use 'elasticsearch' service
  docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
Labels: v8.16, backport-8.16

#2871 Fixes typo on the "ELSER – Elastic Learned Sparse EncodeR" page
  docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
Labels: backport-8.16, backport-8.17

#2876 Add 8.17 to backport configs
  .backportrc.json
  .mergify.yml
Labels: backport-skip

#2875 Add 8.17 to backport configs
  .backportrc.json
  .mergify.yml
Labels: backport-skip

#2878 Update "Download and deploy ELSER" snippet with adaptive allocations
  docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
Labels: backport-8.16, backport-8.17

#2877 [ML] Add ML limitation for ingesting large documents
  docs/en/stack/ml/nlp/ml-nlp-limitations.asciidoc
Labels: bug, :ml, nlp, ELSER, v8.16, backport-8.17, backport-8.x

#2882 [ML] Add ML limitation for ingesting large documents
  docs/en/stack/ml/nlp/ml-nlp-limitations.asciidoc
Labels: :ml, backport

#2883 [ML] Add ML limitation for ingesting large documents
  docs/en/stack/ml/nlp/ml-nlp-limitations.asciidoc
Labels: :ml, backport
