Repository elastic/stack-docs, pull requests merged in 2024-04, with the labels that each got.

#2680 Updates ELSER v2 benchmark table
  docs/en/stack/ml/nlp/images/ml-nlp-bm25-elser-v2.png
Labels: :ml, nlp, ELSER, v8.13, backport-8.13, v8.14

#2679 Adds section about the different options to use NLP in the stack
  docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
Labels: :ml, nlp, v8.13, backport-8.13, v8.14

#2683 Remove FIPS warning as of ES 8.13
  docs/en/install-upgrade/upgrading-elasticsearch.asciidoc
Labels: backport-8.13, v8.14

#2685 Add 'what's next' links to install guide
  docs/en/install-upgrade/installing-stack-demo-secure.asciidoc
  docs/en/install-upgrade/installing-stack-demo-self.asciidoc
Labels: backport-8.13

#2687 Updates legal disclaimer for E5
  docs/en/stack/ml/nlp/ml-nlp-e5.asciidoc
Labels: :ml, v8.12, v8.13, backport-8.12, backport-8.13, v8.14, v.8.15, backport-8.14

#2690 Updates .backportrc.json and .mergify.yaml for 8.14
  .backportrc.json
  .mergify.yml
Labels: backport-skip

#2691 [8.14] Updates legal disclaimer for E5 (#2687)
  docs/en/stack/ml/nlp/ml-nlp-e5.asciidoc
Labels: backport

#2693 Adds inference API links to the NLP APIs page
  docs/en/stack/ml/nlp/ml-nlp-apis.asciidoc
Labels: :ml, nlp, v8.13, backport-8.13, v8.14, v.8.15, backport-8.14

#2696 Adds important callout about granting ML:all feature privilege to the setup page
  docs/en/stack/ml/setup.asciidoc
Labels: :ml, v8.13, backport-8.13, v8.14, v.8.15, backport-8.14

#2699 Adjust important admonition in Kibana security section of ML setup page
  docs/en/stack/ml/setup.asciidoc
Labels: :ml, v8.13, backport-8.13, v8.14, v.8.15, backport-8.14

#2702 Removes E5 limitation that no longer applicable
  docs/en/stack/ml/nlp/ml-nlp-e5.asciidoc
  docs/en/stack/ml/nlp/ml-nlp-limitations.asciidoc
Labels: :ml, nlp, v8.12, v8.13, backport-8.12, backport-8.13, v8.14, v.8.15, backport-8.14
