Repository elastic/stack-docs, pull requests merged in 2024-05, with the labels that each got.

#2706 Update installing-stack-demo-secure.asciidoc
  docs/en/install-upgrade/installing-stack-demo-secure.asciidoc
Labels: backport-8.13, backport-8.14

#2707 Update installing-stack-demo-secure.asciidoc
  docs/en/install-upgrade/installing-stack-demo-secure.asciidoc
Labels: backport-8.13, backport-8.14

#2715 Fixes typo in link text on AD how-to main page
  docs/en/stack/ml/anomaly-detection/anomaly-how-tos.asciidoc
Labels: :ml, v8.13, backport-8.13, v8.14, v.8.15, backport-8.14

#2719 Documents ELSER autoscale limitation
  docs/en/stack/ml/nlp/ml-nlp-limitations.asciidoc
Labels: :ml, nlp, ELSER, v8.12, v8.13, backport-8.12, backport-8.13, v8.14, v.8.15, backport-8.14

#2716 Fix links to E5 optimized version
  docs/en/stack/ml/nlp/ml-nlp-e5.asciidoc
Labels: :ml, nlp, v8.12, v8.13, backport-8.12, backport-8.13, v8.14, v.8.15, backport-8.14
