Repository elastic/stack-docs, pull requests merged in 2025-01, with the labels that each got.

#2889 new reference architectures
  docs/en/reference-architectures/hot-frozen.asciidoc
  docs/en/reference-architectures/images/frozen.png
  docs/en/reference-architectures/images/hot-frozen.png
  docs/en/reference-architectures/images/hot.png
  docs/en/reference-architectures/images/kibana.png
  docs/en/reference-architectures/images/machine-learning.png
  docs/en/reference-architectures/images/master.png
  docs/en/reference-architectures/index.asciidoc
  docs/en/reference-architectures/reference-architectures-overview.asciidoc
Labels: backport-skip

#2899 fixing duplicate id
  docs/en/reference-architectures/reference-architectures-overview.asciidoc
Labels: backport-skip

#2900 adding shared attributes
  docs/en/reference-architectures/index.asciidoc
Labels: backport-skip

#2903 fix bad link
  docs/en/reference-architectures/hot-frozen.asciidoc
Labels: backport-skip

#2904 restore link
  docs/en/reference-architectures/hot-frozen.asciidoc
Labels: backport-skip

#2902 Adds Demi as codeowner to glossary terms
  .github/CODEOWNERS
Labels: backport-skip

#2901 Add sparse embedding models to list of compatible models
  docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
Labels: backport-8.17

#2906 Changes blog URL on Rerank page
  docs/en/stack/ml/nlp/ml-nlp-elastic-rerank.asciidoc
Labels: :ml, nlp, backport-8.17, backport-8.x, v8.17, v8.18, v9.0

#2911 [DOCS] Move reference pages out of appendix for migration
  docs/en/stack/ml/anomaly-detection/functions/ml-count-functions.asciidoc
  docs/en/stack/ml/anomaly-detection/functions/ml-functions.asciidoc
  docs/en/stack/ml/anomaly-detection/functions/ml-geo-functions.asciidoc
  docs/en/stack/ml/anomaly-detection/functions/ml-info-functions.asciidoc
  docs/en/stack/ml/anomaly-detection/functions/ml-metric-functions.asciidoc
  docs/en/stack/ml/anomaly-detection/functions/ml-rare-functions.asciidoc
  docs/en/stack/ml/anomaly-detection/functions/ml-sum-functions.asciidoc
  docs/en/stack/ml/anomaly-detection/functions/ml-time-functions.asciidoc
  docs/en/stack/ml/anomaly-detection/index.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
Labels: backport-skip, v9.0

#2909 Add details for the new `Security: Host` module to OOTB ML jobs doc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Labels: v8.18, v9.0, backport-8.18

#2824 Add BGE reranker model to list of recommended text similarity models
  docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
Labels: backport-8.13, backport-8.14, backport-8.15, backport-8.16

#2917 [8.x] Add BGE reranker model to list of recommended (#2824)
  docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
Labels: :ml, backport, nlp, v8.18

#2918 [8.17] Add BGE reranker model to list of recommended (#2824)
  docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
Labels: :ml, backport, nlp

#2919 [DOCS] Fixes a config line in ELSER docs
  docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
Labels: :ml, nlp, ELSER, backport-8.17, backport-8.x, v8.17, v8.18, v9.0

#2912 [DOCS] Remove temporary function files
  docs/en/stack/ml/anomaly-detection/functions/ml-count-functions.asciidoc
  docs/en/stack/ml/anomaly-detection/functions/ml-functions.asciidoc
  docs/en/stack/ml/anomaly-detection/functions/ml-geo-functions.asciidoc
  docs/en/stack/ml/anomaly-detection/functions/ml-info-functions.asciidoc
  docs/en/stack/ml/anomaly-detection/functions/ml-metric-functions.asciidoc
  docs/en/stack/ml/anomaly-detection/functions/ml-rare-functions.asciidoc
  docs/en/stack/ml/anomaly-detection/functions/ml-sum-functions.asciidoc
  docs/en/stack/ml/anomaly-detection/functions/ml-time-functions.asciidoc
  docs/en/stack/ml/anomaly-detection/index.asciidoc
Labels: :ml, backport-skip, v9.0

#2938 Update installing-stack-demo-secure.asciidoc
  docs/en/install-upgrade/installing-stack-demo-secure.asciidoc
Labels: backport-8.17, backport-8.x, v8.17, v8.18, v9.0

#2910 github-action: Add AsciiDoc freeze warning
  .github/workflows/comment-on-asciidoc-changes.yml
Labels: backport-skip
