Repository elastic/stack-docs, pull requests merged in 2025-03, with the labels that each got.

#2980 [9.0] Updates ML migration guide
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: :ml, v9.0

#2995 Serverless changelog for March 17
  docs/en/install-upgrade/serverless-changelog.asciidoc
Labels: backport-skip

#2996 Mention semantic_text going GA in serverless changelog
  docs/en/install-upgrade/serverless-changelog.asciidoc
Labels: backport-skip

#2957 Correct code sample
  docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
Labels: backport-8.16, backport-8.18

#2998 Doc: Logstash pre-9.0.0 release notes
  docs/en/install-upgrade/release-notes/release-notes-logstash-beta1.asciidoc
  docs/en/install-upgrade/release-notes/release-notes-logstash-rc1.asciidoc
  docs/en/install-upgrade/release-notes/release-notes-logstash.asciidoc
Labels: release-notes

#2999 Fix links on Security anomaly detection config page
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Labels: backport-8.18

#3003 [DOCS] Add Elasticsearch 9.0 rc1 release notes
  docs/en/install-upgrade/release-notes/release-notes-elasticsearch-beta1.asciidoc
  docs/en/install-upgrade/release-notes/release-notes-elasticsearch-rc1.asciidoc
Labels: backport-skip

#3006 [DOCS] Beats 9.0 rc1 release notes
  docs/en/install-upgrade/release-notes/release-notes-beats-rc1.asciidoc
  docs/en/install-upgrade/release-notes/release-notes-beats.asciidoc
Labels: backport-skip

#3002 [9.0] Amends the anomaly detection upgrade instructions
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: :ml, backport-8.x, v8.18, v9.0, backport-8.18

#3008 Fixes OOTB configuration links
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
  docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
  docs/en/stack/ml/get-started/ml-gs-jobs.asciidoc
Labels: backport-8.x, backport-8.18

#3009 Expand guidance on testing an upgrade
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: backport-8.17, v8.18, backport-8.18

#3010 Expand guidance on testing an upgrade (#3009)
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: backport, v8.18

#3011 Expand guidance on testing an upgrade (#3009)
  docs/en/install-upgrade/upgrading-stack.asciidoc
Labels: backport, v8.17
